// Code generated by ent, DO NOT EDIT.

package sub2apioptimizelog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the sub2apioptimizelog type in the database.
	Label = "sub2api_optimize_log"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldProviderID holds the string denoting the provider_id field in the database.
	FieldProviderID = "provider_id"
	// FieldScheduleID holds the string denoting the schedule_id field in the database.
	FieldScheduleID = "schedule_id"
	// FieldTrigger holds the string denoting the trigger field in the database.
	FieldTrigger = "trigger"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldTotal holds the string denoting the total field in the database.
	FieldTotal = "total"
	// FieldOptimized holds the string denoting the optimized field in the database.
	FieldOptimized = "optimized"
	// FieldSkipped holds the string denoting the skipped field in the database.
	FieldSkipped = "skipped"
	// FieldFailed holds the string denoting the failed field in the database.
	FieldFailed = "failed"
	// FieldDetail holds the string denoting the detail field in the database.
	FieldDetail = "detail"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldFinishedAt holds the string denoting the finished_at field in the database.
	FieldFinishedAt = "finished_at"
	// EdgeProvider holds the string denoting the provider edge name in mutations.
	EdgeProvider = "provider"
	// EdgeSchedule holds the string denoting the schedule edge name in mutations.
	EdgeSchedule = "schedule"
	// Table holds the table name of the sub2apioptimizelog in the database.
	Table = "sub2api_optimize_logs"
	// ProviderTable is the table that holds the provider relation/edge.
	ProviderTable = "sub2api_optimize_logs"
	// ProviderInverseTable is the table name for the Sub2APIProvider entity.
	// It exists in this package in order to avoid circular dependency with the "sub2apiprovider" package.
	ProviderInverseTable = "sub2api_providers"
	// ProviderColumn is the table column denoting the provider relation/edge.
	ProviderColumn = "provider_id"
	// ScheduleTable is the table that holds the schedule relation/edge.
	ScheduleTable = "sub2api_optimize_logs"
	// ScheduleInverseTable is the table name for the Sub2APIOptimizeSchedule entity.
	// It exists in this package in order to avoid circular dependency with the "sub2apioptimizeschedule" package.
	ScheduleInverseTable = "sub2api_optimize_schedules"
	// ScheduleColumn is the table column denoting the schedule relation/edge.
	ScheduleColumn = "schedule_id"
)

// Columns holds all SQL columns for sub2apioptimizelog fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldProviderID,
	FieldScheduleID,
	FieldTrigger,
	FieldStatus,
	FieldTotal,
	FieldOptimized,
	FieldSkipped,
	FieldFailed,
	FieldDetail,
	FieldStartedAt,
	FieldFinishedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultTrigger holds the default value on creation for the "trigger" field.
	DefaultTrigger string
	// TriggerValidator is a validator for the "trigger" field. It is called by the builders before save.
	TriggerValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultTotal holds the default value on creation for the "total" field.
	DefaultTotal int
	// DefaultOptimized holds the default value on creation for the "optimized" field.
	DefaultOptimized int
	// DefaultSkipped holds the default value on creation for the "skipped" field.
	DefaultSkipped int
	// DefaultFailed holds the default value on creation for the "failed" field.
	DefaultFailed int
)

// OrderOption defines the ordering options for the Sub2APIOptimizeLog queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByProviderID orders the results by the provider_id field.
func ByProviderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderID, opts...).ToFunc()
}

// ByScheduleID orders the results by the schedule_id field.
func ByScheduleID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScheduleID, opts...).ToFunc()
}

// ByTrigger orders the results by the trigger field.
func ByTrigger(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTrigger, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByTotal orders the results by the total field.
func ByTotal(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotal, opts...).ToFunc()
}

// ByOptimized orders the results by the optimized field.
func ByOptimized(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOptimized, opts...).ToFunc()
}

// BySkipped orders the results by the skipped field.
func BySkipped(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSkipped, opts...).ToFunc()
}

// ByFailed orders the results by the failed field.
func ByFailed(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFailed, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByFinishedAt orders the results by the finished_at field.
func ByFinishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinishedAt, opts...).ToFunc()
}

// ByProviderField orders the results by provider field.
func ByProviderField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProviderStep(), sql.OrderByField(field, opts...))
	}
}

// ByScheduleField orders the results by schedule field.
func ByScheduleField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newScheduleStep(), sql.OrderByField(field, opts...))
	}
}
func newProviderStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProviderInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ProviderTable, ProviderColumn),
	)
}
func newScheduleStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ScheduleInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ScheduleTable, ScheduleColumn),
	)
}
