// Code generated by ent, DO NOT EDIT.

package sub2apioptimizelog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldEQ(FieldUpdatedAt, v))
}

// ProviderID applies equality check predicate on the "provider_id" field. It's identical to ProviderIDEQ.
func ProviderID(v int64) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldEQ(FieldProviderID, v))
}

// ScheduleID applies equality check predicate on the "schedule_id" field. It's identical to ScheduleIDEQ.
func ScheduleID(v int64) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldEQ(FieldScheduleID, v))
}

// Trigger applies equality check predicate on the "trigger" field. It's identical to TriggerEQ.
func Trigger(v string) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldEQ(FieldTrigger, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldEQ(FieldStatus, v))
}

// Total applies equality check predicate on the "total" field. It's identical to TotalEQ.
func Total(v int) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldEQ(FieldTotal, v))
}

// Optimized applies equality check predicate on the "optimized" field. It's identical to OptimizedEQ.
func Optimized(v int) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldEQ(FieldOptimized, v))
}

// Skipped applies equality check predicate on the "skipped" field. It's identical to SkippedEQ.
func Skipped(v int) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldEQ(FieldSkipped, v))
}

// Failed applies equality check predicate on the "failed" field. It's identical to FailedEQ.
func Failed(v int) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldEQ(FieldFailed, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldEQ(FieldStartedAt, v))
}

// FinishedAt applies equality check predicate on the "finished_at" field. It's identical to FinishedAtEQ.
func FinishedAt(v time.Time) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldEQ(FieldFinishedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldLTE(FieldUpdatedAt, v))
}

// ProviderIDEQ applies the EQ predicate on the "provider_id" field.
func ProviderIDEQ(v int64) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldEQ(FieldProviderID, v))
}

// ProviderIDNEQ applies the NEQ predicate on the "provider_id" field.
func ProviderIDNEQ(v int64) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldNEQ(FieldProviderID, v))
}

// ProviderIDIn applies the In predicate on the "provider_id" field.
func ProviderIDIn(vs ...int64) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldIn(FieldProviderID, vs...))
}

// ProviderIDNotIn applies the NotIn predicate on the "provider_id" field.
func ProviderIDNotIn(vs ...int64) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldNotIn(FieldProviderID, vs...))
}

// ScheduleIDEQ applies the EQ predicate on the "schedule_id" field.
func ScheduleIDEQ(v int64) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldEQ(FieldScheduleID, v))
}

// ScheduleIDNEQ applies the NEQ predicate on the "schedule_id" field.
func ScheduleIDNEQ(v int64) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldNEQ(FieldScheduleID, v))
}

// ScheduleIDIn applies the In predicate on the "schedule_id" field.
func ScheduleIDIn(vs ...int64) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldIn(FieldScheduleID, vs...))
}

// ScheduleIDNotIn applies the NotIn predicate on the "schedule_id" field.
func ScheduleIDNotIn(vs ...int64) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldNotIn(FieldScheduleID, vs...))
}

// ScheduleIDIsNil applies the IsNil predicate on the "schedule_id" field.
func ScheduleIDIsNil() predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldIsNull(FieldScheduleID))
}

// ScheduleIDNotNil applies the NotNil predicate on the "schedule_id" field.
func ScheduleIDNotNil() predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldNotNull(FieldScheduleID))
}

// TriggerEQ applies the EQ predicate on the "trigger" field.
func TriggerEQ(v string) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldEQ(FieldTrigger, v))
}

// TriggerNEQ applies the NEQ predicate on the "trigger" field.
func TriggerNEQ(v string) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldNEQ(FieldTrigger, v))
}

// TriggerIn applies the In predicate on the "trigger" field.
func TriggerIn(vs ...string) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldIn(FieldTrigger, vs...))
}

// TriggerNotIn applies the NotIn predicate on the "trigger" field.
func TriggerNotIn(vs ...string) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldNotIn(FieldTrigger, vs...))
}

// TriggerGT applies the GT predicate on the "trigger" field.
func TriggerGT(v string) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldGT(FieldTrigger, v))
}

// TriggerGTE applies the GTE predicate on the "trigger" field.
func TriggerGTE(v string) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldGTE(FieldTrigger, v))
}

// TriggerLT applies the LT predicate on the "trigger" field.
func TriggerLT(v string) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldLT(FieldTrigger, v))
}

// TriggerLTE applies the LTE predicate on the "trigger" field.
func TriggerLTE(v string) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldLTE(FieldTrigger, v))
}

// TriggerContains applies the Contains predicate on the "trigger" field.
func TriggerContains(v string) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldContains(FieldTrigger, v))
}

// TriggerHasPrefix applies the HasPrefix predicate on the "trigger" field.
func TriggerHasPrefix(v string) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldHasPrefix(FieldTrigger, v))
}

// TriggerHasSuffix applies the HasSuffix predicate on the "trigger" field.
func TriggerHasSuffix(v string) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldHasSuffix(FieldTrigger, v))
}

// TriggerEqualFold applies the EqualFold predicate on the "trigger" field.
func TriggerEqualFold(v string) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldEqualFold(FieldTrigger, v))
}

// TriggerContainsFold applies the ContainsFold predicate on the "trigger" field.
func TriggerContainsFold(v string) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldContainsFold(FieldTrigger, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldContainsFold(FieldStatus, v))
}

// TotalEQ applies the EQ predicate on the "total" field.
func TotalEQ(v int) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldEQ(FieldTotal, v))
}

// TotalNEQ applies the NEQ predicate on the "total" field.
func TotalNEQ(v int) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldNEQ(FieldTotal, v))
}

// TotalIn applies the In predicate on the "total" field.
func TotalIn(vs ...int) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldIn(FieldTotal, vs...))
}

// TotalNotIn applies the NotIn predicate on the "total" field.
func TotalNotIn(vs ...int) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldNotIn(FieldTotal, vs...))
}

// TotalGT applies the GT predicate on the "total" field.
func TotalGT(v int) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldGT(FieldTotal, v))
}

// TotalGTE applies the GTE predicate on the "total" field.
func TotalGTE(v int) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldGTE(FieldTotal, v))
}

// TotalLT applies the LT predicate on the "total" field.
func TotalLT(v int) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldLT(FieldTotal, v))
}

// TotalLTE applies the LTE predicate on the "total" field.
func TotalLTE(v int) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldLTE(FieldTotal, v))
}

// OptimizedEQ applies the EQ predicate on the "optimized" field.
func OptimizedEQ(v int) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldEQ(FieldOptimized, v))
}

// OptimizedNEQ applies the NEQ predicate on the "optimized" field.
func OptimizedNEQ(v int) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldNEQ(FieldOptimized, v))
}

// OptimizedIn applies the In predicate on the "optimized" field.
func OptimizedIn(vs ...int) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldIn(FieldOptimized, vs...))
}

// OptimizedNotIn applies the NotIn predicate on the "optimized" field.
func OptimizedNotIn(vs ...int) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldNotIn(FieldOptimized, vs...))
}

// OptimizedGT applies the GT predicate on the "optimized" field.
func OptimizedGT(v int) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldGT(FieldOptimized, v))
}

// OptimizedGTE applies the GTE predicate on the "optimized" field.
func OptimizedGTE(v int) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldGTE(FieldOptimized, v))
}

// OptimizedLT applies the LT predicate on the "optimized" field.
func OptimizedLT(v int) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldLT(FieldOptimized, v))
}

// OptimizedLTE applies the LTE predicate on the "optimized" field.
func OptimizedLTE(v int) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldLTE(FieldOptimized, v))
}

// SkippedEQ applies the EQ predicate on the "skipped" field.
func SkippedEQ(v int) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldEQ(FieldSkipped, v))
}

// SkippedNEQ applies the NEQ predicate on the "skipped" field.
func SkippedNEQ(v int) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldNEQ(FieldSkipped, v))
}

// SkippedIn applies the In predicate on the "skipped" field.
func SkippedIn(vs ...int) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldIn(FieldSkipped, vs...))
}

// SkippedNotIn applies the NotIn predicate on the "skipped" field.
func SkippedNotIn(vs ...int) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldNotIn(FieldSkipped, vs...))
}

// SkippedGT applies the GT predicate on the "skipped" field.
func SkippedGT(v int) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldGT(FieldSkipped, v))
}

// SkippedGTE applies the GTE predicate on the "skipped" field.
func SkippedGTE(v int) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldGTE(FieldSkipped, v))
}

// SkippedLT applies the LT predicate on the "skipped" field.
func SkippedLT(v int) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldLT(FieldSkipped, v))
}

// SkippedLTE applies the LTE predicate on the "skipped" field.
func SkippedLTE(v int) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldLTE(FieldSkipped, v))
}

// FailedEQ applies the EQ predicate on the "failed" field.
func FailedEQ(v int) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldEQ(FieldFailed, v))
}

// FailedNEQ applies the NEQ predicate on the "failed" field.
func FailedNEQ(v int) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldNEQ(FieldFailed, v))
}

// FailedIn applies the In predicate on the "failed" field.
func FailedIn(vs ...int) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldIn(FieldFailed, vs...))
}

// FailedNotIn applies the NotIn predicate on the "failed" field.
func FailedNotIn(vs ...int) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldNotIn(FieldFailed, vs...))
}

// FailedGT applies the GT predicate on the "failed" field.
func FailedGT(v int) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldGT(FieldFailed, v))
}

// FailedGTE applies the GTE predicate on the "failed" field.
func FailedGTE(v int) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldGTE(FieldFailed, v))
}

// FailedLT applies the LT predicate on the "failed" field.
func FailedLT(v int) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldLT(FieldFailed, v))
}

// FailedLTE applies the LTE predicate on the "failed" field.
func FailedLTE(v int) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldLTE(FieldFailed, v))
}

// DetailIsNil applies the IsNil predicate on the "detail" field.
func DetailIsNil() predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldIsNull(FieldDetail))
}

// DetailNotNil applies the NotNil predicate on the "detail" field.
func DetailNotNil() predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldNotNull(FieldDetail))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldLTE(FieldStartedAt, v))
}

// StartedAtIsNil applies the IsNil predicate on the "started_at" field.
func StartedAtIsNil() predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldIsNull(FieldStartedAt))
}

// StartedAtNotNil applies the NotNil predicate on the "started_at" field.
func StartedAtNotNil() predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldNotNull(FieldStartedAt))
}

// FinishedAtEQ applies the EQ predicate on the "finished_at" field.
func FinishedAtEQ(v time.Time) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldEQ(FieldFinishedAt, v))
}

// FinishedAtNEQ applies the NEQ predicate on the "finished_at" field.
func FinishedAtNEQ(v time.Time) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldNEQ(FieldFinishedAt, v))
}

// FinishedAtIn applies the In predicate on the "finished_at" field.
func FinishedAtIn(vs ...time.Time) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldIn(FieldFinishedAt, vs...))
}

// FinishedAtNotIn applies the NotIn predicate on the "finished_at" field.
func FinishedAtNotIn(vs ...time.Time) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldNotIn(FieldFinishedAt, vs...))
}

// FinishedAtGT applies the GT predicate on the "finished_at" field.
func FinishedAtGT(v time.Time) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldGT(FieldFinishedAt, v))
}

// FinishedAtGTE applies the GTE predicate on the "finished_at" field.
func FinishedAtGTE(v time.Time) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldGTE(FieldFinishedAt, v))
}

// FinishedAtLT applies the LT predicate on the "finished_at" field.
func FinishedAtLT(v time.Time) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldLT(FieldFinishedAt, v))
}

// FinishedAtLTE applies the LTE predicate on the "finished_at" field.
func FinishedAtLTE(v time.Time) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldLTE(FieldFinishedAt, v))
}

// FinishedAtIsNil applies the IsNil predicate on the "finished_at" field.
func FinishedAtIsNil() predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldIsNull(FieldFinishedAt))
}

// FinishedAtNotNil applies the NotNil predicate on the "finished_at" field.
func FinishedAtNotNil() predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.FieldNotNull(FieldFinishedAt))
}

// HasProvider applies the HasEdge predicate on the "provider" edge.
func HasProvider() predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProviderTable, ProviderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProviderWith applies the HasEdge predicate on the "provider" edge with a given conditions (other predicates).
func HasProviderWith(preds ...predicate.Sub2APIProvider) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(func(s *sql.Selector) {
		step := newProviderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSchedule applies the HasEdge predicate on the "schedule" edge.
func HasSchedule() predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ScheduleTable, ScheduleColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasScheduleWith applies the HasEdge predicate on the "schedule" edge with a given conditions (other predicates).
func HasScheduleWith(preds ...predicate.Sub2APIOptimizeSchedule) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(func(s *sql.Selector) {
		step := newScheduleStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Sub2APIOptimizeLog) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Sub2APIOptimizeLog) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Sub2APIOptimizeLog) predicate.Sub2APIOptimizeLog {
	return predicate.Sub2APIOptimizeLog(sql.NotPredicates(p))
}
