// Code generated by ent, DO NOT EDIT.

package sub2apiproviderprobetarget

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldEQ(FieldUpdatedAt, v))
}

// ProviderID applies equality check predicate on the "provider_id" field. It's identical to ProviderIDEQ.
func ProviderID(v int64) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldEQ(FieldProviderID, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldEQ(FieldAccountID, v))
}

// ProviderAPIKeyID applies equality check predicate on the "provider_api_key_id" field. It's identical to ProviderAPIKeyIDEQ.
func ProviderAPIKeyID(v int64) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldEQ(FieldProviderAPIKeyID, v))
}

// RemoteGroupID applies equality check predicate on the "remote_group_id" field. It's identical to RemoteGroupIDEQ.
func RemoteGroupID(v int64) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldEQ(FieldRemoteGroupID, v))
}

// RemoteGroupName applies equality check predicate on the "remote_group_name" field. It's identical to RemoteGroupNameEQ.
func RemoteGroupName(v string) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldEQ(FieldRemoteGroupName, v))
}

// Platform applies equality check predicate on the "platform" field. It's identical to PlatformEQ.
func Platform(v string) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldEQ(FieldPlatform, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldEQ(FieldEnabled, v))
}

// IntervalSeconds applies equality check predicate on the "interval_seconds" field. It's identical to IntervalSecondsEQ.
func IntervalSeconds(v int) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldEQ(FieldIntervalSeconds, v))
}

// TestModel applies equality check predicate on the "test_model" field. It's identical to TestModelEQ.
func TestModel(v string) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldEQ(FieldTestModel, v))
}

// AllowMediaProbe applies equality check predicate on the "allow_media_probe" field. It's identical to AllowMediaProbeEQ.
func AllowMediaProbe(v bool) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldEQ(FieldAllowMediaProbe, v))
}

// TimeoutSeconds applies equality check predicate on the "timeout_seconds" field. It's identical to TimeoutSecondsEQ.
func TimeoutSeconds(v int) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldEQ(FieldTimeoutSeconds, v))
}

// DegradedLatencyMs applies equality check predicate on the "degraded_latency_ms" field. It's identical to DegradedLatencyMsEQ.
func DegradedLatencyMs(v int) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldEQ(FieldDegradedLatencyMs, v))
}

// FailureThreshold applies equality check predicate on the "failure_threshold" field. It's identical to FailureThresholdEQ.
func FailureThreshold(v int) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldEQ(FieldFailureThreshold, v))
}

// RecoveryThreshold applies equality check predicate on the "recovery_threshold" field. It's identical to RecoveryThresholdEQ.
func RecoveryThreshold(v int) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldEQ(FieldRecoveryThreshold, v))
}

// LastRunAt applies equality check predicate on the "last_run_at" field. It's identical to LastRunAtEQ.
func LastRunAt(v time.Time) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldEQ(FieldLastRunAt, v))
}

// RouteChangedAt applies equality check predicate on the "route_changed_at" field. It's identical to RouteChangedAtEQ.
func RouteChangedAt(v time.Time) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldEQ(FieldRouteChangedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldLTE(FieldUpdatedAt, v))
}

// ProviderIDEQ applies the EQ predicate on the "provider_id" field.
func ProviderIDEQ(v int64) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldEQ(FieldProviderID, v))
}

// ProviderIDNEQ applies the NEQ predicate on the "provider_id" field.
func ProviderIDNEQ(v int64) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldNEQ(FieldProviderID, v))
}

// ProviderIDIn applies the In predicate on the "provider_id" field.
func ProviderIDIn(vs ...int64) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldIn(FieldProviderID, vs...))
}

// ProviderIDNotIn applies the NotIn predicate on the "provider_id" field.
func ProviderIDNotIn(vs ...int64) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldNotIn(FieldProviderID, vs...))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldNotIn(FieldAccountID, vs...))
}

// ProviderAPIKeyIDEQ applies the EQ predicate on the "provider_api_key_id" field.
func ProviderAPIKeyIDEQ(v int64) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldEQ(FieldProviderAPIKeyID, v))
}

// ProviderAPIKeyIDNEQ applies the NEQ predicate on the "provider_api_key_id" field.
func ProviderAPIKeyIDNEQ(v int64) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldNEQ(FieldProviderAPIKeyID, v))
}

// ProviderAPIKeyIDIn applies the In predicate on the "provider_api_key_id" field.
func ProviderAPIKeyIDIn(vs ...int64) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldIn(FieldProviderAPIKeyID, vs...))
}

// ProviderAPIKeyIDNotIn applies the NotIn predicate on the "provider_api_key_id" field.
func ProviderAPIKeyIDNotIn(vs ...int64) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldNotIn(FieldProviderAPIKeyID, vs...))
}

// ProviderAPIKeyIDGT applies the GT predicate on the "provider_api_key_id" field.
func ProviderAPIKeyIDGT(v int64) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldGT(FieldProviderAPIKeyID, v))
}

// ProviderAPIKeyIDGTE applies the GTE predicate on the "provider_api_key_id" field.
func ProviderAPIKeyIDGTE(v int64) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldGTE(FieldProviderAPIKeyID, v))
}

// ProviderAPIKeyIDLT applies the LT predicate on the "provider_api_key_id" field.
func ProviderAPIKeyIDLT(v int64) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldLT(FieldProviderAPIKeyID, v))
}

// ProviderAPIKeyIDLTE applies the LTE predicate on the "provider_api_key_id" field.
func ProviderAPIKeyIDLTE(v int64) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldLTE(FieldProviderAPIKeyID, v))
}

// ProviderAPIKeyIDIsNil applies the IsNil predicate on the "provider_api_key_id" field.
func ProviderAPIKeyIDIsNil() predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldIsNull(FieldProviderAPIKeyID))
}

// ProviderAPIKeyIDNotNil applies the NotNil predicate on the "provider_api_key_id" field.
func ProviderAPIKeyIDNotNil() predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldNotNull(FieldProviderAPIKeyID))
}

// RemoteGroupIDEQ applies the EQ predicate on the "remote_group_id" field.
func RemoteGroupIDEQ(v int64) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldEQ(FieldRemoteGroupID, v))
}

// RemoteGroupIDNEQ applies the NEQ predicate on the "remote_group_id" field.
func RemoteGroupIDNEQ(v int64) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldNEQ(FieldRemoteGroupID, v))
}

// RemoteGroupIDIn applies the In predicate on the "remote_group_id" field.
func RemoteGroupIDIn(vs ...int64) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldIn(FieldRemoteGroupID, vs...))
}

// RemoteGroupIDNotIn applies the NotIn predicate on the "remote_group_id" field.
func RemoteGroupIDNotIn(vs ...int64) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldNotIn(FieldRemoteGroupID, vs...))
}

// RemoteGroupIDGT applies the GT predicate on the "remote_group_id" field.
func RemoteGroupIDGT(v int64) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldGT(FieldRemoteGroupID, v))
}

// RemoteGroupIDGTE applies the GTE predicate on the "remote_group_id" field.
func RemoteGroupIDGTE(v int64) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldGTE(FieldRemoteGroupID, v))
}

// RemoteGroupIDLT applies the LT predicate on the "remote_group_id" field.
func RemoteGroupIDLT(v int64) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldLT(FieldRemoteGroupID, v))
}

// RemoteGroupIDLTE applies the LTE predicate on the "remote_group_id" field.
func RemoteGroupIDLTE(v int64) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldLTE(FieldRemoteGroupID, v))
}

// RemoteGroupIDIsNil applies the IsNil predicate on the "remote_group_id" field.
func RemoteGroupIDIsNil() predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldIsNull(FieldRemoteGroupID))
}

// RemoteGroupIDNotNil applies the NotNil predicate on the "remote_group_id" field.
func RemoteGroupIDNotNil() predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldNotNull(FieldRemoteGroupID))
}

// RemoteGroupNameEQ applies the EQ predicate on the "remote_group_name" field.
func RemoteGroupNameEQ(v string) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldEQ(FieldRemoteGroupName, v))
}

// RemoteGroupNameNEQ applies the NEQ predicate on the "remote_group_name" field.
func RemoteGroupNameNEQ(v string) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldNEQ(FieldRemoteGroupName, v))
}

// RemoteGroupNameIn applies the In predicate on the "remote_group_name" field.
func RemoteGroupNameIn(vs ...string) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldIn(FieldRemoteGroupName, vs...))
}

// RemoteGroupNameNotIn applies the NotIn predicate on the "remote_group_name" field.
func RemoteGroupNameNotIn(vs ...string) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldNotIn(FieldRemoteGroupName, vs...))
}

// RemoteGroupNameGT applies the GT predicate on the "remote_group_name" field.
func RemoteGroupNameGT(v string) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldGT(FieldRemoteGroupName, v))
}

// RemoteGroupNameGTE applies the GTE predicate on the "remote_group_name" field.
func RemoteGroupNameGTE(v string) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldGTE(FieldRemoteGroupName, v))
}

// RemoteGroupNameLT applies the LT predicate on the "remote_group_name" field.
func RemoteGroupNameLT(v string) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldLT(FieldRemoteGroupName, v))
}

// RemoteGroupNameLTE applies the LTE predicate on the "remote_group_name" field.
func RemoteGroupNameLTE(v string) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldLTE(FieldRemoteGroupName, v))
}

// RemoteGroupNameContains applies the Contains predicate on the "remote_group_name" field.
func RemoteGroupNameContains(v string) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldContains(FieldRemoteGroupName, v))
}

// RemoteGroupNameHasPrefix applies the HasPrefix predicate on the "remote_group_name" field.
func RemoteGroupNameHasPrefix(v string) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldHasPrefix(FieldRemoteGroupName, v))
}

// RemoteGroupNameHasSuffix applies the HasSuffix predicate on the "remote_group_name" field.
func RemoteGroupNameHasSuffix(v string) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldHasSuffix(FieldRemoteGroupName, v))
}

// RemoteGroupNameIsNil applies the IsNil predicate on the "remote_group_name" field.
func RemoteGroupNameIsNil() predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldIsNull(FieldRemoteGroupName))
}

// RemoteGroupNameNotNil applies the NotNil predicate on the "remote_group_name" field.
func RemoteGroupNameNotNil() predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldNotNull(FieldRemoteGroupName))
}

// RemoteGroupNameEqualFold applies the EqualFold predicate on the "remote_group_name" field.
func RemoteGroupNameEqualFold(v string) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldEqualFold(FieldRemoteGroupName, v))
}

// RemoteGroupNameContainsFold applies the ContainsFold predicate on the "remote_group_name" field.
func RemoteGroupNameContainsFold(v string) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldContainsFold(FieldRemoteGroupName, v))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v string) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v string) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...string) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...string) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldNotIn(FieldPlatform, vs...))
}

// PlatformGT applies the GT predicate on the "platform" field.
func PlatformGT(v string) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldGT(FieldPlatform, v))
}

// PlatformGTE applies the GTE predicate on the "platform" field.
func PlatformGTE(v string) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldGTE(FieldPlatform, v))
}

// PlatformLT applies the LT predicate on the "platform" field.
func PlatformLT(v string) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldLT(FieldPlatform, v))
}

// PlatformLTE applies the LTE predicate on the "platform" field.
func PlatformLTE(v string) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldLTE(FieldPlatform, v))
}

// PlatformContains applies the Contains predicate on the "platform" field.
func PlatformContains(v string) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldContains(FieldPlatform, v))
}

// PlatformHasPrefix applies the HasPrefix predicate on the "platform" field.
func PlatformHasPrefix(v string) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldHasPrefix(FieldPlatform, v))
}

// PlatformHasSuffix applies the HasSuffix predicate on the "platform" field.
func PlatformHasSuffix(v string) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldHasSuffix(FieldPlatform, v))
}

// PlatformEqualFold applies the EqualFold predicate on the "platform" field.
func PlatformEqualFold(v string) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldEqualFold(FieldPlatform, v))
}

// PlatformContainsFold applies the ContainsFold predicate on the "platform" field.
func PlatformContainsFold(v string) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldContainsFold(FieldPlatform, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldNEQ(FieldEnabled, v))
}

// IntervalSecondsEQ applies the EQ predicate on the "interval_seconds" field.
func IntervalSecondsEQ(v int) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldEQ(FieldIntervalSeconds, v))
}

// IntervalSecondsNEQ applies the NEQ predicate on the "interval_seconds" field.
func IntervalSecondsNEQ(v int) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldNEQ(FieldIntervalSeconds, v))
}

// IntervalSecondsIn applies the In predicate on the "interval_seconds" field.
func IntervalSecondsIn(vs ...int) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldIn(FieldIntervalSeconds, vs...))
}

// IntervalSecondsNotIn applies the NotIn predicate on the "interval_seconds" field.
func IntervalSecondsNotIn(vs ...int) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldNotIn(FieldIntervalSeconds, vs...))
}

// IntervalSecondsGT applies the GT predicate on the "interval_seconds" field.
func IntervalSecondsGT(v int) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldGT(FieldIntervalSeconds, v))
}

// IntervalSecondsGTE applies the GTE predicate on the "interval_seconds" field.
func IntervalSecondsGTE(v int) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldGTE(FieldIntervalSeconds, v))
}

// IntervalSecondsLT applies the LT predicate on the "interval_seconds" field.
func IntervalSecondsLT(v int) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldLT(FieldIntervalSeconds, v))
}

// IntervalSecondsLTE applies the LTE predicate on the "interval_seconds" field.
func IntervalSecondsLTE(v int) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldLTE(FieldIntervalSeconds, v))
}

// TestModelEQ applies the EQ predicate on the "test_model" field.
func TestModelEQ(v string) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldEQ(FieldTestModel, v))
}

// TestModelNEQ applies the NEQ predicate on the "test_model" field.
func TestModelNEQ(v string) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldNEQ(FieldTestModel, v))
}

// TestModelIn applies the In predicate on the "test_model" field.
func TestModelIn(vs ...string) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldIn(FieldTestModel, vs...))
}

// TestModelNotIn applies the NotIn predicate on the "test_model" field.
func TestModelNotIn(vs ...string) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldNotIn(FieldTestModel, vs...))
}

// TestModelGT applies the GT predicate on the "test_model" field.
func TestModelGT(v string) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldGT(FieldTestModel, v))
}

// TestModelGTE applies the GTE predicate on the "test_model" field.
func TestModelGTE(v string) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldGTE(FieldTestModel, v))
}

// TestModelLT applies the LT predicate on the "test_model" field.
func TestModelLT(v string) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldLT(FieldTestModel, v))
}

// TestModelLTE applies the LTE predicate on the "test_model" field.
func TestModelLTE(v string) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldLTE(FieldTestModel, v))
}

// TestModelContains applies the Contains predicate on the "test_model" field.
func TestModelContains(v string) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldContains(FieldTestModel, v))
}

// TestModelHasPrefix applies the HasPrefix predicate on the "test_model" field.
func TestModelHasPrefix(v string) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldHasPrefix(FieldTestModel, v))
}

// TestModelHasSuffix applies the HasSuffix predicate on the "test_model" field.
func TestModelHasSuffix(v string) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldHasSuffix(FieldTestModel, v))
}

// TestModelIsNil applies the IsNil predicate on the "test_model" field.
func TestModelIsNil() predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldIsNull(FieldTestModel))
}

// TestModelNotNil applies the NotNil predicate on the "test_model" field.
func TestModelNotNil() predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldNotNull(FieldTestModel))
}

// TestModelEqualFold applies the EqualFold predicate on the "test_model" field.
func TestModelEqualFold(v string) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldEqualFold(FieldTestModel, v))
}

// TestModelContainsFold applies the ContainsFold predicate on the "test_model" field.
func TestModelContainsFold(v string) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldContainsFold(FieldTestModel, v))
}

// AllowMediaProbeEQ applies the EQ predicate on the "allow_media_probe" field.
func AllowMediaProbeEQ(v bool) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldEQ(FieldAllowMediaProbe, v))
}

// AllowMediaProbeNEQ applies the NEQ predicate on the "allow_media_probe" field.
func AllowMediaProbeNEQ(v bool) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldNEQ(FieldAllowMediaProbe, v))
}

// TimeoutSecondsEQ applies the EQ predicate on the "timeout_seconds" field.
func TimeoutSecondsEQ(v int) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldEQ(FieldTimeoutSeconds, v))
}

// TimeoutSecondsNEQ applies the NEQ predicate on the "timeout_seconds" field.
func TimeoutSecondsNEQ(v int) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldNEQ(FieldTimeoutSeconds, v))
}

// TimeoutSecondsIn applies the In predicate on the "timeout_seconds" field.
func TimeoutSecondsIn(vs ...int) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldIn(FieldTimeoutSeconds, vs...))
}

// TimeoutSecondsNotIn applies the NotIn predicate on the "timeout_seconds" field.
func TimeoutSecondsNotIn(vs ...int) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldNotIn(FieldTimeoutSeconds, vs...))
}

// TimeoutSecondsGT applies the GT predicate on the "timeout_seconds" field.
func TimeoutSecondsGT(v int) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldGT(FieldTimeoutSeconds, v))
}

// TimeoutSecondsGTE applies the GTE predicate on the "timeout_seconds" field.
func TimeoutSecondsGTE(v int) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldGTE(FieldTimeoutSeconds, v))
}

// TimeoutSecondsLT applies the LT predicate on the "timeout_seconds" field.
func TimeoutSecondsLT(v int) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldLT(FieldTimeoutSeconds, v))
}

// TimeoutSecondsLTE applies the LTE predicate on the "timeout_seconds" field.
func TimeoutSecondsLTE(v int) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldLTE(FieldTimeoutSeconds, v))
}

// DegradedLatencyMsEQ applies the EQ predicate on the "degraded_latency_ms" field.
func DegradedLatencyMsEQ(v int) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldEQ(FieldDegradedLatencyMs, v))
}

// DegradedLatencyMsNEQ applies the NEQ predicate on the "degraded_latency_ms" field.
func DegradedLatencyMsNEQ(v int) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldNEQ(FieldDegradedLatencyMs, v))
}

// DegradedLatencyMsIn applies the In predicate on the "degraded_latency_ms" field.
func DegradedLatencyMsIn(vs ...int) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldIn(FieldDegradedLatencyMs, vs...))
}

// DegradedLatencyMsNotIn applies the NotIn predicate on the "degraded_latency_ms" field.
func DegradedLatencyMsNotIn(vs ...int) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldNotIn(FieldDegradedLatencyMs, vs...))
}

// DegradedLatencyMsGT applies the GT predicate on the "degraded_latency_ms" field.
func DegradedLatencyMsGT(v int) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldGT(FieldDegradedLatencyMs, v))
}

// DegradedLatencyMsGTE applies the GTE predicate on the "degraded_latency_ms" field.
func DegradedLatencyMsGTE(v int) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldGTE(FieldDegradedLatencyMs, v))
}

// DegradedLatencyMsLT applies the LT predicate on the "degraded_latency_ms" field.
func DegradedLatencyMsLT(v int) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldLT(FieldDegradedLatencyMs, v))
}

// DegradedLatencyMsLTE applies the LTE predicate on the "degraded_latency_ms" field.
func DegradedLatencyMsLTE(v int) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldLTE(FieldDegradedLatencyMs, v))
}

// FailureThresholdEQ applies the EQ predicate on the "failure_threshold" field.
func FailureThresholdEQ(v int) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldEQ(FieldFailureThreshold, v))
}

// FailureThresholdNEQ applies the NEQ predicate on the "failure_threshold" field.
func FailureThresholdNEQ(v int) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldNEQ(FieldFailureThreshold, v))
}

// FailureThresholdIn applies the In predicate on the "failure_threshold" field.
func FailureThresholdIn(vs ...int) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldIn(FieldFailureThreshold, vs...))
}

// FailureThresholdNotIn applies the NotIn predicate on the "failure_threshold" field.
func FailureThresholdNotIn(vs ...int) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldNotIn(FieldFailureThreshold, vs...))
}

// FailureThresholdGT applies the GT predicate on the "failure_threshold" field.
func FailureThresholdGT(v int) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldGT(FieldFailureThreshold, v))
}

// FailureThresholdGTE applies the GTE predicate on the "failure_threshold" field.
func FailureThresholdGTE(v int) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldGTE(FieldFailureThreshold, v))
}

// FailureThresholdLT applies the LT predicate on the "failure_threshold" field.
func FailureThresholdLT(v int) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldLT(FieldFailureThreshold, v))
}

// FailureThresholdLTE applies the LTE predicate on the "failure_threshold" field.
func FailureThresholdLTE(v int) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldLTE(FieldFailureThreshold, v))
}

// RecoveryThresholdEQ applies the EQ predicate on the "recovery_threshold" field.
func RecoveryThresholdEQ(v int) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldEQ(FieldRecoveryThreshold, v))
}

// RecoveryThresholdNEQ applies the NEQ predicate on the "recovery_threshold" field.
func RecoveryThresholdNEQ(v int) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldNEQ(FieldRecoveryThreshold, v))
}

// RecoveryThresholdIn applies the In predicate on the "recovery_threshold" field.
func RecoveryThresholdIn(vs ...int) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldIn(FieldRecoveryThreshold, vs...))
}

// RecoveryThresholdNotIn applies the NotIn predicate on the "recovery_threshold" field.
func RecoveryThresholdNotIn(vs ...int) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldNotIn(FieldRecoveryThreshold, vs...))
}

// RecoveryThresholdGT applies the GT predicate on the "recovery_threshold" field.
func RecoveryThresholdGT(v int) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldGT(FieldRecoveryThreshold, v))
}

// RecoveryThresholdGTE applies the GTE predicate on the "recovery_threshold" field.
func RecoveryThresholdGTE(v int) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldGTE(FieldRecoveryThreshold, v))
}

// RecoveryThresholdLT applies the LT predicate on the "recovery_threshold" field.
func RecoveryThresholdLT(v int) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldLT(FieldRecoveryThreshold, v))
}

// RecoveryThresholdLTE applies the LTE predicate on the "recovery_threshold" field.
func RecoveryThresholdLTE(v int) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldLTE(FieldRecoveryThreshold, v))
}

// LastRunAtEQ applies the EQ predicate on the "last_run_at" field.
func LastRunAtEQ(v time.Time) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldEQ(FieldLastRunAt, v))
}

// LastRunAtNEQ applies the NEQ predicate on the "last_run_at" field.
func LastRunAtNEQ(v time.Time) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldNEQ(FieldLastRunAt, v))
}

// LastRunAtIn applies the In predicate on the "last_run_at" field.
func LastRunAtIn(vs ...time.Time) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldIn(FieldLastRunAt, vs...))
}

// LastRunAtNotIn applies the NotIn predicate on the "last_run_at" field.
func LastRunAtNotIn(vs ...time.Time) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldNotIn(FieldLastRunAt, vs...))
}

// LastRunAtGT applies the GT predicate on the "last_run_at" field.
func LastRunAtGT(v time.Time) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldGT(FieldLastRunAt, v))
}

// LastRunAtGTE applies the GTE predicate on the "last_run_at" field.
func LastRunAtGTE(v time.Time) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldGTE(FieldLastRunAt, v))
}

// LastRunAtLT applies the LT predicate on the "last_run_at" field.
func LastRunAtLT(v time.Time) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldLT(FieldLastRunAt, v))
}

// LastRunAtLTE applies the LTE predicate on the "last_run_at" field.
func LastRunAtLTE(v time.Time) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldLTE(FieldLastRunAt, v))
}

// LastRunAtIsNil applies the IsNil predicate on the "last_run_at" field.
func LastRunAtIsNil() predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldIsNull(FieldLastRunAt))
}

// LastRunAtNotNil applies the NotNil predicate on the "last_run_at" field.
func LastRunAtNotNil() predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldNotNull(FieldLastRunAt))
}

// RouteChangedAtEQ applies the EQ predicate on the "route_changed_at" field.
func RouteChangedAtEQ(v time.Time) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldEQ(FieldRouteChangedAt, v))
}

// RouteChangedAtNEQ applies the NEQ predicate on the "route_changed_at" field.
func RouteChangedAtNEQ(v time.Time) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldNEQ(FieldRouteChangedAt, v))
}

// RouteChangedAtIn applies the In predicate on the "route_changed_at" field.
func RouteChangedAtIn(vs ...time.Time) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldIn(FieldRouteChangedAt, vs...))
}

// RouteChangedAtNotIn applies the NotIn predicate on the "route_changed_at" field.
func RouteChangedAtNotIn(vs ...time.Time) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldNotIn(FieldRouteChangedAt, vs...))
}

// RouteChangedAtGT applies the GT predicate on the "route_changed_at" field.
func RouteChangedAtGT(v time.Time) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldGT(FieldRouteChangedAt, v))
}

// RouteChangedAtGTE applies the GTE predicate on the "route_changed_at" field.
func RouteChangedAtGTE(v time.Time) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldGTE(FieldRouteChangedAt, v))
}

// RouteChangedAtLT applies the LT predicate on the "route_changed_at" field.
func RouteChangedAtLT(v time.Time) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldLT(FieldRouteChangedAt, v))
}

// RouteChangedAtLTE applies the LTE predicate on the "route_changed_at" field.
func RouteChangedAtLTE(v time.Time) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldLTE(FieldRouteChangedAt, v))
}

// RouteChangedAtIsNil applies the IsNil predicate on the "route_changed_at" field.
func RouteChangedAtIsNil() predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldIsNull(FieldRouteChangedAt))
}

// RouteChangedAtNotNil applies the NotNil predicate on the "route_changed_at" field.
func RouteChangedAtNotNil() predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.FieldNotNull(FieldRouteChangedAt))
}

// HasProvider applies the HasEdge predicate on the "provider" edge.
func HasProvider() predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProviderTable, ProviderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProviderWith applies the HasEdge predicate on the "provider" edge with a given conditions (other predicates).
func HasProviderWith(preds ...predicate.Sub2APIProvider) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(func(s *sql.Selector) {
		step := newProviderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAccount applies the HasEdge predicate on the "account" edge.
func HasAccount() predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AccountTable, AccountColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountWith applies the HasEdge predicate on the "account" edge with a given conditions (other predicates).
func HasAccountWith(preds ...predicate.Account) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(func(s *sql.Selector) {
		step := newAccountStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRuns applies the HasEdge predicate on the "runs" edge.
func HasRuns() predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RunsTable, RunsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRunsWith applies the HasEdge predicate on the "runs" edge with a given conditions (other predicates).
func HasRunsWith(preds ...predicate.Sub2APIProviderProbeTargetRun) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(func(s *sql.Selector) {
		step := newRunsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Sub2APIProviderProbeTarget) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Sub2APIProviderProbeTarget) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Sub2APIProviderProbeTarget) predicate.Sub2APIProviderProbeTarget {
	return predicate.Sub2APIProviderProbeTarget(sql.NotPredicates(p))
}
