// Code generated by ent, DO NOT EDIT.

package sub2apioptimizeschedule

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldEQ(FieldUpdatedAt, v))
}

// ProviderID applies equality check predicate on the "provider_id" field. It's identical to ProviderIDEQ.
func ProviderID(v int64) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldEQ(FieldProviderID, v))
}

// CronExpr applies equality check predicate on the "cron_expr" field. It's identical to CronExprEQ.
func CronExpr(v string) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldEQ(FieldCronExpr, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldEQ(FieldEnabled, v))
}

// LastRunAt applies equality check predicate on the "last_run_at" field. It's identical to LastRunAtEQ.
func LastRunAt(v time.Time) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldEQ(FieldLastRunAt, v))
}

// NextRunAt applies equality check predicate on the "next_run_at" field. It's identical to NextRunAtEQ.
func NextRunAt(v time.Time) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldEQ(FieldNextRunAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldLTE(FieldUpdatedAt, v))
}

// ProviderIDEQ applies the EQ predicate on the "provider_id" field.
func ProviderIDEQ(v int64) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldEQ(FieldProviderID, v))
}

// ProviderIDNEQ applies the NEQ predicate on the "provider_id" field.
func ProviderIDNEQ(v int64) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldNEQ(FieldProviderID, v))
}

// ProviderIDIn applies the In predicate on the "provider_id" field.
func ProviderIDIn(vs ...int64) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldIn(FieldProviderID, vs...))
}

// ProviderIDNotIn applies the NotIn predicate on the "provider_id" field.
func ProviderIDNotIn(vs ...int64) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldNotIn(FieldProviderID, vs...))
}

// CronExprEQ applies the EQ predicate on the "cron_expr" field.
func CronExprEQ(v string) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldEQ(FieldCronExpr, v))
}

// CronExprNEQ applies the NEQ predicate on the "cron_expr" field.
func CronExprNEQ(v string) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldNEQ(FieldCronExpr, v))
}

// CronExprIn applies the In predicate on the "cron_expr" field.
func CronExprIn(vs ...string) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldIn(FieldCronExpr, vs...))
}

// CronExprNotIn applies the NotIn predicate on the "cron_expr" field.
func CronExprNotIn(vs ...string) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldNotIn(FieldCronExpr, vs...))
}

// CronExprGT applies the GT predicate on the "cron_expr" field.
func CronExprGT(v string) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldGT(FieldCronExpr, v))
}

// CronExprGTE applies the GTE predicate on the "cron_expr" field.
func CronExprGTE(v string) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldGTE(FieldCronExpr, v))
}

// CronExprLT applies the LT predicate on the "cron_expr" field.
func CronExprLT(v string) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldLT(FieldCronExpr, v))
}

// CronExprLTE applies the LTE predicate on the "cron_expr" field.
func CronExprLTE(v string) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldLTE(FieldCronExpr, v))
}

// CronExprContains applies the Contains predicate on the "cron_expr" field.
func CronExprContains(v string) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldContains(FieldCronExpr, v))
}

// CronExprHasPrefix applies the HasPrefix predicate on the "cron_expr" field.
func CronExprHasPrefix(v string) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldHasPrefix(FieldCronExpr, v))
}

// CronExprHasSuffix applies the HasSuffix predicate on the "cron_expr" field.
func CronExprHasSuffix(v string) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldHasSuffix(FieldCronExpr, v))
}

// CronExprEqualFold applies the EqualFold predicate on the "cron_expr" field.
func CronExprEqualFold(v string) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldEqualFold(FieldCronExpr, v))
}

// CronExprContainsFold applies the ContainsFold predicate on the "cron_expr" field.
func CronExprContainsFold(v string) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldContainsFold(FieldCronExpr, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldNEQ(FieldEnabled, v))
}

// LastRunAtEQ applies the EQ predicate on the "last_run_at" field.
func LastRunAtEQ(v time.Time) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldEQ(FieldLastRunAt, v))
}

// LastRunAtNEQ applies the NEQ predicate on the "last_run_at" field.
func LastRunAtNEQ(v time.Time) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldNEQ(FieldLastRunAt, v))
}

// LastRunAtIn applies the In predicate on the "last_run_at" field.
func LastRunAtIn(vs ...time.Time) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldIn(FieldLastRunAt, vs...))
}

// LastRunAtNotIn applies the NotIn predicate on the "last_run_at" field.
func LastRunAtNotIn(vs ...time.Time) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldNotIn(FieldLastRunAt, vs...))
}

// LastRunAtGT applies the GT predicate on the "last_run_at" field.
func LastRunAtGT(v time.Time) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldGT(FieldLastRunAt, v))
}

// LastRunAtGTE applies the GTE predicate on the "last_run_at" field.
func LastRunAtGTE(v time.Time) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldGTE(FieldLastRunAt, v))
}

// LastRunAtLT applies the LT predicate on the "last_run_at" field.
func LastRunAtLT(v time.Time) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldLT(FieldLastRunAt, v))
}

// LastRunAtLTE applies the LTE predicate on the "last_run_at" field.
func LastRunAtLTE(v time.Time) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldLTE(FieldLastRunAt, v))
}

// LastRunAtIsNil applies the IsNil predicate on the "last_run_at" field.
func LastRunAtIsNil() predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldIsNull(FieldLastRunAt))
}

// LastRunAtNotNil applies the NotNil predicate on the "last_run_at" field.
func LastRunAtNotNil() predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldNotNull(FieldLastRunAt))
}

// NextRunAtEQ applies the EQ predicate on the "next_run_at" field.
func NextRunAtEQ(v time.Time) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldEQ(FieldNextRunAt, v))
}

// NextRunAtNEQ applies the NEQ predicate on the "next_run_at" field.
func NextRunAtNEQ(v time.Time) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldNEQ(FieldNextRunAt, v))
}

// NextRunAtIn applies the In predicate on the "next_run_at" field.
func NextRunAtIn(vs ...time.Time) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldIn(FieldNextRunAt, vs...))
}

// NextRunAtNotIn applies the NotIn predicate on the "next_run_at" field.
func NextRunAtNotIn(vs ...time.Time) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldNotIn(FieldNextRunAt, vs...))
}

// NextRunAtGT applies the GT predicate on the "next_run_at" field.
func NextRunAtGT(v time.Time) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldGT(FieldNextRunAt, v))
}

// NextRunAtGTE applies the GTE predicate on the "next_run_at" field.
func NextRunAtGTE(v time.Time) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldGTE(FieldNextRunAt, v))
}

// NextRunAtLT applies the LT predicate on the "next_run_at" field.
func NextRunAtLT(v time.Time) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldLT(FieldNextRunAt, v))
}

// NextRunAtLTE applies the LTE predicate on the "next_run_at" field.
func NextRunAtLTE(v time.Time) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldLTE(FieldNextRunAt, v))
}

// NextRunAtIsNil applies the IsNil predicate on the "next_run_at" field.
func NextRunAtIsNil() predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldIsNull(FieldNextRunAt))
}

// NextRunAtNotNil applies the NotNil predicate on the "next_run_at" field.
func NextRunAtNotNil() predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.FieldNotNull(FieldNextRunAt))
}

// HasProvider applies the HasEdge predicate on the "provider" edge.
func HasProvider() predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, ProviderTable, ProviderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProviderWith applies the HasEdge predicate on the "provider" edge with a given conditions (other predicates).
func HasProviderWith(preds ...predicate.Sub2APIProvider) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(func(s *sql.Selector) {
		step := newProviderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasLogs applies the HasEdge predicate on the "logs" edge.
func HasLogs() predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, LogsTable, LogsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLogsWith applies the HasEdge predicate on the "logs" edge with a given conditions (other predicates).
func HasLogsWith(preds ...predicate.Sub2APIOptimizeLog) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(func(s *sql.Selector) {
		step := newLogsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Sub2APIOptimizeSchedule) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Sub2APIOptimizeSchedule) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Sub2APIOptimizeSchedule) predicate.Sub2APIOptimizeSchedule {
	return predicate.Sub2APIOptimizeSchedule(sql.NotPredicates(p))
}
