// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/sub2apioptimizeschedule"
	"github.com/Wei-Shaw/sub2api/ent/sub2apiprovider"
)

// Sub2APIProviderUpdate is the builder for updating Sub2APIProvider entities.
type Sub2APIProviderUpdate struct {
	config
	hooks    []Hook
	mutation *Sub2APIProviderMutation
}

// Where appends a list predicates to the Sub2APIProviderUpdate builder.
func (_u *Sub2APIProviderUpdate) Where(ps ...predicate.Sub2APIProvider) *Sub2APIProviderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *Sub2APIProviderUpdate) SetUpdatedAt(v time.Time) *Sub2APIProviderUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *Sub2APIProviderUpdate) SetDeletedAt(v time.Time) *Sub2APIProviderUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *Sub2APIProviderUpdate) SetNillableDeletedAt(v *time.Time) *Sub2APIProviderUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *Sub2APIProviderUpdate) ClearDeletedAt() *Sub2APIProviderUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *Sub2APIProviderUpdate) SetName(v string) *Sub2APIProviderUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *Sub2APIProviderUpdate) SetNillableName(v *string) *Sub2APIProviderUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetBaseURL sets the "base_url" field.
func (_u *Sub2APIProviderUpdate) SetBaseURL(v string) *Sub2APIProviderUpdate {
	_u.mutation.SetBaseURL(v)
	return _u
}

// SetNillableBaseURL sets the "base_url" field if the given value is not nil.
func (_u *Sub2APIProviderUpdate) SetNillableBaseURL(v *string) *Sub2APIProviderUpdate {
	if v != nil {
		_u.SetBaseURL(*v)
	}
	return _u
}

// SetProviderType sets the "provider_type" field.
func (_u *Sub2APIProviderUpdate) SetProviderType(v string) *Sub2APIProviderUpdate {
	_u.mutation.SetProviderType(v)
	return _u
}

// SetNillableProviderType sets the "provider_type" field if the given value is not nil.
func (_u *Sub2APIProviderUpdate) SetNillableProviderType(v *string) *Sub2APIProviderUpdate {
	if v != nil {
		_u.SetProviderType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *Sub2APIProviderUpdate) SetStatus(v string) *Sub2APIProviderUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *Sub2APIProviderUpdate) SetNillableStatus(v *string) *Sub2APIProviderUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *Sub2APIProviderUpdate) SetNotes(v string) *Sub2APIProviderUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *Sub2APIProviderUpdate) SetNillableNotes(v *string) *Sub2APIProviderUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *Sub2APIProviderUpdate) ClearNotes() *Sub2APIProviderUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetEmail sets the "email" field.
func (_u *Sub2APIProviderUpdate) SetEmail(v string) *Sub2APIProviderUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *Sub2APIProviderUpdate) SetNillableEmail(v *string) *Sub2APIProviderUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPasswordEncrypted sets the "password_encrypted" field.
func (_u *Sub2APIProviderUpdate) SetPasswordEncrypted(v string) *Sub2APIProviderUpdate {
	_u.mutation.SetPasswordEncrypted(v)
	return _u
}

// SetNillablePasswordEncrypted sets the "password_encrypted" field if the given value is not nil.
func (_u *Sub2APIProviderUpdate) SetNillablePasswordEncrypted(v *string) *Sub2APIProviderUpdate {
	if v != nil {
		_u.SetPasswordEncrypted(*v)
	}
	return _u
}

// SetAPIPathKeys sets the "api_path_keys" field.
func (_u *Sub2APIProviderUpdate) SetAPIPathKeys(v string) *Sub2APIProviderUpdate {
	_u.mutation.SetAPIPathKeys(v)
	return _u
}

// SetNillableAPIPathKeys sets the "api_path_keys" field if the given value is not nil.
func (_u *Sub2APIProviderUpdate) SetNillableAPIPathKeys(v *string) *Sub2APIProviderUpdate {
	if v != nil {
		_u.SetAPIPathKeys(*v)
	}
	return _u
}

// ClearAPIPathKeys clears the value of the "api_path_keys" field.
func (_u *Sub2APIProviderUpdate) ClearAPIPathKeys() *Sub2APIProviderUpdate {
	_u.mutation.ClearAPIPathKeys()
	return _u
}

// SetAPIPathGroups sets the "api_path_groups" field.
func (_u *Sub2APIProviderUpdate) SetAPIPathGroups(v string) *Sub2APIProviderUpdate {
	_u.mutation.SetAPIPathGroups(v)
	return _u
}

// SetNillableAPIPathGroups sets the "api_path_groups" field if the given value is not nil.
func (_u *Sub2APIProviderUpdate) SetNillableAPIPathGroups(v *string) *Sub2APIProviderUpdate {
	if v != nil {
		_u.SetAPIPathGroups(*v)
	}
	return _u
}

// ClearAPIPathGroups clears the value of the "api_path_groups" field.
func (_u *Sub2APIProviderUpdate) ClearAPIPathGroups() *Sub2APIProviderUpdate {
	_u.mutation.ClearAPIPathGroups()
	return _u
}

// SetLastSyncAt sets the "last_sync_at" field.
func (_u *Sub2APIProviderUpdate) SetLastSyncAt(v time.Time) *Sub2APIProviderUpdate {
	_u.mutation.SetLastSyncAt(v)
	return _u
}

// SetNillableLastSyncAt sets the "last_sync_at" field if the given value is not nil.
func (_u *Sub2APIProviderUpdate) SetNillableLastSyncAt(v *time.Time) *Sub2APIProviderUpdate {
	if v != nil {
		_u.SetLastSyncAt(*v)
	}
	return _u
}

// ClearLastSyncAt clears the value of the "last_sync_at" field.
func (_u *Sub2APIProviderUpdate) ClearLastSyncAt() *Sub2APIProviderUpdate {
	_u.mutation.ClearLastSyncAt()
	return _u
}

// SetLastSyncStatus sets the "last_sync_status" field.
func (_u *Sub2APIProviderUpdate) SetLastSyncStatus(v string) *Sub2APIProviderUpdate {
	_u.mutation.SetLastSyncStatus(v)
	return _u
}

// SetNillableLastSyncStatus sets the "last_sync_status" field if the given value is not nil.
func (_u *Sub2APIProviderUpdate) SetNillableLastSyncStatus(v *string) *Sub2APIProviderUpdate {
	if v != nil {
		_u.SetLastSyncStatus(*v)
	}
	return _u
}

// ClearLastSyncStatus clears the value of the "last_sync_status" field.
func (_u *Sub2APIProviderUpdate) ClearLastSyncStatus() *Sub2APIProviderUpdate {
	_u.mutation.ClearLastSyncStatus()
	return _u
}

// SetLastSyncError sets the "last_sync_error" field.
func (_u *Sub2APIProviderUpdate) SetLastSyncError(v string) *Sub2APIProviderUpdate {
	_u.mutation.SetLastSyncError(v)
	return _u
}

// SetNillableLastSyncError sets the "last_sync_error" field if the given value is not nil.
func (_u *Sub2APIProviderUpdate) SetNillableLastSyncError(v *string) *Sub2APIProviderUpdate {
	if v != nil {
		_u.SetLastSyncError(*v)
	}
	return _u
}

// ClearLastSyncError clears the value of the "last_sync_error" field.
func (_u *Sub2APIProviderUpdate) ClearLastSyncError() *Sub2APIProviderUpdate {
	_u.mutation.ClearLastSyncError()
	return _u
}

// AddAccountIDs adds the "accounts" edge to the Account entity by IDs.
func (_u *Sub2APIProviderUpdate) AddAccountIDs(ids ...int64) *Sub2APIProviderUpdate {
	_u.mutation.AddAccountIDs(ids...)
	return _u
}

// AddAccounts adds the "accounts" edges to the Account entity.
func (_u *Sub2APIProviderUpdate) AddAccounts(v ...*Account) *Sub2APIProviderUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAccountIDs(ids...)
}

// SetOptimizeScheduleID sets the "optimize_schedule" edge to the Sub2APIOptimizeSchedule entity by ID.
func (_u *Sub2APIProviderUpdate) SetOptimizeScheduleID(id int64) *Sub2APIProviderUpdate {
	_u.mutation.SetOptimizeScheduleID(id)
	return _u
}

// SetNillableOptimizeScheduleID sets the "optimize_schedule" edge to the Sub2APIOptimizeSchedule entity by ID if the given value is not nil.
func (_u *Sub2APIProviderUpdate) SetNillableOptimizeScheduleID(id *int64) *Sub2APIProviderUpdate {
	if id != nil {
		_u = _u.SetOptimizeScheduleID(*id)
	}
	return _u
}

// SetOptimizeSchedule sets the "optimize_schedule" edge to the Sub2APIOptimizeSchedule entity.
func (_u *Sub2APIProviderUpdate) SetOptimizeSchedule(v *Sub2APIOptimizeSchedule) *Sub2APIProviderUpdate {
	return _u.SetOptimizeScheduleID(v.ID)
}

// Mutation returns the Sub2APIProviderMutation object of the builder.
func (_u *Sub2APIProviderUpdate) Mutation() *Sub2APIProviderMutation {
	return _u.mutation
}

// ClearAccounts clears all "accounts" edges to the Account entity.
func (_u *Sub2APIProviderUpdate) ClearAccounts() *Sub2APIProviderUpdate {
	_u.mutation.ClearAccounts()
	return _u
}

// RemoveAccountIDs removes the "accounts" edge to Account entities by IDs.
func (_u *Sub2APIProviderUpdate) RemoveAccountIDs(ids ...int64) *Sub2APIProviderUpdate {
	_u.mutation.RemoveAccountIDs(ids...)
	return _u
}

// RemoveAccounts removes "accounts" edges to Account entities.
func (_u *Sub2APIProviderUpdate) RemoveAccounts(v ...*Account) *Sub2APIProviderUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAccountIDs(ids...)
}

// ClearOptimizeSchedule clears the "optimize_schedule" edge to the Sub2APIOptimizeSchedule entity.
func (_u *Sub2APIProviderUpdate) ClearOptimizeSchedule() *Sub2APIProviderUpdate {
	_u.mutation.ClearOptimizeSchedule()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *Sub2APIProviderUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *Sub2APIProviderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *Sub2APIProviderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *Sub2APIProviderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *Sub2APIProviderUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if sub2apiprovider.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized sub2apiprovider.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := sub2apiprovider.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *Sub2APIProviderUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := sub2apiprovider.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Sub2APIProvider.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BaseURL(); ok {
		if err := sub2apiprovider.BaseURLValidator(v); err != nil {
			return &ValidationError{Name: "base_url", err: fmt.Errorf(`ent: validator failed for field "Sub2APIProvider.base_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderType(); ok {
		if err := sub2apiprovider.ProviderTypeValidator(v); err != nil {
			return &ValidationError{Name: "provider_type", err: fmt.Errorf(`ent: validator failed for field "Sub2APIProvider.provider_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := sub2apiprovider.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Sub2APIProvider.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := sub2apiprovider.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Sub2APIProvider.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PasswordEncrypted(); ok {
		if err := sub2apiprovider.PasswordEncryptedValidator(v); err != nil {
			return &ValidationError{Name: "password_encrypted", err: fmt.Errorf(`ent: validator failed for field "Sub2APIProvider.password_encrypted": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APIPathKeys(); ok {
		if err := sub2apiprovider.APIPathKeysValidator(v); err != nil {
			return &ValidationError{Name: "api_path_keys", err: fmt.Errorf(`ent: validator failed for field "Sub2APIProvider.api_path_keys": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APIPathGroups(); ok {
		if err := sub2apiprovider.APIPathGroupsValidator(v); err != nil {
			return &ValidationError{Name: "api_path_groups", err: fmt.Errorf(`ent: validator failed for field "Sub2APIProvider.api_path_groups": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastSyncStatus(); ok {
		if err := sub2apiprovider.LastSyncStatusValidator(v); err != nil {
			return &ValidationError{Name: "last_sync_status", err: fmt.Errorf(`ent: validator failed for field "Sub2APIProvider.last_sync_status": %w`, err)}
		}
	}
	return nil
}

func (_u *Sub2APIProviderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sub2apiprovider.Table, sub2apiprovider.Columns, sqlgraph.NewFieldSpec(sub2apiprovider.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sub2apiprovider.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(sub2apiprovider.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(sub2apiprovider.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(sub2apiprovider.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.BaseURL(); ok {
		_spec.SetField(sub2apiprovider.FieldBaseURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderType(); ok {
		_spec.SetField(sub2apiprovider.FieldProviderType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(sub2apiprovider.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(sub2apiprovider.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(sub2apiprovider.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(sub2apiprovider.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordEncrypted(); ok {
		_spec.SetField(sub2apiprovider.FieldPasswordEncrypted, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIPathKeys(); ok {
		_spec.SetField(sub2apiprovider.FieldAPIPathKeys, field.TypeString, value)
	}
	if _u.mutation.APIPathKeysCleared() {
		_spec.ClearField(sub2apiprovider.FieldAPIPathKeys, field.TypeString)
	}
	if value, ok := _u.mutation.APIPathGroups(); ok {
		_spec.SetField(sub2apiprovider.FieldAPIPathGroups, field.TypeString, value)
	}
	if _u.mutation.APIPathGroupsCleared() {
		_spec.ClearField(sub2apiprovider.FieldAPIPathGroups, field.TypeString)
	}
	if value, ok := _u.mutation.LastSyncAt(); ok {
		_spec.SetField(sub2apiprovider.FieldLastSyncAt, field.TypeTime, value)
	}
	if _u.mutation.LastSyncAtCleared() {
		_spec.ClearField(sub2apiprovider.FieldLastSyncAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastSyncStatus(); ok {
		_spec.SetField(sub2apiprovider.FieldLastSyncStatus, field.TypeString, value)
	}
	if _u.mutation.LastSyncStatusCleared() {
		_spec.ClearField(sub2apiprovider.FieldLastSyncStatus, field.TypeString)
	}
	if value, ok := _u.mutation.LastSyncError(); ok {
		_spec.SetField(sub2apiprovider.FieldLastSyncError, field.TypeString, value)
	}
	if _u.mutation.LastSyncErrorCleared() {
		_spec.ClearField(sub2apiprovider.FieldLastSyncError, field.TypeString)
	}
	if _u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sub2apiprovider.AccountsTable,
			Columns: []string{sub2apiprovider.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAccountsIDs(); len(nodes) > 0 && !_u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sub2apiprovider.AccountsTable,
			Columns: []string{sub2apiprovider.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sub2apiprovider.AccountsTable,
			Columns: []string{sub2apiprovider.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OptimizeScheduleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   sub2apiprovider.OptimizeScheduleTable,
			Columns: []string{sub2apiprovider.OptimizeScheduleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sub2apioptimizeschedule.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OptimizeScheduleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   sub2apiprovider.OptimizeScheduleTable,
			Columns: []string{sub2apiprovider.OptimizeScheduleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sub2apioptimizeschedule.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sub2apiprovider.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// Sub2APIProviderUpdateOne is the builder for updating a single Sub2APIProvider entity.
type Sub2APIProviderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *Sub2APIProviderMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *Sub2APIProviderUpdateOne) SetUpdatedAt(v time.Time) *Sub2APIProviderUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *Sub2APIProviderUpdateOne) SetDeletedAt(v time.Time) *Sub2APIProviderUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *Sub2APIProviderUpdateOne) SetNillableDeletedAt(v *time.Time) *Sub2APIProviderUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *Sub2APIProviderUpdateOne) ClearDeletedAt() *Sub2APIProviderUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *Sub2APIProviderUpdateOne) SetName(v string) *Sub2APIProviderUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *Sub2APIProviderUpdateOne) SetNillableName(v *string) *Sub2APIProviderUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetBaseURL sets the "base_url" field.
func (_u *Sub2APIProviderUpdateOne) SetBaseURL(v string) *Sub2APIProviderUpdateOne {
	_u.mutation.SetBaseURL(v)
	return _u
}

// SetNillableBaseURL sets the "base_url" field if the given value is not nil.
func (_u *Sub2APIProviderUpdateOne) SetNillableBaseURL(v *string) *Sub2APIProviderUpdateOne {
	if v != nil {
		_u.SetBaseURL(*v)
	}
	return _u
}

// SetProviderType sets the "provider_type" field.
func (_u *Sub2APIProviderUpdateOne) SetProviderType(v string) *Sub2APIProviderUpdateOne {
	_u.mutation.SetProviderType(v)
	return _u
}

// SetNillableProviderType sets the "provider_type" field if the given value is not nil.
func (_u *Sub2APIProviderUpdateOne) SetNillableProviderType(v *string) *Sub2APIProviderUpdateOne {
	if v != nil {
		_u.SetProviderType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *Sub2APIProviderUpdateOne) SetStatus(v string) *Sub2APIProviderUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *Sub2APIProviderUpdateOne) SetNillableStatus(v *string) *Sub2APIProviderUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *Sub2APIProviderUpdateOne) SetNotes(v string) *Sub2APIProviderUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *Sub2APIProviderUpdateOne) SetNillableNotes(v *string) *Sub2APIProviderUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *Sub2APIProviderUpdateOne) ClearNotes() *Sub2APIProviderUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetEmail sets the "email" field.
func (_u *Sub2APIProviderUpdateOne) SetEmail(v string) *Sub2APIProviderUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *Sub2APIProviderUpdateOne) SetNillableEmail(v *string) *Sub2APIProviderUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPasswordEncrypted sets the "password_encrypted" field.
func (_u *Sub2APIProviderUpdateOne) SetPasswordEncrypted(v string) *Sub2APIProviderUpdateOne {
	_u.mutation.SetPasswordEncrypted(v)
	return _u
}

// SetNillablePasswordEncrypted sets the "password_encrypted" field if the given value is not nil.
func (_u *Sub2APIProviderUpdateOne) SetNillablePasswordEncrypted(v *string) *Sub2APIProviderUpdateOne {
	if v != nil {
		_u.SetPasswordEncrypted(*v)
	}
	return _u
}

// SetAPIPathKeys sets the "api_path_keys" field.
func (_u *Sub2APIProviderUpdateOne) SetAPIPathKeys(v string) *Sub2APIProviderUpdateOne {
	_u.mutation.SetAPIPathKeys(v)
	return _u
}

// SetNillableAPIPathKeys sets the "api_path_keys" field if the given value is not nil.
func (_u *Sub2APIProviderUpdateOne) SetNillableAPIPathKeys(v *string) *Sub2APIProviderUpdateOne {
	if v != nil {
		_u.SetAPIPathKeys(*v)
	}
	return _u
}

// ClearAPIPathKeys clears the value of the "api_path_keys" field.
func (_u *Sub2APIProviderUpdateOne) ClearAPIPathKeys() *Sub2APIProviderUpdateOne {
	_u.mutation.ClearAPIPathKeys()
	return _u
}

// SetAPIPathGroups sets the "api_path_groups" field.
func (_u *Sub2APIProviderUpdateOne) SetAPIPathGroups(v string) *Sub2APIProviderUpdateOne {
	_u.mutation.SetAPIPathGroups(v)
	return _u
}

// SetNillableAPIPathGroups sets the "api_path_groups" field if the given value is not nil.
func (_u *Sub2APIProviderUpdateOne) SetNillableAPIPathGroups(v *string) *Sub2APIProviderUpdateOne {
	if v != nil {
		_u.SetAPIPathGroups(*v)
	}
	return _u
}

// ClearAPIPathGroups clears the value of the "api_path_groups" field.
func (_u *Sub2APIProviderUpdateOne) ClearAPIPathGroups() *Sub2APIProviderUpdateOne {
	_u.mutation.ClearAPIPathGroups()
	return _u
}

// SetLastSyncAt sets the "last_sync_at" field.
func (_u *Sub2APIProviderUpdateOne) SetLastSyncAt(v time.Time) *Sub2APIProviderUpdateOne {
	_u.mutation.SetLastSyncAt(v)
	return _u
}

// SetNillableLastSyncAt sets the "last_sync_at" field if the given value is not nil.
func (_u *Sub2APIProviderUpdateOne) SetNillableLastSyncAt(v *time.Time) *Sub2APIProviderUpdateOne {
	if v != nil {
		_u.SetLastSyncAt(*v)
	}
	return _u
}

// ClearLastSyncAt clears the value of the "last_sync_at" field.
func (_u *Sub2APIProviderUpdateOne) ClearLastSyncAt() *Sub2APIProviderUpdateOne {
	_u.mutation.ClearLastSyncAt()
	return _u
}

// SetLastSyncStatus sets the "last_sync_status" field.
func (_u *Sub2APIProviderUpdateOne) SetLastSyncStatus(v string) *Sub2APIProviderUpdateOne {
	_u.mutation.SetLastSyncStatus(v)
	return _u
}

// SetNillableLastSyncStatus sets the "last_sync_status" field if the given value is not nil.
func (_u *Sub2APIProviderUpdateOne) SetNillableLastSyncStatus(v *string) *Sub2APIProviderUpdateOne {
	if v != nil {
		_u.SetLastSyncStatus(*v)
	}
	return _u
}

// ClearLastSyncStatus clears the value of the "last_sync_status" field.
func (_u *Sub2APIProviderUpdateOne) ClearLastSyncStatus() *Sub2APIProviderUpdateOne {
	_u.mutation.ClearLastSyncStatus()
	return _u
}

// SetLastSyncError sets the "last_sync_error" field.
func (_u *Sub2APIProviderUpdateOne) SetLastSyncError(v string) *Sub2APIProviderUpdateOne {
	_u.mutation.SetLastSyncError(v)
	return _u
}

// SetNillableLastSyncError sets the "last_sync_error" field if the given value is not nil.
func (_u *Sub2APIProviderUpdateOne) SetNillableLastSyncError(v *string) *Sub2APIProviderUpdateOne {
	if v != nil {
		_u.SetLastSyncError(*v)
	}
	return _u
}

// ClearLastSyncError clears the value of the "last_sync_error" field.
func (_u *Sub2APIProviderUpdateOne) ClearLastSyncError() *Sub2APIProviderUpdateOne {
	_u.mutation.ClearLastSyncError()
	return _u
}

// AddAccountIDs adds the "accounts" edge to the Account entity by IDs.
func (_u *Sub2APIProviderUpdateOne) AddAccountIDs(ids ...int64) *Sub2APIProviderUpdateOne {
	_u.mutation.AddAccountIDs(ids...)
	return _u
}

// AddAccounts adds the "accounts" edges to the Account entity.
func (_u *Sub2APIProviderUpdateOne) AddAccounts(v ...*Account) *Sub2APIProviderUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAccountIDs(ids...)
}

// SetOptimizeScheduleID sets the "optimize_schedule" edge to the Sub2APIOptimizeSchedule entity by ID.
func (_u *Sub2APIProviderUpdateOne) SetOptimizeScheduleID(id int64) *Sub2APIProviderUpdateOne {
	_u.mutation.SetOptimizeScheduleID(id)
	return _u
}

// SetNillableOptimizeScheduleID sets the "optimize_schedule" edge to the Sub2APIOptimizeSchedule entity by ID if the given value is not nil.
func (_u *Sub2APIProviderUpdateOne) SetNillableOptimizeScheduleID(id *int64) *Sub2APIProviderUpdateOne {
	if id != nil {
		_u = _u.SetOptimizeScheduleID(*id)
	}
	return _u
}

// SetOptimizeSchedule sets the "optimize_schedule" edge to the Sub2APIOptimizeSchedule entity.
func (_u *Sub2APIProviderUpdateOne) SetOptimizeSchedule(v *Sub2APIOptimizeSchedule) *Sub2APIProviderUpdateOne {
	return _u.SetOptimizeScheduleID(v.ID)
}

// Mutation returns the Sub2APIProviderMutation object of the builder.
func (_u *Sub2APIProviderUpdateOne) Mutation() *Sub2APIProviderMutation {
	return _u.mutation
}

// ClearAccounts clears all "accounts" edges to the Account entity.
func (_u *Sub2APIProviderUpdateOne) ClearAccounts() *Sub2APIProviderUpdateOne {
	_u.mutation.ClearAccounts()
	return _u
}

// RemoveAccountIDs removes the "accounts" edge to Account entities by IDs.
func (_u *Sub2APIProviderUpdateOne) RemoveAccountIDs(ids ...int64) *Sub2APIProviderUpdateOne {
	_u.mutation.RemoveAccountIDs(ids...)
	return _u
}

// RemoveAccounts removes "accounts" edges to Account entities.
func (_u *Sub2APIProviderUpdateOne) RemoveAccounts(v ...*Account) *Sub2APIProviderUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAccountIDs(ids...)
}

// ClearOptimizeSchedule clears the "optimize_schedule" edge to the Sub2APIOptimizeSchedule entity.
func (_u *Sub2APIProviderUpdateOne) ClearOptimizeSchedule() *Sub2APIProviderUpdateOne {
	_u.mutation.ClearOptimizeSchedule()
	return _u
}

// Where appends a list predicates to the Sub2APIProviderUpdate builder.
func (_u *Sub2APIProviderUpdateOne) Where(ps ...predicate.Sub2APIProvider) *Sub2APIProviderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *Sub2APIProviderUpdateOne) Select(field string, fields ...string) *Sub2APIProviderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Sub2APIProvider entity.
func (_u *Sub2APIProviderUpdateOne) Save(ctx context.Context) (*Sub2APIProvider, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *Sub2APIProviderUpdateOne) SaveX(ctx context.Context) *Sub2APIProvider {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *Sub2APIProviderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *Sub2APIProviderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *Sub2APIProviderUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if sub2apiprovider.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized sub2apiprovider.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := sub2apiprovider.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *Sub2APIProviderUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := sub2apiprovider.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Sub2APIProvider.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BaseURL(); ok {
		if err := sub2apiprovider.BaseURLValidator(v); err != nil {
			return &ValidationError{Name: "base_url", err: fmt.Errorf(`ent: validator failed for field "Sub2APIProvider.base_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderType(); ok {
		if err := sub2apiprovider.ProviderTypeValidator(v); err != nil {
			return &ValidationError{Name: "provider_type", err: fmt.Errorf(`ent: validator failed for field "Sub2APIProvider.provider_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := sub2apiprovider.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Sub2APIProvider.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := sub2apiprovider.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Sub2APIProvider.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PasswordEncrypted(); ok {
		if err := sub2apiprovider.PasswordEncryptedValidator(v); err != nil {
			return &ValidationError{Name: "password_encrypted", err: fmt.Errorf(`ent: validator failed for field "Sub2APIProvider.password_encrypted": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APIPathKeys(); ok {
		if err := sub2apiprovider.APIPathKeysValidator(v); err != nil {
			return &ValidationError{Name: "api_path_keys", err: fmt.Errorf(`ent: validator failed for field "Sub2APIProvider.api_path_keys": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APIPathGroups(); ok {
		if err := sub2apiprovider.APIPathGroupsValidator(v); err != nil {
			return &ValidationError{Name: "api_path_groups", err: fmt.Errorf(`ent: validator failed for field "Sub2APIProvider.api_path_groups": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastSyncStatus(); ok {
		if err := sub2apiprovider.LastSyncStatusValidator(v); err != nil {
			return &ValidationError{Name: "last_sync_status", err: fmt.Errorf(`ent: validator failed for field "Sub2APIProvider.last_sync_status": %w`, err)}
		}
	}
	return nil
}

func (_u *Sub2APIProviderUpdateOne) sqlSave(ctx context.Context) (_node *Sub2APIProvider, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sub2apiprovider.Table, sub2apiprovider.Columns, sqlgraph.NewFieldSpec(sub2apiprovider.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Sub2APIProvider.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sub2apiprovider.FieldID)
		for _, f := range fields {
			if !sub2apiprovider.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sub2apiprovider.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sub2apiprovider.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(sub2apiprovider.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(sub2apiprovider.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(sub2apiprovider.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.BaseURL(); ok {
		_spec.SetField(sub2apiprovider.FieldBaseURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderType(); ok {
		_spec.SetField(sub2apiprovider.FieldProviderType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(sub2apiprovider.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(sub2apiprovider.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(sub2apiprovider.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(sub2apiprovider.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordEncrypted(); ok {
		_spec.SetField(sub2apiprovider.FieldPasswordEncrypted, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIPathKeys(); ok {
		_spec.SetField(sub2apiprovider.FieldAPIPathKeys, field.TypeString, value)
	}
	if _u.mutation.APIPathKeysCleared() {
		_spec.ClearField(sub2apiprovider.FieldAPIPathKeys, field.TypeString)
	}
	if value, ok := _u.mutation.APIPathGroups(); ok {
		_spec.SetField(sub2apiprovider.FieldAPIPathGroups, field.TypeString, value)
	}
	if _u.mutation.APIPathGroupsCleared() {
		_spec.ClearField(sub2apiprovider.FieldAPIPathGroups, field.TypeString)
	}
	if value, ok := _u.mutation.LastSyncAt(); ok {
		_spec.SetField(sub2apiprovider.FieldLastSyncAt, field.TypeTime, value)
	}
	if _u.mutation.LastSyncAtCleared() {
		_spec.ClearField(sub2apiprovider.FieldLastSyncAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastSyncStatus(); ok {
		_spec.SetField(sub2apiprovider.FieldLastSyncStatus, field.TypeString, value)
	}
	if _u.mutation.LastSyncStatusCleared() {
		_spec.ClearField(sub2apiprovider.FieldLastSyncStatus, field.TypeString)
	}
	if value, ok := _u.mutation.LastSyncError(); ok {
		_spec.SetField(sub2apiprovider.FieldLastSyncError, field.TypeString, value)
	}
	if _u.mutation.LastSyncErrorCleared() {
		_spec.ClearField(sub2apiprovider.FieldLastSyncError, field.TypeString)
	}
	if _u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sub2apiprovider.AccountsTable,
			Columns: []string{sub2apiprovider.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAccountsIDs(); len(nodes) > 0 && !_u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sub2apiprovider.AccountsTable,
			Columns: []string{sub2apiprovider.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sub2apiprovider.AccountsTable,
			Columns: []string{sub2apiprovider.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OptimizeScheduleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   sub2apiprovider.OptimizeScheduleTable,
			Columns: []string{sub2apiprovider.OptimizeScheduleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sub2apioptimizeschedule.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OptimizeScheduleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   sub2apiprovider.OptimizeScheduleTable,
			Columns: []string{sub2apiprovider.OptimizeScheduleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sub2apioptimizeschedule.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Sub2APIProvider{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sub2apiprovider.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
