// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/sub2apioptimizelog"
	"github.com/Wei-Shaw/sub2api/ent/sub2apioptimizeschedule"
	"github.com/Wei-Shaw/sub2api/ent/sub2apiprovider"
)

// Sub2APIOptimizeLogUpdate is the builder for updating Sub2APIOptimizeLog entities.
type Sub2APIOptimizeLogUpdate struct {
	config
	hooks    []Hook
	mutation *Sub2APIOptimizeLogMutation
}

// Where appends a list predicates to the Sub2APIOptimizeLogUpdate builder.
func (_u *Sub2APIOptimizeLogUpdate) Where(ps ...predicate.Sub2APIOptimizeLog) *Sub2APIOptimizeLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *Sub2APIOptimizeLogUpdate) SetUpdatedAt(v time.Time) *Sub2APIOptimizeLogUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProviderID sets the "provider_id" field.
func (_u *Sub2APIOptimizeLogUpdate) SetProviderID(v int64) *Sub2APIOptimizeLogUpdate {
	_u.mutation.SetProviderID(v)
	return _u
}

// SetNillableProviderID sets the "provider_id" field if the given value is not nil.
func (_u *Sub2APIOptimizeLogUpdate) SetNillableProviderID(v *int64) *Sub2APIOptimizeLogUpdate {
	if v != nil {
		_u.SetProviderID(*v)
	}
	return _u
}

// SetScheduleID sets the "schedule_id" field.
func (_u *Sub2APIOptimizeLogUpdate) SetScheduleID(v int64) *Sub2APIOptimizeLogUpdate {
	_u.mutation.SetScheduleID(v)
	return _u
}

// SetNillableScheduleID sets the "schedule_id" field if the given value is not nil.
func (_u *Sub2APIOptimizeLogUpdate) SetNillableScheduleID(v *int64) *Sub2APIOptimizeLogUpdate {
	if v != nil {
		_u.SetScheduleID(*v)
	}
	return _u
}

// ClearScheduleID clears the value of the "schedule_id" field.
func (_u *Sub2APIOptimizeLogUpdate) ClearScheduleID() *Sub2APIOptimizeLogUpdate {
	_u.mutation.ClearScheduleID()
	return _u
}

// SetTrigger sets the "trigger" field.
func (_u *Sub2APIOptimizeLogUpdate) SetTrigger(v string) *Sub2APIOptimizeLogUpdate {
	_u.mutation.SetTrigger(v)
	return _u
}

// SetNillableTrigger sets the "trigger" field if the given value is not nil.
func (_u *Sub2APIOptimizeLogUpdate) SetNillableTrigger(v *string) *Sub2APIOptimizeLogUpdate {
	if v != nil {
		_u.SetTrigger(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *Sub2APIOptimizeLogUpdate) SetStatus(v string) *Sub2APIOptimizeLogUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *Sub2APIOptimizeLogUpdate) SetNillableStatus(v *string) *Sub2APIOptimizeLogUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTotal sets the "total" field.
func (_u *Sub2APIOptimizeLogUpdate) SetTotal(v int) *Sub2APIOptimizeLogUpdate {
	_u.mutation.ResetTotal()
	_u.mutation.SetTotal(v)
	return _u
}

// SetNillableTotal sets the "total" field if the given value is not nil.
func (_u *Sub2APIOptimizeLogUpdate) SetNillableTotal(v *int) *Sub2APIOptimizeLogUpdate {
	if v != nil {
		_u.SetTotal(*v)
	}
	return _u
}

// AddTotal adds value to the "total" field.
func (_u *Sub2APIOptimizeLogUpdate) AddTotal(v int) *Sub2APIOptimizeLogUpdate {
	_u.mutation.AddTotal(v)
	return _u
}

// SetOptimized sets the "optimized" field.
func (_u *Sub2APIOptimizeLogUpdate) SetOptimized(v int) *Sub2APIOptimizeLogUpdate {
	_u.mutation.ResetOptimized()
	_u.mutation.SetOptimized(v)
	return _u
}

// SetNillableOptimized sets the "optimized" field if the given value is not nil.
func (_u *Sub2APIOptimizeLogUpdate) SetNillableOptimized(v *int) *Sub2APIOptimizeLogUpdate {
	if v != nil {
		_u.SetOptimized(*v)
	}
	return _u
}

// AddOptimized adds value to the "optimized" field.
func (_u *Sub2APIOptimizeLogUpdate) AddOptimized(v int) *Sub2APIOptimizeLogUpdate {
	_u.mutation.AddOptimized(v)
	return _u
}

// SetSkipped sets the "skipped" field.
func (_u *Sub2APIOptimizeLogUpdate) SetSkipped(v int) *Sub2APIOptimizeLogUpdate {
	_u.mutation.ResetSkipped()
	_u.mutation.SetSkipped(v)
	return _u
}

// SetNillableSkipped sets the "skipped" field if the given value is not nil.
func (_u *Sub2APIOptimizeLogUpdate) SetNillableSkipped(v *int) *Sub2APIOptimizeLogUpdate {
	if v != nil {
		_u.SetSkipped(*v)
	}
	return _u
}

// AddSkipped adds value to the "skipped" field.
func (_u *Sub2APIOptimizeLogUpdate) AddSkipped(v int) *Sub2APIOptimizeLogUpdate {
	_u.mutation.AddSkipped(v)
	return _u
}

// SetFailed sets the "failed" field.
func (_u *Sub2APIOptimizeLogUpdate) SetFailed(v int) *Sub2APIOptimizeLogUpdate {
	_u.mutation.ResetFailed()
	_u.mutation.SetFailed(v)
	return _u
}

// SetNillableFailed sets the "failed" field if the given value is not nil.
func (_u *Sub2APIOptimizeLogUpdate) SetNillableFailed(v *int) *Sub2APIOptimizeLogUpdate {
	if v != nil {
		_u.SetFailed(*v)
	}
	return _u
}

// AddFailed adds value to the "failed" field.
func (_u *Sub2APIOptimizeLogUpdate) AddFailed(v int) *Sub2APIOptimizeLogUpdate {
	_u.mutation.AddFailed(v)
	return _u
}

// SetDetail sets the "detail" field.
func (_u *Sub2APIOptimizeLogUpdate) SetDetail(v []map[string]interface{}) *Sub2APIOptimizeLogUpdate {
	_u.mutation.SetDetail(v)
	return _u
}

// AppendDetail appends value to the "detail" field.
func (_u *Sub2APIOptimizeLogUpdate) AppendDetail(v []map[string]interface{}) *Sub2APIOptimizeLogUpdate {
	_u.mutation.AppendDetail(v)
	return _u
}

// ClearDetail clears the value of the "detail" field.
func (_u *Sub2APIOptimizeLogUpdate) ClearDetail() *Sub2APIOptimizeLogUpdate {
	_u.mutation.ClearDetail()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *Sub2APIOptimizeLogUpdate) SetStartedAt(v time.Time) *Sub2APIOptimizeLogUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *Sub2APIOptimizeLogUpdate) SetNillableStartedAt(v *time.Time) *Sub2APIOptimizeLogUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *Sub2APIOptimizeLogUpdate) ClearStartedAt() *Sub2APIOptimizeLogUpdate {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *Sub2APIOptimizeLogUpdate) SetFinishedAt(v time.Time) *Sub2APIOptimizeLogUpdate {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *Sub2APIOptimizeLogUpdate) SetNillableFinishedAt(v *time.Time) *Sub2APIOptimizeLogUpdate {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *Sub2APIOptimizeLogUpdate) ClearFinishedAt() *Sub2APIOptimizeLogUpdate {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetProvider sets the "provider" edge to the Sub2APIProvider entity.
func (_u *Sub2APIOptimizeLogUpdate) SetProvider(v *Sub2APIProvider) *Sub2APIOptimizeLogUpdate {
	return _u.SetProviderID(v.ID)
}

// SetSchedule sets the "schedule" edge to the Sub2APIOptimizeSchedule entity.
func (_u *Sub2APIOptimizeLogUpdate) SetSchedule(v *Sub2APIOptimizeSchedule) *Sub2APIOptimizeLogUpdate {
	return _u.SetScheduleID(v.ID)
}

// Mutation returns the Sub2APIOptimizeLogMutation object of the builder.
func (_u *Sub2APIOptimizeLogUpdate) Mutation() *Sub2APIOptimizeLogMutation {
	return _u.mutation
}

// ClearProvider clears the "provider" edge to the Sub2APIProvider entity.
func (_u *Sub2APIOptimizeLogUpdate) ClearProvider() *Sub2APIOptimizeLogUpdate {
	_u.mutation.ClearProvider()
	return _u
}

// ClearSchedule clears the "schedule" edge to the Sub2APIOptimizeSchedule entity.
func (_u *Sub2APIOptimizeLogUpdate) ClearSchedule() *Sub2APIOptimizeLogUpdate {
	_u.mutation.ClearSchedule()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *Sub2APIOptimizeLogUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *Sub2APIOptimizeLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *Sub2APIOptimizeLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *Sub2APIOptimizeLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *Sub2APIOptimizeLogUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := sub2apioptimizelog.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *Sub2APIOptimizeLogUpdate) check() error {
	if v, ok := _u.mutation.Trigger(); ok {
		if err := sub2apioptimizelog.TriggerValidator(v); err != nil {
			return &ValidationError{Name: "trigger", err: fmt.Errorf(`ent: validator failed for field "Sub2APIOptimizeLog.trigger": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := sub2apioptimizelog.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Sub2APIOptimizeLog.status": %w`, err)}
		}
	}
	if _u.mutation.ProviderCleared() && len(_u.mutation.ProviderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Sub2APIOptimizeLog.provider"`)
	}
	return nil
}

func (_u *Sub2APIOptimizeLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sub2apioptimizelog.Table, sub2apioptimizelog.Columns, sqlgraph.NewFieldSpec(sub2apioptimizelog.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sub2apioptimizelog.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Trigger(); ok {
		_spec.SetField(sub2apioptimizelog.FieldTrigger, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(sub2apioptimizelog.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Total(); ok {
		_spec.SetField(sub2apioptimizelog.FieldTotal, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotal(); ok {
		_spec.AddField(sub2apioptimizelog.FieldTotal, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Optimized(); ok {
		_spec.SetField(sub2apioptimizelog.FieldOptimized, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOptimized(); ok {
		_spec.AddField(sub2apioptimizelog.FieldOptimized, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Skipped(); ok {
		_spec.SetField(sub2apioptimizelog.FieldSkipped, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSkipped(); ok {
		_spec.AddField(sub2apioptimizelog.FieldSkipped, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Failed(); ok {
		_spec.SetField(sub2apioptimizelog.FieldFailed, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFailed(); ok {
		_spec.AddField(sub2apioptimizelog.FieldFailed, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Detail(); ok {
		_spec.SetField(sub2apioptimizelog.FieldDetail, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedDetail(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, sub2apioptimizelog.FieldDetail, value)
		})
	}
	if _u.mutation.DetailCleared() {
		_spec.ClearField(sub2apioptimizelog.FieldDetail, field.TypeJSON)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(sub2apioptimizelog.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(sub2apioptimizelog.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(sub2apioptimizelog.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(sub2apioptimizelog.FieldFinishedAt, field.TypeTime)
	}
	if _u.mutation.ProviderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sub2apioptimizelog.ProviderTable,
			Columns: []string{sub2apioptimizelog.ProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sub2apiprovider.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProviderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sub2apioptimizelog.ProviderTable,
			Columns: []string{sub2apioptimizelog.ProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sub2apiprovider.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ScheduleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sub2apioptimizelog.ScheduleTable,
			Columns: []string{sub2apioptimizelog.ScheduleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sub2apioptimizeschedule.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ScheduleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sub2apioptimizelog.ScheduleTable,
			Columns: []string{sub2apioptimizelog.ScheduleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sub2apioptimizeschedule.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sub2apioptimizelog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// Sub2APIOptimizeLogUpdateOne is the builder for updating a single Sub2APIOptimizeLog entity.
type Sub2APIOptimizeLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *Sub2APIOptimizeLogMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *Sub2APIOptimizeLogUpdateOne) SetUpdatedAt(v time.Time) *Sub2APIOptimizeLogUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProviderID sets the "provider_id" field.
func (_u *Sub2APIOptimizeLogUpdateOne) SetProviderID(v int64) *Sub2APIOptimizeLogUpdateOne {
	_u.mutation.SetProviderID(v)
	return _u
}

// SetNillableProviderID sets the "provider_id" field if the given value is not nil.
func (_u *Sub2APIOptimizeLogUpdateOne) SetNillableProviderID(v *int64) *Sub2APIOptimizeLogUpdateOne {
	if v != nil {
		_u.SetProviderID(*v)
	}
	return _u
}

// SetScheduleID sets the "schedule_id" field.
func (_u *Sub2APIOptimizeLogUpdateOne) SetScheduleID(v int64) *Sub2APIOptimizeLogUpdateOne {
	_u.mutation.SetScheduleID(v)
	return _u
}

// SetNillableScheduleID sets the "schedule_id" field if the given value is not nil.
func (_u *Sub2APIOptimizeLogUpdateOne) SetNillableScheduleID(v *int64) *Sub2APIOptimizeLogUpdateOne {
	if v != nil {
		_u.SetScheduleID(*v)
	}
	return _u
}

// ClearScheduleID clears the value of the "schedule_id" field.
func (_u *Sub2APIOptimizeLogUpdateOne) ClearScheduleID() *Sub2APIOptimizeLogUpdateOne {
	_u.mutation.ClearScheduleID()
	return _u
}

// SetTrigger sets the "trigger" field.
func (_u *Sub2APIOptimizeLogUpdateOne) SetTrigger(v string) *Sub2APIOptimizeLogUpdateOne {
	_u.mutation.SetTrigger(v)
	return _u
}

// SetNillableTrigger sets the "trigger" field if the given value is not nil.
func (_u *Sub2APIOptimizeLogUpdateOne) SetNillableTrigger(v *string) *Sub2APIOptimizeLogUpdateOne {
	if v != nil {
		_u.SetTrigger(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *Sub2APIOptimizeLogUpdateOne) SetStatus(v string) *Sub2APIOptimizeLogUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *Sub2APIOptimizeLogUpdateOne) SetNillableStatus(v *string) *Sub2APIOptimizeLogUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTotal sets the "total" field.
func (_u *Sub2APIOptimizeLogUpdateOne) SetTotal(v int) *Sub2APIOptimizeLogUpdateOne {
	_u.mutation.ResetTotal()
	_u.mutation.SetTotal(v)
	return _u
}

// SetNillableTotal sets the "total" field if the given value is not nil.
func (_u *Sub2APIOptimizeLogUpdateOne) SetNillableTotal(v *int) *Sub2APIOptimizeLogUpdateOne {
	if v != nil {
		_u.SetTotal(*v)
	}
	return _u
}

// AddTotal adds value to the "total" field.
func (_u *Sub2APIOptimizeLogUpdateOne) AddTotal(v int) *Sub2APIOptimizeLogUpdateOne {
	_u.mutation.AddTotal(v)
	return _u
}

// SetOptimized sets the "optimized" field.
func (_u *Sub2APIOptimizeLogUpdateOne) SetOptimized(v int) *Sub2APIOptimizeLogUpdateOne {
	_u.mutation.ResetOptimized()
	_u.mutation.SetOptimized(v)
	return _u
}

// SetNillableOptimized sets the "optimized" field if the given value is not nil.
func (_u *Sub2APIOptimizeLogUpdateOne) SetNillableOptimized(v *int) *Sub2APIOptimizeLogUpdateOne {
	if v != nil {
		_u.SetOptimized(*v)
	}
	return _u
}

// AddOptimized adds value to the "optimized" field.
func (_u *Sub2APIOptimizeLogUpdateOne) AddOptimized(v int) *Sub2APIOptimizeLogUpdateOne {
	_u.mutation.AddOptimized(v)
	return _u
}

// SetSkipped sets the "skipped" field.
func (_u *Sub2APIOptimizeLogUpdateOne) SetSkipped(v int) *Sub2APIOptimizeLogUpdateOne {
	_u.mutation.ResetSkipped()
	_u.mutation.SetSkipped(v)
	return _u
}

// SetNillableSkipped sets the "skipped" field if the given value is not nil.
func (_u *Sub2APIOptimizeLogUpdateOne) SetNillableSkipped(v *int) *Sub2APIOptimizeLogUpdateOne {
	if v != nil {
		_u.SetSkipped(*v)
	}
	return _u
}

// AddSkipped adds value to the "skipped" field.
func (_u *Sub2APIOptimizeLogUpdateOne) AddSkipped(v int) *Sub2APIOptimizeLogUpdateOne {
	_u.mutation.AddSkipped(v)
	return _u
}

// SetFailed sets the "failed" field.
func (_u *Sub2APIOptimizeLogUpdateOne) SetFailed(v int) *Sub2APIOptimizeLogUpdateOne {
	_u.mutation.ResetFailed()
	_u.mutation.SetFailed(v)
	return _u
}

// SetNillableFailed sets the "failed" field if the given value is not nil.
func (_u *Sub2APIOptimizeLogUpdateOne) SetNillableFailed(v *int) *Sub2APIOptimizeLogUpdateOne {
	if v != nil {
		_u.SetFailed(*v)
	}
	return _u
}

// AddFailed adds value to the "failed" field.
func (_u *Sub2APIOptimizeLogUpdateOne) AddFailed(v int) *Sub2APIOptimizeLogUpdateOne {
	_u.mutation.AddFailed(v)
	return _u
}

// SetDetail sets the "detail" field.
func (_u *Sub2APIOptimizeLogUpdateOne) SetDetail(v []map[string]interface{}) *Sub2APIOptimizeLogUpdateOne {
	_u.mutation.SetDetail(v)
	return _u
}

// AppendDetail appends value to the "detail" field.
func (_u *Sub2APIOptimizeLogUpdateOne) AppendDetail(v []map[string]interface{}) *Sub2APIOptimizeLogUpdateOne {
	_u.mutation.AppendDetail(v)
	return _u
}

// ClearDetail clears the value of the "detail" field.
func (_u *Sub2APIOptimizeLogUpdateOne) ClearDetail() *Sub2APIOptimizeLogUpdateOne {
	_u.mutation.ClearDetail()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *Sub2APIOptimizeLogUpdateOne) SetStartedAt(v time.Time) *Sub2APIOptimizeLogUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *Sub2APIOptimizeLogUpdateOne) SetNillableStartedAt(v *time.Time) *Sub2APIOptimizeLogUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *Sub2APIOptimizeLogUpdateOne) ClearStartedAt() *Sub2APIOptimizeLogUpdateOne {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *Sub2APIOptimizeLogUpdateOne) SetFinishedAt(v time.Time) *Sub2APIOptimizeLogUpdateOne {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *Sub2APIOptimizeLogUpdateOne) SetNillableFinishedAt(v *time.Time) *Sub2APIOptimizeLogUpdateOne {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *Sub2APIOptimizeLogUpdateOne) ClearFinishedAt() *Sub2APIOptimizeLogUpdateOne {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetProvider sets the "provider" edge to the Sub2APIProvider entity.
func (_u *Sub2APIOptimizeLogUpdateOne) SetProvider(v *Sub2APIProvider) *Sub2APIOptimizeLogUpdateOne {
	return _u.SetProviderID(v.ID)
}

// SetSchedule sets the "schedule" edge to the Sub2APIOptimizeSchedule entity.
func (_u *Sub2APIOptimizeLogUpdateOne) SetSchedule(v *Sub2APIOptimizeSchedule) *Sub2APIOptimizeLogUpdateOne {
	return _u.SetScheduleID(v.ID)
}

// Mutation returns the Sub2APIOptimizeLogMutation object of the builder.
func (_u *Sub2APIOptimizeLogUpdateOne) Mutation() *Sub2APIOptimizeLogMutation {
	return _u.mutation
}

// ClearProvider clears the "provider" edge to the Sub2APIProvider entity.
func (_u *Sub2APIOptimizeLogUpdateOne) ClearProvider() *Sub2APIOptimizeLogUpdateOne {
	_u.mutation.ClearProvider()
	return _u
}

// ClearSchedule clears the "schedule" edge to the Sub2APIOptimizeSchedule entity.
func (_u *Sub2APIOptimizeLogUpdateOne) ClearSchedule() *Sub2APIOptimizeLogUpdateOne {
	_u.mutation.ClearSchedule()
	return _u
}

// Where appends a list predicates to the Sub2APIOptimizeLogUpdate builder.
func (_u *Sub2APIOptimizeLogUpdateOne) Where(ps ...predicate.Sub2APIOptimizeLog) *Sub2APIOptimizeLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *Sub2APIOptimizeLogUpdateOne) Select(field string, fields ...string) *Sub2APIOptimizeLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Sub2APIOptimizeLog entity.
func (_u *Sub2APIOptimizeLogUpdateOne) Save(ctx context.Context) (*Sub2APIOptimizeLog, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *Sub2APIOptimizeLogUpdateOne) SaveX(ctx context.Context) *Sub2APIOptimizeLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *Sub2APIOptimizeLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *Sub2APIOptimizeLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *Sub2APIOptimizeLogUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := sub2apioptimizelog.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *Sub2APIOptimizeLogUpdateOne) check() error {
	if v, ok := _u.mutation.Trigger(); ok {
		if err := sub2apioptimizelog.TriggerValidator(v); err != nil {
			return &ValidationError{Name: "trigger", err: fmt.Errorf(`ent: validator failed for field "Sub2APIOptimizeLog.trigger": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := sub2apioptimizelog.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Sub2APIOptimizeLog.status": %w`, err)}
		}
	}
	if _u.mutation.ProviderCleared() && len(_u.mutation.ProviderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Sub2APIOptimizeLog.provider"`)
	}
	return nil
}

func (_u *Sub2APIOptimizeLogUpdateOne) sqlSave(ctx context.Context) (_node *Sub2APIOptimizeLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sub2apioptimizelog.Table, sub2apioptimizelog.Columns, sqlgraph.NewFieldSpec(sub2apioptimizelog.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Sub2APIOptimizeLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sub2apioptimizelog.FieldID)
		for _, f := range fields {
			if !sub2apioptimizelog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sub2apioptimizelog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sub2apioptimizelog.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Trigger(); ok {
		_spec.SetField(sub2apioptimizelog.FieldTrigger, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(sub2apioptimizelog.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Total(); ok {
		_spec.SetField(sub2apioptimizelog.FieldTotal, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotal(); ok {
		_spec.AddField(sub2apioptimizelog.FieldTotal, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Optimized(); ok {
		_spec.SetField(sub2apioptimizelog.FieldOptimized, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOptimized(); ok {
		_spec.AddField(sub2apioptimizelog.FieldOptimized, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Skipped(); ok {
		_spec.SetField(sub2apioptimizelog.FieldSkipped, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSkipped(); ok {
		_spec.AddField(sub2apioptimizelog.FieldSkipped, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Failed(); ok {
		_spec.SetField(sub2apioptimizelog.FieldFailed, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFailed(); ok {
		_spec.AddField(sub2apioptimizelog.FieldFailed, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Detail(); ok {
		_spec.SetField(sub2apioptimizelog.FieldDetail, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedDetail(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, sub2apioptimizelog.FieldDetail, value)
		})
	}
	if _u.mutation.DetailCleared() {
		_spec.ClearField(sub2apioptimizelog.FieldDetail, field.TypeJSON)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(sub2apioptimizelog.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(sub2apioptimizelog.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(sub2apioptimizelog.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(sub2apioptimizelog.FieldFinishedAt, field.TypeTime)
	}
	if _u.mutation.ProviderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sub2apioptimizelog.ProviderTable,
			Columns: []string{sub2apioptimizelog.ProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sub2apiprovider.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProviderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sub2apioptimizelog.ProviderTable,
			Columns: []string{sub2apioptimizelog.ProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sub2apiprovider.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ScheduleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sub2apioptimizelog.ScheduleTable,
			Columns: []string{sub2apioptimizelog.ScheduleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sub2apioptimizeschedule.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ScheduleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sub2apioptimizelog.ScheduleTable,
			Columns: []string{sub2apioptimizelog.ScheduleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sub2apioptimizeschedule.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Sub2APIOptimizeLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sub2apioptimizelog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
