// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/sub2apioptimizelog"
	"github.com/Wei-Shaw/sub2api/ent/sub2apioptimizeschedule"
	"github.com/Wei-Shaw/sub2api/ent/sub2apiprovider"
)

// Sub2APIOptimizeLogQuery is the builder for querying Sub2APIOptimizeLog entities.
type Sub2APIOptimizeLogQuery struct {
	config
	ctx          *QueryContext
	order        []sub2apioptimizelog.OrderOption
	inters       []Interceptor
	predicates   []predicate.Sub2APIOptimizeLog
	withProvider *Sub2APIProviderQuery
	withSchedule *Sub2APIOptimizeScheduleQuery
	modifiers    []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the Sub2APIOptimizeLogQuery builder.
func (_q *Sub2APIOptimizeLogQuery) Where(ps ...predicate.Sub2APIOptimizeLog) *Sub2APIOptimizeLogQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *Sub2APIOptimizeLogQuery) Limit(limit int) *Sub2APIOptimizeLogQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *Sub2APIOptimizeLogQuery) Offset(offset int) *Sub2APIOptimizeLogQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *Sub2APIOptimizeLogQuery) Unique(unique bool) *Sub2APIOptimizeLogQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *Sub2APIOptimizeLogQuery) Order(o ...sub2apioptimizelog.OrderOption) *Sub2APIOptimizeLogQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryProvider chains the current query on the "provider" edge.
func (_q *Sub2APIOptimizeLogQuery) QueryProvider() *Sub2APIProviderQuery {
	query := (&Sub2APIProviderClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(sub2apioptimizelog.Table, sub2apioptimizelog.FieldID, selector),
			sqlgraph.To(sub2apiprovider.Table, sub2apiprovider.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, sub2apioptimizelog.ProviderTable, sub2apioptimizelog.ProviderColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySchedule chains the current query on the "schedule" edge.
func (_q *Sub2APIOptimizeLogQuery) QuerySchedule() *Sub2APIOptimizeScheduleQuery {
	query := (&Sub2APIOptimizeScheduleClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(sub2apioptimizelog.Table, sub2apioptimizelog.FieldID, selector),
			sqlgraph.To(sub2apioptimizeschedule.Table, sub2apioptimizeschedule.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, sub2apioptimizelog.ScheduleTable, sub2apioptimizelog.ScheduleColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Sub2APIOptimizeLog entity from the query.
// Returns a *NotFoundError when no Sub2APIOptimizeLog was found.
func (_q *Sub2APIOptimizeLogQuery) First(ctx context.Context) (*Sub2APIOptimizeLog, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{sub2apioptimizelog.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *Sub2APIOptimizeLogQuery) FirstX(ctx context.Context) *Sub2APIOptimizeLog {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Sub2APIOptimizeLog ID from the query.
// Returns a *NotFoundError when no Sub2APIOptimizeLog ID was found.
func (_q *Sub2APIOptimizeLogQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{sub2apioptimizelog.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *Sub2APIOptimizeLogQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Sub2APIOptimizeLog entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Sub2APIOptimizeLog entity is found.
// Returns a *NotFoundError when no Sub2APIOptimizeLog entities are found.
func (_q *Sub2APIOptimizeLogQuery) Only(ctx context.Context) (*Sub2APIOptimizeLog, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{sub2apioptimizelog.Label}
	default:
		return nil, &NotSingularError{sub2apioptimizelog.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *Sub2APIOptimizeLogQuery) OnlyX(ctx context.Context) *Sub2APIOptimizeLog {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Sub2APIOptimizeLog ID in the query.
// Returns a *NotSingularError when more than one Sub2APIOptimizeLog ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *Sub2APIOptimizeLogQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{sub2apioptimizelog.Label}
	default:
		err = &NotSingularError{sub2apioptimizelog.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *Sub2APIOptimizeLogQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Sub2APIOptimizeLogs.
func (_q *Sub2APIOptimizeLogQuery) All(ctx context.Context) ([]*Sub2APIOptimizeLog, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Sub2APIOptimizeLog, *Sub2APIOptimizeLogQuery]()
	return withInterceptors[[]*Sub2APIOptimizeLog](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *Sub2APIOptimizeLogQuery) AllX(ctx context.Context) []*Sub2APIOptimizeLog {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Sub2APIOptimizeLog IDs.
func (_q *Sub2APIOptimizeLogQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(sub2apioptimizelog.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *Sub2APIOptimizeLogQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *Sub2APIOptimizeLogQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*Sub2APIOptimizeLogQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *Sub2APIOptimizeLogQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *Sub2APIOptimizeLogQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *Sub2APIOptimizeLogQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the Sub2APIOptimizeLogQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *Sub2APIOptimizeLogQuery) Clone() *Sub2APIOptimizeLogQuery {
	if _q == nil {
		return nil
	}
	return &Sub2APIOptimizeLogQuery{
		config:       _q.config,
		ctx:          _q.ctx.Clone(),
		order:        append([]sub2apioptimizelog.OrderOption{}, _q.order...),
		inters:       append([]Interceptor{}, _q.inters...),
		predicates:   append([]predicate.Sub2APIOptimizeLog{}, _q.predicates...),
		withProvider: _q.withProvider.Clone(),
		withSchedule: _q.withSchedule.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithProvider tells the query-builder to eager-load the nodes that are connected to
// the "provider" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *Sub2APIOptimizeLogQuery) WithProvider(opts ...func(*Sub2APIProviderQuery)) *Sub2APIOptimizeLogQuery {
	query := (&Sub2APIProviderClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withProvider = query
	return _q
}

// WithSchedule tells the query-builder to eager-load the nodes that are connected to
// the "schedule" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *Sub2APIOptimizeLogQuery) WithSchedule(opts ...func(*Sub2APIOptimizeScheduleQuery)) *Sub2APIOptimizeLogQuery {
	query := (&Sub2APIOptimizeScheduleClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSchedule = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Sub2APIOptimizeLog.Query().
//		GroupBy(sub2apioptimizelog.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *Sub2APIOptimizeLogQuery) GroupBy(field string, fields ...string) *Sub2APIOptimizeLogGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &Sub2APIOptimizeLogGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = sub2apioptimizelog.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.Sub2APIOptimizeLog.Query().
//		Select(sub2apioptimizelog.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *Sub2APIOptimizeLogQuery) Select(fields ...string) *Sub2APIOptimizeLogSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &Sub2APIOptimizeLogSelect{Sub2APIOptimizeLogQuery: _q}
	sbuild.label = sub2apioptimizelog.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a Sub2APIOptimizeLogSelect configured with the given aggregations.
func (_q *Sub2APIOptimizeLogQuery) Aggregate(fns ...AggregateFunc) *Sub2APIOptimizeLogSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *Sub2APIOptimizeLogQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !sub2apioptimizelog.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *Sub2APIOptimizeLogQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Sub2APIOptimizeLog, error) {
	var (
		nodes       = []*Sub2APIOptimizeLog{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withProvider != nil,
			_q.withSchedule != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Sub2APIOptimizeLog).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Sub2APIOptimizeLog{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withProvider; query != nil {
		if err := _q.loadProvider(ctx, query, nodes, nil,
			func(n *Sub2APIOptimizeLog, e *Sub2APIProvider) { n.Edges.Provider = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withSchedule; query != nil {
		if err := _q.loadSchedule(ctx, query, nodes, nil,
			func(n *Sub2APIOptimizeLog, e *Sub2APIOptimizeSchedule) { n.Edges.Schedule = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *Sub2APIOptimizeLogQuery) loadProvider(ctx context.Context, query *Sub2APIProviderQuery, nodes []*Sub2APIOptimizeLog, init func(*Sub2APIOptimizeLog), assign func(*Sub2APIOptimizeLog, *Sub2APIProvider)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*Sub2APIOptimizeLog)
	for i := range nodes {
		fk := nodes[i].ProviderID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(sub2apiprovider.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "provider_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *Sub2APIOptimizeLogQuery) loadSchedule(ctx context.Context, query *Sub2APIOptimizeScheduleQuery, nodes []*Sub2APIOptimizeLog, init func(*Sub2APIOptimizeLog), assign func(*Sub2APIOptimizeLog, *Sub2APIOptimizeSchedule)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*Sub2APIOptimizeLog)
	for i := range nodes {
		if nodes[i].ScheduleID == nil {
			continue
		}
		fk := *nodes[i].ScheduleID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(sub2apioptimizeschedule.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "schedule_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *Sub2APIOptimizeLogQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *Sub2APIOptimizeLogQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(sub2apioptimizelog.Table, sub2apioptimizelog.Columns, sqlgraph.NewFieldSpec(sub2apioptimizelog.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sub2apioptimizelog.FieldID)
		for i := range fields {
			if fields[i] != sub2apioptimizelog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withProvider != nil {
			_spec.Node.AddColumnOnce(sub2apioptimizelog.FieldProviderID)
		}
		if _q.withSchedule != nil {
			_spec.Node.AddColumnOnce(sub2apioptimizelog.FieldScheduleID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *Sub2APIOptimizeLogQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(sub2apioptimizelog.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = sub2apioptimizelog.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *Sub2APIOptimizeLogQuery) ForUpdate(opts ...sql.LockOption) *Sub2APIOptimizeLogQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *Sub2APIOptimizeLogQuery) ForShare(opts ...sql.LockOption) *Sub2APIOptimizeLogQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// Sub2APIOptimizeLogGroupBy is the group-by builder for Sub2APIOptimizeLog entities.
type Sub2APIOptimizeLogGroupBy struct {
	selector
	build *Sub2APIOptimizeLogQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *Sub2APIOptimizeLogGroupBy) Aggregate(fns ...AggregateFunc) *Sub2APIOptimizeLogGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *Sub2APIOptimizeLogGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*Sub2APIOptimizeLogQuery, *Sub2APIOptimizeLogGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *Sub2APIOptimizeLogGroupBy) sqlScan(ctx context.Context, root *Sub2APIOptimizeLogQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Sub2APIOptimizeLogSelect is the builder for selecting fields of Sub2APIOptimizeLog entities.
type Sub2APIOptimizeLogSelect struct {
	*Sub2APIOptimizeLogQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *Sub2APIOptimizeLogSelect) Aggregate(fns ...AggregateFunc) *Sub2APIOptimizeLogSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *Sub2APIOptimizeLogSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*Sub2APIOptimizeLogQuery, *Sub2APIOptimizeLogSelect](ctx, _s.Sub2APIOptimizeLogQuery, _s, _s.inters, v)
}

func (_s *Sub2APIOptimizeLogSelect) sqlScan(ctx context.Context, root *Sub2APIOptimizeLogQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
