// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/sub2apiprovider"
	"github.com/Wei-Shaw/sub2api/ent/sub2apiproviderprobeconfig"
)

// Sub2APIProviderProbeConfig is the model entity for the Sub2APIProviderProbeConfig schema.
type Sub2APIProviderProbeConfig struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// ProviderID holds the value of the "provider_id" field.
	ProviderID int64 `json:"provider_id,omitempty"`
	// ControlEnabled holds the value of the "control_enabled" field.
	ControlEnabled bool `json:"control_enabled,omitempty"`
	// ControlIntervalSeconds holds the value of the "control_interval_seconds" field.
	ControlIntervalSeconds int `json:"control_interval_seconds,omitempty"`
	// DataEnabled holds the value of the "data_enabled" field.
	DataEnabled bool `json:"data_enabled,omitempty"`
	// DataIntervalSeconds holds the value of the "data_interval_seconds" field.
	DataIntervalSeconds int `json:"data_interval_seconds,omitempty"`
	// SelectedAccountIds holds the value of the "selected_account_ids" field.
	SelectedAccountIds []int64 `json:"selected_account_ids,omitempty"`
	// AllowMediaProbe holds the value of the "allow_media_probe" field.
	AllowMediaProbe bool `json:"allow_media_probe,omitempty"`
	// TimeoutSeconds holds the value of the "timeout_seconds" field.
	TimeoutSeconds int `json:"timeout_seconds,omitempty"`
	// DegradedLatencyMs holds the value of the "degraded_latency_ms" field.
	DegradedLatencyMs int `json:"degraded_latency_ms,omitempty"`
	// FailureThreshold holds the value of the "failure_threshold" field.
	FailureThreshold int `json:"failure_threshold,omitempty"`
	// RecoveryThreshold holds the value of the "recovery_threshold" field.
	RecoveryThreshold int `json:"recovery_threshold,omitempty"`
	// LastControlRunAt holds the value of the "last_control_run_at" field.
	LastControlRunAt *time.Time `json:"last_control_run_at,omitempty"`
	// LastDataRunAt holds the value of the "last_data_run_at" field.
	LastDataRunAt *time.Time `json:"last_data_run_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the Sub2APIProviderProbeConfigQuery when eager-loading is set.
	Edges        Sub2APIProviderProbeConfigEdges `json:"edges"`
	selectValues sql.SelectValues
}

// Sub2APIProviderProbeConfigEdges holds the relations/edges for other nodes in the graph.
type Sub2APIProviderProbeConfigEdges struct {
	// Provider holds the value of the provider edge.
	Provider *Sub2APIProvider `json:"provider,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ProviderOrErr returns the Provider value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e Sub2APIProviderProbeConfigEdges) ProviderOrErr() (*Sub2APIProvider, error) {
	if e.Provider != nil {
		return e.Provider, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: sub2apiprovider.Label}
	}
	return nil, &NotLoadedError{edge: "provider"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Sub2APIProviderProbeConfig) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case sub2apiproviderprobeconfig.FieldSelectedAccountIds:
			values[i] = new([]byte)
		case sub2apiproviderprobeconfig.FieldControlEnabled, sub2apiproviderprobeconfig.FieldDataEnabled, sub2apiproviderprobeconfig.FieldAllowMediaProbe:
			values[i] = new(sql.NullBool)
		case sub2apiproviderprobeconfig.FieldID, sub2apiproviderprobeconfig.FieldProviderID, sub2apiproviderprobeconfig.FieldControlIntervalSeconds, sub2apiproviderprobeconfig.FieldDataIntervalSeconds, sub2apiproviderprobeconfig.FieldTimeoutSeconds, sub2apiproviderprobeconfig.FieldDegradedLatencyMs, sub2apiproviderprobeconfig.FieldFailureThreshold, sub2apiproviderprobeconfig.FieldRecoveryThreshold:
			values[i] = new(sql.NullInt64)
		case sub2apiproviderprobeconfig.FieldCreatedAt, sub2apiproviderprobeconfig.FieldUpdatedAt, sub2apiproviderprobeconfig.FieldLastControlRunAt, sub2apiproviderprobeconfig.FieldLastDataRunAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Sub2APIProviderProbeConfig fields.
func (_m *Sub2APIProviderProbeConfig) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case sub2apiproviderprobeconfig.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case sub2apiproviderprobeconfig.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case sub2apiproviderprobeconfig.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case sub2apiproviderprobeconfig.FieldProviderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field provider_id", values[i])
			} else if value.Valid {
				_m.ProviderID = value.Int64
			}
		case sub2apiproviderprobeconfig.FieldControlEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field control_enabled", values[i])
			} else if value.Valid {
				_m.ControlEnabled = value.Bool
			}
		case sub2apiproviderprobeconfig.FieldControlIntervalSeconds:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field control_interval_seconds", values[i])
			} else if value.Valid {
				_m.ControlIntervalSeconds = int(value.Int64)
			}
		case sub2apiproviderprobeconfig.FieldDataEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field data_enabled", values[i])
			} else if value.Valid {
				_m.DataEnabled = value.Bool
			}
		case sub2apiproviderprobeconfig.FieldDataIntervalSeconds:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field data_interval_seconds", values[i])
			} else if value.Valid {
				_m.DataIntervalSeconds = int(value.Int64)
			}
		case sub2apiproviderprobeconfig.FieldSelectedAccountIds:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field selected_account_ids", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.SelectedAccountIds); err != nil {
					return fmt.Errorf("unmarshal field selected_account_ids: %w", err)
				}
			}
		case sub2apiproviderprobeconfig.FieldAllowMediaProbe:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field allow_media_probe", values[i])
			} else if value.Valid {
				_m.AllowMediaProbe = value.Bool
			}
		case sub2apiproviderprobeconfig.FieldTimeoutSeconds:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field timeout_seconds", values[i])
			} else if value.Valid {
				_m.TimeoutSeconds = int(value.Int64)
			}
		case sub2apiproviderprobeconfig.FieldDegradedLatencyMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field degraded_latency_ms", values[i])
			} else if value.Valid {
				_m.DegradedLatencyMs = int(value.Int64)
			}
		case sub2apiproviderprobeconfig.FieldFailureThreshold:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field failure_threshold", values[i])
			} else if value.Valid {
				_m.FailureThreshold = int(value.Int64)
			}
		case sub2apiproviderprobeconfig.FieldRecoveryThreshold:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field recovery_threshold", values[i])
			} else if value.Valid {
				_m.RecoveryThreshold = int(value.Int64)
			}
		case sub2apiproviderprobeconfig.FieldLastControlRunAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_control_run_at", values[i])
			} else if value.Valid {
				_m.LastControlRunAt = new(time.Time)
				*_m.LastControlRunAt = value.Time
			}
		case sub2apiproviderprobeconfig.FieldLastDataRunAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_data_run_at", values[i])
			} else if value.Valid {
				_m.LastDataRunAt = new(time.Time)
				*_m.LastDataRunAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Sub2APIProviderProbeConfig.
// This includes values selected through modifiers, order, etc.
func (_m *Sub2APIProviderProbeConfig) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProvider queries the "provider" edge of the Sub2APIProviderProbeConfig entity.
func (_m *Sub2APIProviderProbeConfig) QueryProvider() *Sub2APIProviderQuery {
	return NewSub2APIProviderProbeConfigClient(_m.config).QueryProvider(_m)
}

// Update returns a builder for updating this Sub2APIProviderProbeConfig.
// Note that you need to call Sub2APIProviderProbeConfig.Unwrap() before calling this method if this Sub2APIProviderProbeConfig
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Sub2APIProviderProbeConfig) Update() *Sub2APIProviderProbeConfigUpdateOne {
	return NewSub2APIProviderProbeConfigClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Sub2APIProviderProbeConfig entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Sub2APIProviderProbeConfig) Unwrap() *Sub2APIProviderProbeConfig {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Sub2APIProviderProbeConfig is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Sub2APIProviderProbeConfig) String() string {
	var builder strings.Builder
	builder.WriteString("Sub2APIProviderProbeConfig(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("provider_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProviderID))
	builder.WriteString(", ")
	builder.WriteString("control_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.ControlEnabled))
	builder.WriteString(", ")
	builder.WriteString("control_interval_seconds=")
	builder.WriteString(fmt.Sprintf("%v", _m.ControlIntervalSeconds))
	builder.WriteString(", ")
	builder.WriteString("data_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.DataEnabled))
	builder.WriteString(", ")
	builder.WriteString("data_interval_seconds=")
	builder.WriteString(fmt.Sprintf("%v", _m.DataIntervalSeconds))
	builder.WriteString(", ")
	builder.WriteString("selected_account_ids=")
	builder.WriteString(fmt.Sprintf("%v", _m.SelectedAccountIds))
	builder.WriteString(", ")
	builder.WriteString("allow_media_probe=")
	builder.WriteString(fmt.Sprintf("%v", _m.AllowMediaProbe))
	builder.WriteString(", ")
	builder.WriteString("timeout_seconds=")
	builder.WriteString(fmt.Sprintf("%v", _m.TimeoutSeconds))
	builder.WriteString(", ")
	builder.WriteString("degraded_latency_ms=")
	builder.WriteString(fmt.Sprintf("%v", _m.DegradedLatencyMs))
	builder.WriteString(", ")
	builder.WriteString("failure_threshold=")
	builder.WriteString(fmt.Sprintf("%v", _m.FailureThreshold))
	builder.WriteString(", ")
	builder.WriteString("recovery_threshold=")
	builder.WriteString(fmt.Sprintf("%v", _m.RecoveryThreshold))
	builder.WriteString(", ")
	if v := _m.LastControlRunAt; v != nil {
		builder.WriteString("last_control_run_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastDataRunAt; v != nil {
		builder.WriteString("last_data_run_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Sub2APIProviderProbeConfigs is a parsable slice of Sub2APIProviderProbeConfig.
type Sub2APIProviderProbeConfigs []*Sub2APIProviderProbeConfig
