// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/sub2apiprovider"
)

// Sub2APIProviderDelete is the builder for deleting a Sub2APIProvider entity.
type Sub2APIProviderDelete struct {
	config
	hooks    []Hook
	mutation *Sub2APIProviderMutation
}

// Where appends a list predicates to the Sub2APIProviderDelete builder.
func (_d *Sub2APIProviderDelete) Where(ps ...predicate.Sub2APIProvider) *Sub2APIProviderDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *Sub2APIProviderDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *Sub2APIProviderDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *Sub2APIProviderDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(sub2apiprovider.Table, sqlgraph.NewFieldSpec(sub2apiprovider.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// Sub2APIProviderDeleteOne is the builder for deleting a single Sub2APIProvider entity.
type Sub2APIProviderDeleteOne struct {
	_d *Sub2APIProviderDelete
}

// Where appends a list predicates to the Sub2APIProviderDelete builder.
func (_d *Sub2APIProviderDeleteOne) Where(ps ...predicate.Sub2APIProvider) *Sub2APIProviderDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *Sub2APIProviderDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{sub2apiprovider.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *Sub2APIProviderDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
