// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/sub2apioptimizelog"
	"github.com/Wei-Shaw/sub2api/ent/sub2apioptimizeschedule"
	"github.com/Wei-Shaw/sub2api/ent/sub2apiprovider"
)

// Sub2APIOptimizeScheduleUpdate is the builder for updating Sub2APIOptimizeSchedule entities.
type Sub2APIOptimizeScheduleUpdate struct {
	config
	hooks    []Hook
	mutation *Sub2APIOptimizeScheduleMutation
}

// Where appends a list predicates to the Sub2APIOptimizeScheduleUpdate builder.
func (_u *Sub2APIOptimizeScheduleUpdate) Where(ps ...predicate.Sub2APIOptimizeSchedule) *Sub2APIOptimizeScheduleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *Sub2APIOptimizeScheduleUpdate) SetUpdatedAt(v time.Time) *Sub2APIOptimizeScheduleUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProviderID sets the "provider_id" field.
func (_u *Sub2APIOptimizeScheduleUpdate) SetProviderID(v int64) *Sub2APIOptimizeScheduleUpdate {
	_u.mutation.SetProviderID(v)
	return _u
}

// SetNillableProviderID sets the "provider_id" field if the given value is not nil.
func (_u *Sub2APIOptimizeScheduleUpdate) SetNillableProviderID(v *int64) *Sub2APIOptimizeScheduleUpdate {
	if v != nil {
		_u.SetProviderID(*v)
	}
	return _u
}

// SetCronExpr sets the "cron_expr" field.
func (_u *Sub2APIOptimizeScheduleUpdate) SetCronExpr(v string) *Sub2APIOptimizeScheduleUpdate {
	_u.mutation.SetCronExpr(v)
	return _u
}

// SetNillableCronExpr sets the "cron_expr" field if the given value is not nil.
func (_u *Sub2APIOptimizeScheduleUpdate) SetNillableCronExpr(v *string) *Sub2APIOptimizeScheduleUpdate {
	if v != nil {
		_u.SetCronExpr(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *Sub2APIOptimizeScheduleUpdate) SetEnabled(v bool) *Sub2APIOptimizeScheduleUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *Sub2APIOptimizeScheduleUpdate) SetNillableEnabled(v *bool) *Sub2APIOptimizeScheduleUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetLastRunAt sets the "last_run_at" field.
func (_u *Sub2APIOptimizeScheduleUpdate) SetLastRunAt(v time.Time) *Sub2APIOptimizeScheduleUpdate {
	_u.mutation.SetLastRunAt(v)
	return _u
}

// SetNillableLastRunAt sets the "last_run_at" field if the given value is not nil.
func (_u *Sub2APIOptimizeScheduleUpdate) SetNillableLastRunAt(v *time.Time) *Sub2APIOptimizeScheduleUpdate {
	if v != nil {
		_u.SetLastRunAt(*v)
	}
	return _u
}

// ClearLastRunAt clears the value of the "last_run_at" field.
func (_u *Sub2APIOptimizeScheduleUpdate) ClearLastRunAt() *Sub2APIOptimizeScheduleUpdate {
	_u.mutation.ClearLastRunAt()
	return _u
}

// SetNextRunAt sets the "next_run_at" field.
func (_u *Sub2APIOptimizeScheduleUpdate) SetNextRunAt(v time.Time) *Sub2APIOptimizeScheduleUpdate {
	_u.mutation.SetNextRunAt(v)
	return _u
}

// SetNillableNextRunAt sets the "next_run_at" field if the given value is not nil.
func (_u *Sub2APIOptimizeScheduleUpdate) SetNillableNextRunAt(v *time.Time) *Sub2APIOptimizeScheduleUpdate {
	if v != nil {
		_u.SetNextRunAt(*v)
	}
	return _u
}

// ClearNextRunAt clears the value of the "next_run_at" field.
func (_u *Sub2APIOptimizeScheduleUpdate) ClearNextRunAt() *Sub2APIOptimizeScheduleUpdate {
	_u.mutation.ClearNextRunAt()
	return _u
}

// SetProvider sets the "provider" edge to the Sub2APIProvider entity.
func (_u *Sub2APIOptimizeScheduleUpdate) SetProvider(v *Sub2APIProvider) *Sub2APIOptimizeScheduleUpdate {
	return _u.SetProviderID(v.ID)
}

// AddLogIDs adds the "logs" edge to the Sub2APIOptimizeLog entity by IDs.
func (_u *Sub2APIOptimizeScheduleUpdate) AddLogIDs(ids ...int64) *Sub2APIOptimizeScheduleUpdate {
	_u.mutation.AddLogIDs(ids...)
	return _u
}

// AddLogs adds the "logs" edges to the Sub2APIOptimizeLog entity.
func (_u *Sub2APIOptimizeScheduleUpdate) AddLogs(v ...*Sub2APIOptimizeLog) *Sub2APIOptimizeScheduleUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLogIDs(ids...)
}

// Mutation returns the Sub2APIOptimizeScheduleMutation object of the builder.
func (_u *Sub2APIOptimizeScheduleUpdate) Mutation() *Sub2APIOptimizeScheduleMutation {
	return _u.mutation
}

// ClearProvider clears the "provider" edge to the Sub2APIProvider entity.
func (_u *Sub2APIOptimizeScheduleUpdate) ClearProvider() *Sub2APIOptimizeScheduleUpdate {
	_u.mutation.ClearProvider()
	return _u
}

// ClearLogs clears all "logs" edges to the Sub2APIOptimizeLog entity.
func (_u *Sub2APIOptimizeScheduleUpdate) ClearLogs() *Sub2APIOptimizeScheduleUpdate {
	_u.mutation.ClearLogs()
	return _u
}

// RemoveLogIDs removes the "logs" edge to Sub2APIOptimizeLog entities by IDs.
func (_u *Sub2APIOptimizeScheduleUpdate) RemoveLogIDs(ids ...int64) *Sub2APIOptimizeScheduleUpdate {
	_u.mutation.RemoveLogIDs(ids...)
	return _u
}

// RemoveLogs removes "logs" edges to Sub2APIOptimizeLog entities.
func (_u *Sub2APIOptimizeScheduleUpdate) RemoveLogs(v ...*Sub2APIOptimizeLog) *Sub2APIOptimizeScheduleUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLogIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *Sub2APIOptimizeScheduleUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *Sub2APIOptimizeScheduleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *Sub2APIOptimizeScheduleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *Sub2APIOptimizeScheduleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *Sub2APIOptimizeScheduleUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := sub2apioptimizeschedule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *Sub2APIOptimizeScheduleUpdate) check() error {
	if v, ok := _u.mutation.CronExpr(); ok {
		if err := sub2apioptimizeschedule.CronExprValidator(v); err != nil {
			return &ValidationError{Name: "cron_expr", err: fmt.Errorf(`ent: validator failed for field "Sub2APIOptimizeSchedule.cron_expr": %w`, err)}
		}
	}
	if _u.mutation.ProviderCleared() && len(_u.mutation.ProviderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Sub2APIOptimizeSchedule.provider"`)
	}
	return nil
}

func (_u *Sub2APIOptimizeScheduleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sub2apioptimizeschedule.Table, sub2apioptimizeschedule.Columns, sqlgraph.NewFieldSpec(sub2apioptimizeschedule.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sub2apioptimizeschedule.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CronExpr(); ok {
		_spec.SetField(sub2apioptimizeschedule.FieldCronExpr, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(sub2apioptimizeschedule.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastRunAt(); ok {
		_spec.SetField(sub2apioptimizeschedule.FieldLastRunAt, field.TypeTime, value)
	}
	if _u.mutation.LastRunAtCleared() {
		_spec.ClearField(sub2apioptimizeschedule.FieldLastRunAt, field.TypeTime)
	}
	if value, ok := _u.mutation.NextRunAt(); ok {
		_spec.SetField(sub2apioptimizeschedule.FieldNextRunAt, field.TypeTime, value)
	}
	if _u.mutation.NextRunAtCleared() {
		_spec.ClearField(sub2apioptimizeschedule.FieldNextRunAt, field.TypeTime)
	}
	if _u.mutation.ProviderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   sub2apioptimizeschedule.ProviderTable,
			Columns: []string{sub2apioptimizeschedule.ProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sub2apiprovider.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProviderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   sub2apioptimizeschedule.ProviderTable,
			Columns: []string{sub2apioptimizeschedule.ProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sub2apiprovider.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sub2apioptimizeschedule.LogsTable,
			Columns: []string{sub2apioptimizeschedule.LogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sub2apioptimizelog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLogsIDs(); len(nodes) > 0 && !_u.mutation.LogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sub2apioptimizeschedule.LogsTable,
			Columns: []string{sub2apioptimizeschedule.LogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sub2apioptimizelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sub2apioptimizeschedule.LogsTable,
			Columns: []string{sub2apioptimizeschedule.LogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sub2apioptimizelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sub2apioptimizeschedule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// Sub2APIOptimizeScheduleUpdateOne is the builder for updating a single Sub2APIOptimizeSchedule entity.
type Sub2APIOptimizeScheduleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *Sub2APIOptimizeScheduleMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *Sub2APIOptimizeScheduleUpdateOne) SetUpdatedAt(v time.Time) *Sub2APIOptimizeScheduleUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProviderID sets the "provider_id" field.
func (_u *Sub2APIOptimizeScheduleUpdateOne) SetProviderID(v int64) *Sub2APIOptimizeScheduleUpdateOne {
	_u.mutation.SetProviderID(v)
	return _u
}

// SetNillableProviderID sets the "provider_id" field if the given value is not nil.
func (_u *Sub2APIOptimizeScheduleUpdateOne) SetNillableProviderID(v *int64) *Sub2APIOptimizeScheduleUpdateOne {
	if v != nil {
		_u.SetProviderID(*v)
	}
	return _u
}

// SetCronExpr sets the "cron_expr" field.
func (_u *Sub2APIOptimizeScheduleUpdateOne) SetCronExpr(v string) *Sub2APIOptimizeScheduleUpdateOne {
	_u.mutation.SetCronExpr(v)
	return _u
}

// SetNillableCronExpr sets the "cron_expr" field if the given value is not nil.
func (_u *Sub2APIOptimizeScheduleUpdateOne) SetNillableCronExpr(v *string) *Sub2APIOptimizeScheduleUpdateOne {
	if v != nil {
		_u.SetCronExpr(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *Sub2APIOptimizeScheduleUpdateOne) SetEnabled(v bool) *Sub2APIOptimizeScheduleUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *Sub2APIOptimizeScheduleUpdateOne) SetNillableEnabled(v *bool) *Sub2APIOptimizeScheduleUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetLastRunAt sets the "last_run_at" field.
func (_u *Sub2APIOptimizeScheduleUpdateOne) SetLastRunAt(v time.Time) *Sub2APIOptimizeScheduleUpdateOne {
	_u.mutation.SetLastRunAt(v)
	return _u
}

// SetNillableLastRunAt sets the "last_run_at" field if the given value is not nil.
func (_u *Sub2APIOptimizeScheduleUpdateOne) SetNillableLastRunAt(v *time.Time) *Sub2APIOptimizeScheduleUpdateOne {
	if v != nil {
		_u.SetLastRunAt(*v)
	}
	return _u
}

// ClearLastRunAt clears the value of the "last_run_at" field.
func (_u *Sub2APIOptimizeScheduleUpdateOne) ClearLastRunAt() *Sub2APIOptimizeScheduleUpdateOne {
	_u.mutation.ClearLastRunAt()
	return _u
}

// SetNextRunAt sets the "next_run_at" field.
func (_u *Sub2APIOptimizeScheduleUpdateOne) SetNextRunAt(v time.Time) *Sub2APIOptimizeScheduleUpdateOne {
	_u.mutation.SetNextRunAt(v)
	return _u
}

// SetNillableNextRunAt sets the "next_run_at" field if the given value is not nil.
func (_u *Sub2APIOptimizeScheduleUpdateOne) SetNillableNextRunAt(v *time.Time) *Sub2APIOptimizeScheduleUpdateOne {
	if v != nil {
		_u.SetNextRunAt(*v)
	}
	return _u
}

// ClearNextRunAt clears the value of the "next_run_at" field.
func (_u *Sub2APIOptimizeScheduleUpdateOne) ClearNextRunAt() *Sub2APIOptimizeScheduleUpdateOne {
	_u.mutation.ClearNextRunAt()
	return _u
}

// SetProvider sets the "provider" edge to the Sub2APIProvider entity.
func (_u *Sub2APIOptimizeScheduleUpdateOne) SetProvider(v *Sub2APIProvider) *Sub2APIOptimizeScheduleUpdateOne {
	return _u.SetProviderID(v.ID)
}

// AddLogIDs adds the "logs" edge to the Sub2APIOptimizeLog entity by IDs.
func (_u *Sub2APIOptimizeScheduleUpdateOne) AddLogIDs(ids ...int64) *Sub2APIOptimizeScheduleUpdateOne {
	_u.mutation.AddLogIDs(ids...)
	return _u
}

// AddLogs adds the "logs" edges to the Sub2APIOptimizeLog entity.
func (_u *Sub2APIOptimizeScheduleUpdateOne) AddLogs(v ...*Sub2APIOptimizeLog) *Sub2APIOptimizeScheduleUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLogIDs(ids...)
}

// Mutation returns the Sub2APIOptimizeScheduleMutation object of the builder.
func (_u *Sub2APIOptimizeScheduleUpdateOne) Mutation() *Sub2APIOptimizeScheduleMutation {
	return _u.mutation
}

// ClearProvider clears the "provider" edge to the Sub2APIProvider entity.
func (_u *Sub2APIOptimizeScheduleUpdateOne) ClearProvider() *Sub2APIOptimizeScheduleUpdateOne {
	_u.mutation.ClearProvider()
	return _u
}

// ClearLogs clears all "logs" edges to the Sub2APIOptimizeLog entity.
func (_u *Sub2APIOptimizeScheduleUpdateOne) ClearLogs() *Sub2APIOptimizeScheduleUpdateOne {
	_u.mutation.ClearLogs()
	return _u
}

// RemoveLogIDs removes the "logs" edge to Sub2APIOptimizeLog entities by IDs.
func (_u *Sub2APIOptimizeScheduleUpdateOne) RemoveLogIDs(ids ...int64) *Sub2APIOptimizeScheduleUpdateOne {
	_u.mutation.RemoveLogIDs(ids...)
	return _u
}

// RemoveLogs removes "logs" edges to Sub2APIOptimizeLog entities.
func (_u *Sub2APIOptimizeScheduleUpdateOne) RemoveLogs(v ...*Sub2APIOptimizeLog) *Sub2APIOptimizeScheduleUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLogIDs(ids...)
}

// Where appends a list predicates to the Sub2APIOptimizeScheduleUpdate builder.
func (_u *Sub2APIOptimizeScheduleUpdateOne) Where(ps ...predicate.Sub2APIOptimizeSchedule) *Sub2APIOptimizeScheduleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *Sub2APIOptimizeScheduleUpdateOne) Select(field string, fields ...string) *Sub2APIOptimizeScheduleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Sub2APIOptimizeSchedule entity.
func (_u *Sub2APIOptimizeScheduleUpdateOne) Save(ctx context.Context) (*Sub2APIOptimizeSchedule, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *Sub2APIOptimizeScheduleUpdateOne) SaveX(ctx context.Context) *Sub2APIOptimizeSchedule {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *Sub2APIOptimizeScheduleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *Sub2APIOptimizeScheduleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *Sub2APIOptimizeScheduleUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := sub2apioptimizeschedule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *Sub2APIOptimizeScheduleUpdateOne) check() error {
	if v, ok := _u.mutation.CronExpr(); ok {
		if err := sub2apioptimizeschedule.CronExprValidator(v); err != nil {
			return &ValidationError{Name: "cron_expr", err: fmt.Errorf(`ent: validator failed for field "Sub2APIOptimizeSchedule.cron_expr": %w`, err)}
		}
	}
	if _u.mutation.ProviderCleared() && len(_u.mutation.ProviderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Sub2APIOptimizeSchedule.provider"`)
	}
	return nil
}

func (_u *Sub2APIOptimizeScheduleUpdateOne) sqlSave(ctx context.Context) (_node *Sub2APIOptimizeSchedule, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sub2apioptimizeschedule.Table, sub2apioptimizeschedule.Columns, sqlgraph.NewFieldSpec(sub2apioptimizeschedule.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Sub2APIOptimizeSchedule.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sub2apioptimizeschedule.FieldID)
		for _, f := range fields {
			if !sub2apioptimizeschedule.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sub2apioptimizeschedule.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sub2apioptimizeschedule.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CronExpr(); ok {
		_spec.SetField(sub2apioptimizeschedule.FieldCronExpr, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(sub2apioptimizeschedule.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastRunAt(); ok {
		_spec.SetField(sub2apioptimizeschedule.FieldLastRunAt, field.TypeTime, value)
	}
	if _u.mutation.LastRunAtCleared() {
		_spec.ClearField(sub2apioptimizeschedule.FieldLastRunAt, field.TypeTime)
	}
	if value, ok := _u.mutation.NextRunAt(); ok {
		_spec.SetField(sub2apioptimizeschedule.FieldNextRunAt, field.TypeTime, value)
	}
	if _u.mutation.NextRunAtCleared() {
		_spec.ClearField(sub2apioptimizeschedule.FieldNextRunAt, field.TypeTime)
	}
	if _u.mutation.ProviderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   sub2apioptimizeschedule.ProviderTable,
			Columns: []string{sub2apioptimizeschedule.ProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sub2apiprovider.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProviderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   sub2apioptimizeschedule.ProviderTable,
			Columns: []string{sub2apioptimizeschedule.ProviderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sub2apiprovider.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sub2apioptimizeschedule.LogsTable,
			Columns: []string{sub2apioptimizeschedule.LogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sub2apioptimizelog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLogsIDs(); len(nodes) > 0 && !_u.mutation.LogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sub2apioptimizeschedule.LogsTable,
			Columns: []string{sub2apioptimizeschedule.LogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sub2apioptimizelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sub2apioptimizeschedule.LogsTable,
			Columns: []string{sub2apioptimizeschedule.LogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sub2apioptimizelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Sub2APIOptimizeSchedule{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sub2apioptimizeschedule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
