// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/sub2apioptimizeschedule"
	"github.com/Wei-Shaw/sub2api/ent/sub2apiprovider"
)

// Sub2APIOptimizeSchedule is the model entity for the Sub2APIOptimizeSchedule schema.
type Sub2APIOptimizeSchedule struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 关联的上游 Provider ID
	ProviderID int64 `json:"provider_id,omitempty"`
	// cron 表达式，如 */30 * * * *
	CronExpr string `json:"cron_expr,omitempty"`
	// 是否启用
	Enabled bool `json:"enabled,omitempty"`
	// 上次执行时间
	LastRunAt *time.Time `json:"last_run_at,omitempty"`
	// 下次执行时间
	NextRunAt *time.Time `json:"next_run_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the Sub2APIOptimizeScheduleQuery when eager-loading is set.
	Edges        Sub2APIOptimizeScheduleEdges `json:"edges"`
	selectValues sql.SelectValues
}

// Sub2APIOptimizeScheduleEdges holds the relations/edges for other nodes in the graph.
type Sub2APIOptimizeScheduleEdges struct {
	// Provider holds the value of the provider edge.
	Provider *Sub2APIProvider `json:"provider,omitempty"`
	// Logs holds the value of the logs edge.
	Logs []*Sub2APIOptimizeLog `json:"logs,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ProviderOrErr returns the Provider value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e Sub2APIOptimizeScheduleEdges) ProviderOrErr() (*Sub2APIProvider, error) {
	if e.Provider != nil {
		return e.Provider, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: sub2apiprovider.Label}
	}
	return nil, &NotLoadedError{edge: "provider"}
}

// LogsOrErr returns the Logs value or an error if the edge
// was not loaded in eager-loading.
func (e Sub2APIOptimizeScheduleEdges) LogsOrErr() ([]*Sub2APIOptimizeLog, error) {
	if e.loadedTypes[1] {
		return e.Logs, nil
	}
	return nil, &NotLoadedError{edge: "logs"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Sub2APIOptimizeSchedule) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case sub2apioptimizeschedule.FieldEnabled:
			values[i] = new(sql.NullBool)
		case sub2apioptimizeschedule.FieldID, sub2apioptimizeschedule.FieldProviderID:
			values[i] = new(sql.NullInt64)
		case sub2apioptimizeschedule.FieldCronExpr:
			values[i] = new(sql.NullString)
		case sub2apioptimizeschedule.FieldCreatedAt, sub2apioptimizeschedule.FieldUpdatedAt, sub2apioptimizeschedule.FieldLastRunAt, sub2apioptimizeschedule.FieldNextRunAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Sub2APIOptimizeSchedule fields.
func (_m *Sub2APIOptimizeSchedule) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case sub2apioptimizeschedule.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case sub2apioptimizeschedule.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case sub2apioptimizeschedule.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case sub2apioptimizeschedule.FieldProviderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field provider_id", values[i])
			} else if value.Valid {
				_m.ProviderID = value.Int64
			}
		case sub2apioptimizeschedule.FieldCronExpr:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cron_expr", values[i])
			} else if value.Valid {
				_m.CronExpr = value.String
			}
		case sub2apioptimizeschedule.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case sub2apioptimizeschedule.FieldLastRunAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_run_at", values[i])
			} else if value.Valid {
				_m.LastRunAt = new(time.Time)
				*_m.LastRunAt = value.Time
			}
		case sub2apioptimizeschedule.FieldNextRunAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field next_run_at", values[i])
			} else if value.Valid {
				_m.NextRunAt = new(time.Time)
				*_m.NextRunAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Sub2APIOptimizeSchedule.
// This includes values selected through modifiers, order, etc.
func (_m *Sub2APIOptimizeSchedule) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProvider queries the "provider" edge of the Sub2APIOptimizeSchedule entity.
func (_m *Sub2APIOptimizeSchedule) QueryProvider() *Sub2APIProviderQuery {
	return NewSub2APIOptimizeScheduleClient(_m.config).QueryProvider(_m)
}

// QueryLogs queries the "logs" edge of the Sub2APIOptimizeSchedule entity.
func (_m *Sub2APIOptimizeSchedule) QueryLogs() *Sub2APIOptimizeLogQuery {
	return NewSub2APIOptimizeScheduleClient(_m.config).QueryLogs(_m)
}

// Update returns a builder for updating this Sub2APIOptimizeSchedule.
// Note that you need to call Sub2APIOptimizeSchedule.Unwrap() before calling this method if this Sub2APIOptimizeSchedule
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Sub2APIOptimizeSchedule) Update() *Sub2APIOptimizeScheduleUpdateOne {
	return NewSub2APIOptimizeScheduleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Sub2APIOptimizeSchedule entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Sub2APIOptimizeSchedule) Unwrap() *Sub2APIOptimizeSchedule {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Sub2APIOptimizeSchedule is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Sub2APIOptimizeSchedule) String() string {
	var builder strings.Builder
	builder.WriteString("Sub2APIOptimizeSchedule(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("provider_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProviderID))
	builder.WriteString(", ")
	builder.WriteString("cron_expr=")
	builder.WriteString(_m.CronExpr)
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	if v := _m.LastRunAt; v != nil {
		builder.WriteString("last_run_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.NextRunAt; v != nil {
		builder.WriteString("next_run_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Sub2APIOptimizeSchedules is a parsable slice of Sub2APIOptimizeSchedule.
type Sub2APIOptimizeSchedules []*Sub2APIOptimizeSchedule
