// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/proxy"
	"github.com/Wei-Shaw/sub2api/ent/sub2apioptimizelog"
	"github.com/Wei-Shaw/sub2api/ent/sub2apioptimizeschedule"
	"github.com/Wei-Shaw/sub2api/ent/sub2apiprovider"
	"github.com/Wei-Shaw/sub2api/ent/sub2apiproviderprobeconfig"
	"github.com/Wei-Shaw/sub2api/ent/sub2apiproviderproberun"
	"github.com/Wei-Shaw/sub2api/ent/sub2apiproviderprobetarget"
)

// Sub2APIProviderCreate is the builder for creating a Sub2APIProvider entity.
type Sub2APIProviderCreate struct {
	config
	mutation *Sub2APIProviderMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *Sub2APIProviderCreate) SetCreatedAt(v time.Time) *Sub2APIProviderCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *Sub2APIProviderCreate) SetNillableCreatedAt(v *time.Time) *Sub2APIProviderCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *Sub2APIProviderCreate) SetUpdatedAt(v time.Time) *Sub2APIProviderCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *Sub2APIProviderCreate) SetNillableUpdatedAt(v *time.Time) *Sub2APIProviderCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *Sub2APIProviderCreate) SetDeletedAt(v time.Time) *Sub2APIProviderCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *Sub2APIProviderCreate) SetNillableDeletedAt(v *time.Time) *Sub2APIProviderCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *Sub2APIProviderCreate) SetName(v string) *Sub2APIProviderCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetBaseURL sets the "base_url" field.
func (_c *Sub2APIProviderCreate) SetBaseURL(v string) *Sub2APIProviderCreate {
	_c.mutation.SetBaseURL(v)
	return _c
}

// SetProviderType sets the "provider_type" field.
func (_c *Sub2APIProviderCreate) SetProviderType(v string) *Sub2APIProviderCreate {
	_c.mutation.SetProviderType(v)
	return _c
}

// SetNillableProviderType sets the "provider_type" field if the given value is not nil.
func (_c *Sub2APIProviderCreate) SetNillableProviderType(v *string) *Sub2APIProviderCreate {
	if v != nil {
		_c.SetProviderType(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *Sub2APIProviderCreate) SetStatus(v string) *Sub2APIProviderCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *Sub2APIProviderCreate) SetNillableStatus(v *string) *Sub2APIProviderCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *Sub2APIProviderCreate) SetNotes(v string) *Sub2APIProviderCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *Sub2APIProviderCreate) SetNillableNotes(v *string) *Sub2APIProviderCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetProxyID sets the "proxy_id" field.
func (_c *Sub2APIProviderCreate) SetProxyID(v int64) *Sub2APIProviderCreate {
	_c.mutation.SetProxyID(v)
	return _c
}

// SetNillableProxyID sets the "proxy_id" field if the given value is not nil.
func (_c *Sub2APIProviderCreate) SetNillableProxyID(v *int64) *Sub2APIProviderCreate {
	if v != nil {
		_c.SetProxyID(*v)
	}
	return _c
}

// SetEmail sets the "email" field.
func (_c *Sub2APIProviderCreate) SetEmail(v string) *Sub2APIProviderCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetPasswordEncrypted sets the "password_encrypted" field.
func (_c *Sub2APIProviderCreate) SetPasswordEncrypted(v string) *Sub2APIProviderCreate {
	_c.mutation.SetPasswordEncrypted(v)
	return _c
}

// SetNillablePasswordEncrypted sets the "password_encrypted" field if the given value is not nil.
func (_c *Sub2APIProviderCreate) SetNillablePasswordEncrypted(v *string) *Sub2APIProviderCreate {
	if v != nil {
		_c.SetPasswordEncrypted(*v)
	}
	return _c
}

// SetAuthMode sets the "auth_mode" field.
func (_c *Sub2APIProviderCreate) SetAuthMode(v string) *Sub2APIProviderCreate {
	_c.mutation.SetAuthMode(v)
	return _c
}

// SetNillableAuthMode sets the "auth_mode" field if the given value is not nil.
func (_c *Sub2APIProviderCreate) SetNillableAuthMode(v *string) *Sub2APIProviderCreate {
	if v != nil {
		_c.SetAuthMode(*v)
	}
	return _c
}

// SetAccessTokenEncrypted sets the "access_token_encrypted" field.
func (_c *Sub2APIProviderCreate) SetAccessTokenEncrypted(v string) *Sub2APIProviderCreate {
	_c.mutation.SetAccessTokenEncrypted(v)
	return _c
}

// SetNillableAccessTokenEncrypted sets the "access_token_encrypted" field if the given value is not nil.
func (_c *Sub2APIProviderCreate) SetNillableAccessTokenEncrypted(v *string) *Sub2APIProviderCreate {
	if v != nil {
		_c.SetAccessTokenEncrypted(*v)
	}
	return _c
}

// SetRefreshTokenEncrypted sets the "refresh_token_encrypted" field.
func (_c *Sub2APIProviderCreate) SetRefreshTokenEncrypted(v string) *Sub2APIProviderCreate {
	_c.mutation.SetRefreshTokenEncrypted(v)
	return _c
}

// SetNillableRefreshTokenEncrypted sets the "refresh_token_encrypted" field if the given value is not nil.
func (_c *Sub2APIProviderCreate) SetNillableRefreshTokenEncrypted(v *string) *Sub2APIProviderCreate {
	if v != nil {
		_c.SetRefreshTokenEncrypted(*v)
	}
	return _c
}

// SetAccessTokenExpiresAt sets the "access_token_expires_at" field.
func (_c *Sub2APIProviderCreate) SetAccessTokenExpiresAt(v time.Time) *Sub2APIProviderCreate {
	_c.mutation.SetAccessTokenExpiresAt(v)
	return _c
}

// SetNillableAccessTokenExpiresAt sets the "access_token_expires_at" field if the given value is not nil.
func (_c *Sub2APIProviderCreate) SetNillableAccessTokenExpiresAt(v *time.Time) *Sub2APIProviderCreate {
	if v != nil {
		_c.SetAccessTokenExpiresAt(*v)
	}
	return _c
}

// SetLastTokenRefreshAt sets the "last_token_refresh_at" field.
func (_c *Sub2APIProviderCreate) SetLastTokenRefreshAt(v time.Time) *Sub2APIProviderCreate {
	_c.mutation.SetLastTokenRefreshAt(v)
	return _c
}

// SetNillableLastTokenRefreshAt sets the "last_token_refresh_at" field if the given value is not nil.
func (_c *Sub2APIProviderCreate) SetNillableLastTokenRefreshAt(v *time.Time) *Sub2APIProviderCreate {
	if v != nil {
		_c.SetLastTokenRefreshAt(*v)
	}
	return _c
}

// SetLastAuthError sets the "last_auth_error" field.
func (_c *Sub2APIProviderCreate) SetLastAuthError(v string) *Sub2APIProviderCreate {
	_c.mutation.SetLastAuthError(v)
	return _c
}

// SetNillableLastAuthError sets the "last_auth_error" field if the given value is not nil.
func (_c *Sub2APIProviderCreate) SetNillableLastAuthError(v *string) *Sub2APIProviderCreate {
	if v != nil {
		_c.SetLastAuthError(*v)
	}
	return _c
}

// SetAPIPathKeys sets the "api_path_keys" field.
func (_c *Sub2APIProviderCreate) SetAPIPathKeys(v string) *Sub2APIProviderCreate {
	_c.mutation.SetAPIPathKeys(v)
	return _c
}

// SetNillableAPIPathKeys sets the "api_path_keys" field if the given value is not nil.
func (_c *Sub2APIProviderCreate) SetNillableAPIPathKeys(v *string) *Sub2APIProviderCreate {
	if v != nil {
		_c.SetAPIPathKeys(*v)
	}
	return _c
}

// SetAPIPathGroups sets the "api_path_groups" field.
func (_c *Sub2APIProviderCreate) SetAPIPathGroups(v string) *Sub2APIProviderCreate {
	_c.mutation.SetAPIPathGroups(v)
	return _c
}

// SetNillableAPIPathGroups sets the "api_path_groups" field if the given value is not nil.
func (_c *Sub2APIProviderCreate) SetNillableAPIPathGroups(v *string) *Sub2APIProviderCreate {
	if v != nil {
		_c.SetAPIPathGroups(*v)
	}
	return _c
}

// SetLastSyncAt sets the "last_sync_at" field.
func (_c *Sub2APIProviderCreate) SetLastSyncAt(v time.Time) *Sub2APIProviderCreate {
	_c.mutation.SetLastSyncAt(v)
	return _c
}

// SetNillableLastSyncAt sets the "last_sync_at" field if the given value is not nil.
func (_c *Sub2APIProviderCreate) SetNillableLastSyncAt(v *time.Time) *Sub2APIProviderCreate {
	if v != nil {
		_c.SetLastSyncAt(*v)
	}
	return _c
}

// SetLastSyncStatus sets the "last_sync_status" field.
func (_c *Sub2APIProviderCreate) SetLastSyncStatus(v string) *Sub2APIProviderCreate {
	_c.mutation.SetLastSyncStatus(v)
	return _c
}

// SetNillableLastSyncStatus sets the "last_sync_status" field if the given value is not nil.
func (_c *Sub2APIProviderCreate) SetNillableLastSyncStatus(v *string) *Sub2APIProviderCreate {
	if v != nil {
		_c.SetLastSyncStatus(*v)
	}
	return _c
}

// SetLastSyncError sets the "last_sync_error" field.
func (_c *Sub2APIProviderCreate) SetLastSyncError(v string) *Sub2APIProviderCreate {
	_c.mutation.SetLastSyncError(v)
	return _c
}

// SetNillableLastSyncError sets the "last_sync_error" field if the given value is not nil.
func (_c *Sub2APIProviderCreate) SetNillableLastSyncError(v *string) *Sub2APIProviderCreate {
	if v != nil {
		_c.SetLastSyncError(*v)
	}
	return _c
}

// SetProxy sets the "proxy" edge to the Proxy entity.
func (_c *Sub2APIProviderCreate) SetProxy(v *Proxy) *Sub2APIProviderCreate {
	return _c.SetProxyID(v.ID)
}

// AddAccountIDs adds the "accounts" edge to the Account entity by IDs.
func (_c *Sub2APIProviderCreate) AddAccountIDs(ids ...int64) *Sub2APIProviderCreate {
	_c.mutation.AddAccountIDs(ids...)
	return _c
}

// AddAccounts adds the "accounts" edges to the Account entity.
func (_c *Sub2APIProviderCreate) AddAccounts(v ...*Account) *Sub2APIProviderCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAccountIDs(ids...)
}

// SetOptimizeScheduleID sets the "optimize_schedule" edge to the Sub2APIOptimizeSchedule entity by ID.
func (_c *Sub2APIProviderCreate) SetOptimizeScheduleID(id int64) *Sub2APIProviderCreate {
	_c.mutation.SetOptimizeScheduleID(id)
	return _c
}

// SetNillableOptimizeScheduleID sets the "optimize_schedule" edge to the Sub2APIOptimizeSchedule entity by ID if the given value is not nil.
func (_c *Sub2APIProviderCreate) SetNillableOptimizeScheduleID(id *int64) *Sub2APIProviderCreate {
	if id != nil {
		_c = _c.SetOptimizeScheduleID(*id)
	}
	return _c
}

// SetOptimizeSchedule sets the "optimize_schedule" edge to the Sub2APIOptimizeSchedule entity.
func (_c *Sub2APIProviderCreate) SetOptimizeSchedule(v *Sub2APIOptimizeSchedule) *Sub2APIProviderCreate {
	return _c.SetOptimizeScheduleID(v.ID)
}

// AddOptimizeLogIDs adds the "optimize_logs" edge to the Sub2APIOptimizeLog entity by IDs.
func (_c *Sub2APIProviderCreate) AddOptimizeLogIDs(ids ...int64) *Sub2APIProviderCreate {
	_c.mutation.AddOptimizeLogIDs(ids...)
	return _c
}

// AddOptimizeLogs adds the "optimize_logs" edges to the Sub2APIOptimizeLog entity.
func (_c *Sub2APIProviderCreate) AddOptimizeLogs(v ...*Sub2APIOptimizeLog) *Sub2APIProviderCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddOptimizeLogIDs(ids...)
}

// SetProbeConfigID sets the "probe_config" edge to the Sub2APIProviderProbeConfig entity by ID.
func (_c *Sub2APIProviderCreate) SetProbeConfigID(id int64) *Sub2APIProviderCreate {
	_c.mutation.SetProbeConfigID(id)
	return _c
}

// SetNillableProbeConfigID sets the "probe_config" edge to the Sub2APIProviderProbeConfig entity by ID if the given value is not nil.
func (_c *Sub2APIProviderCreate) SetNillableProbeConfigID(id *int64) *Sub2APIProviderCreate {
	if id != nil {
		_c = _c.SetProbeConfigID(*id)
	}
	return _c
}

// SetProbeConfig sets the "probe_config" edge to the Sub2APIProviderProbeConfig entity.
func (_c *Sub2APIProviderCreate) SetProbeConfig(v *Sub2APIProviderProbeConfig) *Sub2APIProviderCreate {
	return _c.SetProbeConfigID(v.ID)
}

// AddProbeRunIDs adds the "probe_runs" edge to the Sub2APIProviderProbeRun entity by IDs.
func (_c *Sub2APIProviderCreate) AddProbeRunIDs(ids ...int64) *Sub2APIProviderCreate {
	_c.mutation.AddProbeRunIDs(ids...)
	return _c
}

// AddProbeRuns adds the "probe_runs" edges to the Sub2APIProviderProbeRun entity.
func (_c *Sub2APIProviderCreate) AddProbeRuns(v ...*Sub2APIProviderProbeRun) *Sub2APIProviderCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddProbeRunIDs(ids...)
}

// AddProbeTargetIDs adds the "probe_targets" edge to the Sub2APIProviderProbeTarget entity by IDs.
func (_c *Sub2APIProviderCreate) AddProbeTargetIDs(ids ...int64) *Sub2APIProviderCreate {
	_c.mutation.AddProbeTargetIDs(ids...)
	return _c
}

// AddProbeTargets adds the "probe_targets" edges to the Sub2APIProviderProbeTarget entity.
func (_c *Sub2APIProviderCreate) AddProbeTargets(v ...*Sub2APIProviderProbeTarget) *Sub2APIProviderCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddProbeTargetIDs(ids...)
}

// Mutation returns the Sub2APIProviderMutation object of the builder.
func (_c *Sub2APIProviderCreate) Mutation() *Sub2APIProviderMutation {
	return _c.mutation
}

// Save creates the Sub2APIProvider in the database.
func (_c *Sub2APIProviderCreate) Save(ctx context.Context) (*Sub2APIProvider, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *Sub2APIProviderCreate) SaveX(ctx context.Context) *Sub2APIProvider {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *Sub2APIProviderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *Sub2APIProviderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *Sub2APIProviderCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if sub2apiprovider.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized sub2apiprovider.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := sub2apiprovider.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if sub2apiprovider.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized sub2apiprovider.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := sub2apiprovider.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ProviderType(); !ok {
		v := sub2apiprovider.DefaultProviderType
		_c.mutation.SetProviderType(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := sub2apiprovider.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.PasswordEncrypted(); !ok {
		v := sub2apiprovider.DefaultPasswordEncrypted
		_c.mutation.SetPasswordEncrypted(v)
	}
	if _, ok := _c.mutation.AuthMode(); !ok {
		v := sub2apiprovider.DefaultAuthMode
		_c.mutation.SetAuthMode(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *Sub2APIProviderCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Sub2APIProvider.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Sub2APIProvider.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Sub2APIProvider.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := sub2apiprovider.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Sub2APIProvider.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BaseURL(); !ok {
		return &ValidationError{Name: "base_url", err: errors.New(`ent: missing required field "Sub2APIProvider.base_url"`)}
	}
	if v, ok := _c.mutation.BaseURL(); ok {
		if err := sub2apiprovider.BaseURLValidator(v); err != nil {
			return &ValidationError{Name: "base_url", err: fmt.Errorf(`ent: validator failed for field "Sub2APIProvider.base_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProviderType(); !ok {
		return &ValidationError{Name: "provider_type", err: errors.New(`ent: missing required field "Sub2APIProvider.provider_type"`)}
	}
	if v, ok := _c.mutation.ProviderType(); ok {
		if err := sub2apiprovider.ProviderTypeValidator(v); err != nil {
			return &ValidationError{Name: "provider_type", err: fmt.Errorf(`ent: validator failed for field "Sub2APIProvider.provider_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Sub2APIProvider.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := sub2apiprovider.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Sub2APIProvider.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "Sub2APIProvider.email"`)}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := sub2apiprovider.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Sub2APIProvider.email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PasswordEncrypted(); !ok {
		return &ValidationError{Name: "password_encrypted", err: errors.New(`ent: missing required field "Sub2APIProvider.password_encrypted"`)}
	}
	if _, ok := _c.mutation.AuthMode(); !ok {
		return &ValidationError{Name: "auth_mode", err: errors.New(`ent: missing required field "Sub2APIProvider.auth_mode"`)}
	}
	if v, ok := _c.mutation.AuthMode(); ok {
		if err := sub2apiprovider.AuthModeValidator(v); err != nil {
			return &ValidationError{Name: "auth_mode", err: fmt.Errorf(`ent: validator failed for field "Sub2APIProvider.auth_mode": %w`, err)}
		}
	}
	if v, ok := _c.mutation.APIPathKeys(); ok {
		if err := sub2apiprovider.APIPathKeysValidator(v); err != nil {
			return &ValidationError{Name: "api_path_keys", err: fmt.Errorf(`ent: validator failed for field "Sub2APIProvider.api_path_keys": %w`, err)}
		}
	}
	if v, ok := _c.mutation.APIPathGroups(); ok {
		if err := sub2apiprovider.APIPathGroupsValidator(v); err != nil {
			return &ValidationError{Name: "api_path_groups", err: fmt.Errorf(`ent: validator failed for field "Sub2APIProvider.api_path_groups": %w`, err)}
		}
	}
	if v, ok := _c.mutation.LastSyncStatus(); ok {
		if err := sub2apiprovider.LastSyncStatusValidator(v); err != nil {
			return &ValidationError{Name: "last_sync_status", err: fmt.Errorf(`ent: validator failed for field "Sub2APIProvider.last_sync_status": %w`, err)}
		}
	}
	return nil
}

func (_c *Sub2APIProviderCreate) sqlSave(ctx context.Context) (*Sub2APIProvider, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *Sub2APIProviderCreate) createSpec() (*Sub2APIProvider, *sqlgraph.CreateSpec) {
	var (
		_node = &Sub2APIProvider{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(sub2apiprovider.Table, sqlgraph.NewFieldSpec(sub2apiprovider.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(sub2apiprovider.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(sub2apiprovider.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(sub2apiprovider.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(sub2apiprovider.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.BaseURL(); ok {
		_spec.SetField(sub2apiprovider.FieldBaseURL, field.TypeString, value)
		_node.BaseURL = value
	}
	if value, ok := _c.mutation.ProviderType(); ok {
		_spec.SetField(sub2apiprovider.FieldProviderType, field.TypeString, value)
		_node.ProviderType = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(sub2apiprovider.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(sub2apiprovider.FieldNotes, field.TypeString, value)
		_node.Notes = &value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(sub2apiprovider.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.PasswordEncrypted(); ok {
		_spec.SetField(sub2apiprovider.FieldPasswordEncrypted, field.TypeString, value)
		_node.PasswordEncrypted = value
	}
	if value, ok := _c.mutation.AuthMode(); ok {
		_spec.SetField(sub2apiprovider.FieldAuthMode, field.TypeString, value)
		_node.AuthMode = value
	}
	if value, ok := _c.mutation.AccessTokenEncrypted(); ok {
		_spec.SetField(sub2apiprovider.FieldAccessTokenEncrypted, field.TypeString, value)
		_node.AccessTokenEncrypted = &value
	}
	if value, ok := _c.mutation.RefreshTokenEncrypted(); ok {
		_spec.SetField(sub2apiprovider.FieldRefreshTokenEncrypted, field.TypeString, value)
		_node.RefreshTokenEncrypted = &value
	}
	if value, ok := _c.mutation.AccessTokenExpiresAt(); ok {
		_spec.SetField(sub2apiprovider.FieldAccessTokenExpiresAt, field.TypeTime, value)
		_node.AccessTokenExpiresAt = &value
	}
	if value, ok := _c.mutation.LastTokenRefreshAt(); ok {
		_spec.SetField(sub2apiprovider.FieldLastTokenRefreshAt, field.TypeTime, value)
		_node.LastTokenRefreshAt = &value
	}
	if value, ok := _c.mutation.LastAuthError(); ok {
		_spec.SetField(sub2apiprovider.FieldLastAuthError, field.TypeString, value)
		_node.LastAuthError = &value
	}
	if value, ok := _c.mutation.APIPathKeys(); ok {
		_spec.SetField(sub2apiprovider.FieldAPIPathKeys, field.TypeString, value)
		_node.APIPathKeys = &value
	}
	if value, ok := _c.mutation.APIPathGroups(); ok {
		_spec.SetField(sub2apiprovider.FieldAPIPathGroups, field.TypeString, value)
		_node.APIPathGroups = &value
	}
	if value, ok := _c.mutation.LastSyncAt(); ok {
		_spec.SetField(sub2apiprovider.FieldLastSyncAt, field.TypeTime, value)
		_node.LastSyncAt = &value
	}
	if value, ok := _c.mutation.LastSyncStatus(); ok {
		_spec.SetField(sub2apiprovider.FieldLastSyncStatus, field.TypeString, value)
		_node.LastSyncStatus = &value
	}
	if value, ok := _c.mutation.LastSyncError(); ok {
		_spec.SetField(sub2apiprovider.FieldLastSyncError, field.TypeString, value)
		_node.LastSyncError = &value
	}
	if nodes := _c.mutation.ProxyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   sub2apiprovider.ProxyTable,
			Columns: []string{sub2apiprovider.ProxyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProxyID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sub2apiprovider.AccountsTable,
			Columns: []string{sub2apiprovider.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.OptimizeScheduleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   sub2apiprovider.OptimizeScheduleTable,
			Columns: []string{sub2apiprovider.OptimizeScheduleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sub2apioptimizeschedule.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.OptimizeLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sub2apiprovider.OptimizeLogsTable,
			Columns: []string{sub2apiprovider.OptimizeLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sub2apioptimizelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ProbeConfigIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   sub2apiprovider.ProbeConfigTable,
			Columns: []string{sub2apiprovider.ProbeConfigColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sub2apiproviderprobeconfig.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ProbeRunsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sub2apiprovider.ProbeRunsTable,
			Columns: []string{sub2apiprovider.ProbeRunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sub2apiproviderproberun.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ProbeTargetsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sub2apiprovider.ProbeTargetsTable,
			Columns: []string{sub2apiprovider.ProbeTargetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sub2apiproviderprobetarget.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Sub2APIProvider.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.Sub2APIProviderUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *Sub2APIProviderCreate) OnConflict(opts ...sql.ConflictOption) *Sub2APIProviderUpsertOne {
	_c.conflict = opts
	return &Sub2APIProviderUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Sub2APIProvider.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *Sub2APIProviderCreate) OnConflictColumns(columns ...string) *Sub2APIProviderUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &Sub2APIProviderUpsertOne{
		create: _c,
	}
}

type (
	// Sub2APIProviderUpsertOne is the builder for "upsert"-ing
	//  one Sub2APIProvider node.
	Sub2APIProviderUpsertOne struct {
		create *Sub2APIProviderCreate
	}

	// Sub2APIProviderUpsert is the "OnConflict" setter.
	Sub2APIProviderUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *Sub2APIProviderUpsert) SetUpdatedAt(v time.Time) *Sub2APIProviderUpsert {
	u.Set(sub2apiprovider.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *Sub2APIProviderUpsert) UpdateUpdatedAt() *Sub2APIProviderUpsert {
	u.SetExcluded(sub2apiprovider.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *Sub2APIProviderUpsert) SetDeletedAt(v time.Time) *Sub2APIProviderUpsert {
	u.Set(sub2apiprovider.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *Sub2APIProviderUpsert) UpdateDeletedAt() *Sub2APIProviderUpsert {
	u.SetExcluded(sub2apiprovider.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *Sub2APIProviderUpsert) ClearDeletedAt() *Sub2APIProviderUpsert {
	u.SetNull(sub2apiprovider.FieldDeletedAt)
	return u
}

// SetName sets the "name" field.
func (u *Sub2APIProviderUpsert) SetName(v string) *Sub2APIProviderUpsert {
	u.Set(sub2apiprovider.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *Sub2APIProviderUpsert) UpdateName() *Sub2APIProviderUpsert {
	u.SetExcluded(sub2apiprovider.FieldName)
	return u
}

// SetBaseURL sets the "base_url" field.
func (u *Sub2APIProviderUpsert) SetBaseURL(v string) *Sub2APIProviderUpsert {
	u.Set(sub2apiprovider.FieldBaseURL, v)
	return u
}

// UpdateBaseURL sets the "base_url" field to the value that was provided on create.
func (u *Sub2APIProviderUpsert) UpdateBaseURL() *Sub2APIProviderUpsert {
	u.SetExcluded(sub2apiprovider.FieldBaseURL)
	return u
}

// SetProviderType sets the "provider_type" field.
func (u *Sub2APIProviderUpsert) SetProviderType(v string) *Sub2APIProviderUpsert {
	u.Set(sub2apiprovider.FieldProviderType, v)
	return u
}

// UpdateProviderType sets the "provider_type" field to the value that was provided on create.
func (u *Sub2APIProviderUpsert) UpdateProviderType() *Sub2APIProviderUpsert {
	u.SetExcluded(sub2apiprovider.FieldProviderType)
	return u
}

// SetStatus sets the "status" field.
func (u *Sub2APIProviderUpsert) SetStatus(v string) *Sub2APIProviderUpsert {
	u.Set(sub2apiprovider.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *Sub2APIProviderUpsert) UpdateStatus() *Sub2APIProviderUpsert {
	u.SetExcluded(sub2apiprovider.FieldStatus)
	return u
}

// SetNotes sets the "notes" field.
func (u *Sub2APIProviderUpsert) SetNotes(v string) *Sub2APIProviderUpsert {
	u.Set(sub2apiprovider.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *Sub2APIProviderUpsert) UpdateNotes() *Sub2APIProviderUpsert {
	u.SetExcluded(sub2apiprovider.FieldNotes)
	return u
}

// ClearNotes clears the value of the "notes" field.
func (u *Sub2APIProviderUpsert) ClearNotes() *Sub2APIProviderUpsert {
	u.SetNull(sub2apiprovider.FieldNotes)
	return u
}

// SetProxyID sets the "proxy_id" field.
func (u *Sub2APIProviderUpsert) SetProxyID(v int64) *Sub2APIProviderUpsert {
	u.Set(sub2apiprovider.FieldProxyID, v)
	return u
}

// UpdateProxyID sets the "proxy_id" field to the value that was provided on create.
func (u *Sub2APIProviderUpsert) UpdateProxyID() *Sub2APIProviderUpsert {
	u.SetExcluded(sub2apiprovider.FieldProxyID)
	return u
}

// ClearProxyID clears the value of the "proxy_id" field.
func (u *Sub2APIProviderUpsert) ClearProxyID() *Sub2APIProviderUpsert {
	u.SetNull(sub2apiprovider.FieldProxyID)
	return u
}

// SetEmail sets the "email" field.
func (u *Sub2APIProviderUpsert) SetEmail(v string) *Sub2APIProviderUpsert {
	u.Set(sub2apiprovider.FieldEmail, v)
	return u
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *Sub2APIProviderUpsert) UpdateEmail() *Sub2APIProviderUpsert {
	u.SetExcluded(sub2apiprovider.FieldEmail)
	return u
}

// SetPasswordEncrypted sets the "password_encrypted" field.
func (u *Sub2APIProviderUpsert) SetPasswordEncrypted(v string) *Sub2APIProviderUpsert {
	u.Set(sub2apiprovider.FieldPasswordEncrypted, v)
	return u
}

// UpdatePasswordEncrypted sets the "password_encrypted" field to the value that was provided on create.
func (u *Sub2APIProviderUpsert) UpdatePasswordEncrypted() *Sub2APIProviderUpsert {
	u.SetExcluded(sub2apiprovider.FieldPasswordEncrypted)
	return u
}

// SetAuthMode sets the "auth_mode" field.
func (u *Sub2APIProviderUpsert) SetAuthMode(v string) *Sub2APIProviderUpsert {
	u.Set(sub2apiprovider.FieldAuthMode, v)
	return u
}

// UpdateAuthMode sets the "auth_mode" field to the value that was provided on create.
func (u *Sub2APIProviderUpsert) UpdateAuthMode() *Sub2APIProviderUpsert {
	u.SetExcluded(sub2apiprovider.FieldAuthMode)
	return u
}

// SetAccessTokenEncrypted sets the "access_token_encrypted" field.
func (u *Sub2APIProviderUpsert) SetAccessTokenEncrypted(v string) *Sub2APIProviderUpsert {
	u.Set(sub2apiprovider.FieldAccessTokenEncrypted, v)
	return u
}

// UpdateAccessTokenEncrypted sets the "access_token_encrypted" field to the value that was provided on create.
func (u *Sub2APIProviderUpsert) UpdateAccessTokenEncrypted() *Sub2APIProviderUpsert {
	u.SetExcluded(sub2apiprovider.FieldAccessTokenEncrypted)
	return u
}

// ClearAccessTokenEncrypted clears the value of the "access_token_encrypted" field.
func (u *Sub2APIProviderUpsert) ClearAccessTokenEncrypted() *Sub2APIProviderUpsert {
	u.SetNull(sub2apiprovider.FieldAccessTokenEncrypted)
	return u
}

// SetRefreshTokenEncrypted sets the "refresh_token_encrypted" field.
func (u *Sub2APIProviderUpsert) SetRefreshTokenEncrypted(v string) *Sub2APIProviderUpsert {
	u.Set(sub2apiprovider.FieldRefreshTokenEncrypted, v)
	return u
}

// UpdateRefreshTokenEncrypted sets the "refresh_token_encrypted" field to the value that was provided on create.
func (u *Sub2APIProviderUpsert) UpdateRefreshTokenEncrypted() *Sub2APIProviderUpsert {
	u.SetExcluded(sub2apiprovider.FieldRefreshTokenEncrypted)
	return u
}

// ClearRefreshTokenEncrypted clears the value of the "refresh_token_encrypted" field.
func (u *Sub2APIProviderUpsert) ClearRefreshTokenEncrypted() *Sub2APIProviderUpsert {
	u.SetNull(sub2apiprovider.FieldRefreshTokenEncrypted)
	return u
}

// SetAccessTokenExpiresAt sets the "access_token_expires_at" field.
func (u *Sub2APIProviderUpsert) SetAccessTokenExpiresAt(v time.Time) *Sub2APIProviderUpsert {
	u.Set(sub2apiprovider.FieldAccessTokenExpiresAt, v)
	return u
}

// UpdateAccessTokenExpiresAt sets the "access_token_expires_at" field to the value that was provided on create.
func (u *Sub2APIProviderUpsert) UpdateAccessTokenExpiresAt() *Sub2APIProviderUpsert {
	u.SetExcluded(sub2apiprovider.FieldAccessTokenExpiresAt)
	return u
}

// ClearAccessTokenExpiresAt clears the value of the "access_token_expires_at" field.
func (u *Sub2APIProviderUpsert) ClearAccessTokenExpiresAt() *Sub2APIProviderUpsert {
	u.SetNull(sub2apiprovider.FieldAccessTokenExpiresAt)
	return u
}

// SetLastTokenRefreshAt sets the "last_token_refresh_at" field.
func (u *Sub2APIProviderUpsert) SetLastTokenRefreshAt(v time.Time) *Sub2APIProviderUpsert {
	u.Set(sub2apiprovider.FieldLastTokenRefreshAt, v)
	return u
}

// UpdateLastTokenRefreshAt sets the "last_token_refresh_at" field to the value that was provided on create.
func (u *Sub2APIProviderUpsert) UpdateLastTokenRefreshAt() *Sub2APIProviderUpsert {
	u.SetExcluded(sub2apiprovider.FieldLastTokenRefreshAt)
	return u
}

// ClearLastTokenRefreshAt clears the value of the "last_token_refresh_at" field.
func (u *Sub2APIProviderUpsert) ClearLastTokenRefreshAt() *Sub2APIProviderUpsert {
	u.SetNull(sub2apiprovider.FieldLastTokenRefreshAt)
	return u
}

// SetLastAuthError sets the "last_auth_error" field.
func (u *Sub2APIProviderUpsert) SetLastAuthError(v string) *Sub2APIProviderUpsert {
	u.Set(sub2apiprovider.FieldLastAuthError, v)
	return u
}

// UpdateLastAuthError sets the "last_auth_error" field to the value that was provided on create.
func (u *Sub2APIProviderUpsert) UpdateLastAuthError() *Sub2APIProviderUpsert {
	u.SetExcluded(sub2apiprovider.FieldLastAuthError)
	return u
}

// ClearLastAuthError clears the value of the "last_auth_error" field.
func (u *Sub2APIProviderUpsert) ClearLastAuthError() *Sub2APIProviderUpsert {
	u.SetNull(sub2apiprovider.FieldLastAuthError)
	return u
}

// SetAPIPathKeys sets the "api_path_keys" field.
func (u *Sub2APIProviderUpsert) SetAPIPathKeys(v string) *Sub2APIProviderUpsert {
	u.Set(sub2apiprovider.FieldAPIPathKeys, v)
	return u
}

// UpdateAPIPathKeys sets the "api_path_keys" field to the value that was provided on create.
func (u *Sub2APIProviderUpsert) UpdateAPIPathKeys() *Sub2APIProviderUpsert {
	u.SetExcluded(sub2apiprovider.FieldAPIPathKeys)
	return u
}

// ClearAPIPathKeys clears the value of the "api_path_keys" field.
func (u *Sub2APIProviderUpsert) ClearAPIPathKeys() *Sub2APIProviderUpsert {
	u.SetNull(sub2apiprovider.FieldAPIPathKeys)
	return u
}

// SetAPIPathGroups sets the "api_path_groups" field.
func (u *Sub2APIProviderUpsert) SetAPIPathGroups(v string) *Sub2APIProviderUpsert {
	u.Set(sub2apiprovider.FieldAPIPathGroups, v)
	return u
}

// UpdateAPIPathGroups sets the "api_path_groups" field to the value that was provided on create.
func (u *Sub2APIProviderUpsert) UpdateAPIPathGroups() *Sub2APIProviderUpsert {
	u.SetExcluded(sub2apiprovider.FieldAPIPathGroups)
	return u
}

// ClearAPIPathGroups clears the value of the "api_path_groups" field.
func (u *Sub2APIProviderUpsert) ClearAPIPathGroups() *Sub2APIProviderUpsert {
	u.SetNull(sub2apiprovider.FieldAPIPathGroups)
	return u
}

// SetLastSyncAt sets the "last_sync_at" field.
func (u *Sub2APIProviderUpsert) SetLastSyncAt(v time.Time) *Sub2APIProviderUpsert {
	u.Set(sub2apiprovider.FieldLastSyncAt, v)
	return u
}

// UpdateLastSyncAt sets the "last_sync_at" field to the value that was provided on create.
func (u *Sub2APIProviderUpsert) UpdateLastSyncAt() *Sub2APIProviderUpsert {
	u.SetExcluded(sub2apiprovider.FieldLastSyncAt)
	return u
}

// ClearLastSyncAt clears the value of the "last_sync_at" field.
func (u *Sub2APIProviderUpsert) ClearLastSyncAt() *Sub2APIProviderUpsert {
	u.SetNull(sub2apiprovider.FieldLastSyncAt)
	return u
}

// SetLastSyncStatus sets the "last_sync_status" field.
func (u *Sub2APIProviderUpsert) SetLastSyncStatus(v string) *Sub2APIProviderUpsert {
	u.Set(sub2apiprovider.FieldLastSyncStatus, v)
	return u
}

// UpdateLastSyncStatus sets the "last_sync_status" field to the value that was provided on create.
func (u *Sub2APIProviderUpsert) UpdateLastSyncStatus() *Sub2APIProviderUpsert {
	u.SetExcluded(sub2apiprovider.FieldLastSyncStatus)
	return u
}

// ClearLastSyncStatus clears the value of the "last_sync_status" field.
func (u *Sub2APIProviderUpsert) ClearLastSyncStatus() *Sub2APIProviderUpsert {
	u.SetNull(sub2apiprovider.FieldLastSyncStatus)
	return u
}

// SetLastSyncError sets the "last_sync_error" field.
func (u *Sub2APIProviderUpsert) SetLastSyncError(v string) *Sub2APIProviderUpsert {
	u.Set(sub2apiprovider.FieldLastSyncError, v)
	return u
}

// UpdateLastSyncError sets the "last_sync_error" field to the value that was provided on create.
func (u *Sub2APIProviderUpsert) UpdateLastSyncError() *Sub2APIProviderUpsert {
	u.SetExcluded(sub2apiprovider.FieldLastSyncError)
	return u
}

// ClearLastSyncError clears the value of the "last_sync_error" field.
func (u *Sub2APIProviderUpsert) ClearLastSyncError() *Sub2APIProviderUpsert {
	u.SetNull(sub2apiprovider.FieldLastSyncError)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Sub2APIProvider.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *Sub2APIProviderUpsertOne) UpdateNewValues() *Sub2APIProviderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(sub2apiprovider.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Sub2APIProvider.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *Sub2APIProviderUpsertOne) Ignore() *Sub2APIProviderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *Sub2APIProviderUpsertOne) DoNothing() *Sub2APIProviderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the Sub2APIProviderCreate.OnConflict
// documentation for more info.
func (u *Sub2APIProviderUpsertOne) Update(set func(*Sub2APIProviderUpsert)) *Sub2APIProviderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&Sub2APIProviderUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *Sub2APIProviderUpsertOne) SetUpdatedAt(v time.Time) *Sub2APIProviderUpsertOne {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *Sub2APIProviderUpsertOne) UpdateUpdatedAt() *Sub2APIProviderUpsertOne {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *Sub2APIProviderUpsertOne) SetDeletedAt(v time.Time) *Sub2APIProviderUpsertOne {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *Sub2APIProviderUpsertOne) UpdateDeletedAt() *Sub2APIProviderUpsertOne {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *Sub2APIProviderUpsertOne) ClearDeletedAt() *Sub2APIProviderUpsertOne {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *Sub2APIProviderUpsertOne) SetName(v string) *Sub2APIProviderUpsertOne {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *Sub2APIProviderUpsertOne) UpdateName() *Sub2APIProviderUpsertOne {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.UpdateName()
	})
}

// SetBaseURL sets the "base_url" field.
func (u *Sub2APIProviderUpsertOne) SetBaseURL(v string) *Sub2APIProviderUpsertOne {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.SetBaseURL(v)
	})
}

// UpdateBaseURL sets the "base_url" field to the value that was provided on create.
func (u *Sub2APIProviderUpsertOne) UpdateBaseURL() *Sub2APIProviderUpsertOne {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.UpdateBaseURL()
	})
}

// SetProviderType sets the "provider_type" field.
func (u *Sub2APIProviderUpsertOne) SetProviderType(v string) *Sub2APIProviderUpsertOne {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.SetProviderType(v)
	})
}

// UpdateProviderType sets the "provider_type" field to the value that was provided on create.
func (u *Sub2APIProviderUpsertOne) UpdateProviderType() *Sub2APIProviderUpsertOne {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.UpdateProviderType()
	})
}

// SetStatus sets the "status" field.
func (u *Sub2APIProviderUpsertOne) SetStatus(v string) *Sub2APIProviderUpsertOne {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *Sub2APIProviderUpsertOne) UpdateStatus() *Sub2APIProviderUpsertOne {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.UpdateStatus()
	})
}

// SetNotes sets the "notes" field.
func (u *Sub2APIProviderUpsertOne) SetNotes(v string) *Sub2APIProviderUpsertOne {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *Sub2APIProviderUpsertOne) UpdateNotes() *Sub2APIProviderUpsertOne {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *Sub2APIProviderUpsertOne) ClearNotes() *Sub2APIProviderUpsertOne {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.ClearNotes()
	})
}

// SetProxyID sets the "proxy_id" field.
func (u *Sub2APIProviderUpsertOne) SetProxyID(v int64) *Sub2APIProviderUpsertOne {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.SetProxyID(v)
	})
}

// UpdateProxyID sets the "proxy_id" field to the value that was provided on create.
func (u *Sub2APIProviderUpsertOne) UpdateProxyID() *Sub2APIProviderUpsertOne {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.UpdateProxyID()
	})
}

// ClearProxyID clears the value of the "proxy_id" field.
func (u *Sub2APIProviderUpsertOne) ClearProxyID() *Sub2APIProviderUpsertOne {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.ClearProxyID()
	})
}

// SetEmail sets the "email" field.
func (u *Sub2APIProviderUpsertOne) SetEmail(v string) *Sub2APIProviderUpsertOne {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *Sub2APIProviderUpsertOne) UpdateEmail() *Sub2APIProviderUpsertOne {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.UpdateEmail()
	})
}

// SetPasswordEncrypted sets the "password_encrypted" field.
func (u *Sub2APIProviderUpsertOne) SetPasswordEncrypted(v string) *Sub2APIProviderUpsertOne {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.SetPasswordEncrypted(v)
	})
}

// UpdatePasswordEncrypted sets the "password_encrypted" field to the value that was provided on create.
func (u *Sub2APIProviderUpsertOne) UpdatePasswordEncrypted() *Sub2APIProviderUpsertOne {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.UpdatePasswordEncrypted()
	})
}

// SetAuthMode sets the "auth_mode" field.
func (u *Sub2APIProviderUpsertOne) SetAuthMode(v string) *Sub2APIProviderUpsertOne {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.SetAuthMode(v)
	})
}

// UpdateAuthMode sets the "auth_mode" field to the value that was provided on create.
func (u *Sub2APIProviderUpsertOne) UpdateAuthMode() *Sub2APIProviderUpsertOne {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.UpdateAuthMode()
	})
}

// SetAccessTokenEncrypted sets the "access_token_encrypted" field.
func (u *Sub2APIProviderUpsertOne) SetAccessTokenEncrypted(v string) *Sub2APIProviderUpsertOne {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.SetAccessTokenEncrypted(v)
	})
}

// UpdateAccessTokenEncrypted sets the "access_token_encrypted" field to the value that was provided on create.
func (u *Sub2APIProviderUpsertOne) UpdateAccessTokenEncrypted() *Sub2APIProviderUpsertOne {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.UpdateAccessTokenEncrypted()
	})
}

// ClearAccessTokenEncrypted clears the value of the "access_token_encrypted" field.
func (u *Sub2APIProviderUpsertOne) ClearAccessTokenEncrypted() *Sub2APIProviderUpsertOne {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.ClearAccessTokenEncrypted()
	})
}

// SetRefreshTokenEncrypted sets the "refresh_token_encrypted" field.
func (u *Sub2APIProviderUpsertOne) SetRefreshTokenEncrypted(v string) *Sub2APIProviderUpsertOne {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.SetRefreshTokenEncrypted(v)
	})
}

// UpdateRefreshTokenEncrypted sets the "refresh_token_encrypted" field to the value that was provided on create.
func (u *Sub2APIProviderUpsertOne) UpdateRefreshTokenEncrypted() *Sub2APIProviderUpsertOne {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.UpdateRefreshTokenEncrypted()
	})
}

// ClearRefreshTokenEncrypted clears the value of the "refresh_token_encrypted" field.
func (u *Sub2APIProviderUpsertOne) ClearRefreshTokenEncrypted() *Sub2APIProviderUpsertOne {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.ClearRefreshTokenEncrypted()
	})
}

// SetAccessTokenExpiresAt sets the "access_token_expires_at" field.
func (u *Sub2APIProviderUpsertOne) SetAccessTokenExpiresAt(v time.Time) *Sub2APIProviderUpsertOne {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.SetAccessTokenExpiresAt(v)
	})
}

// UpdateAccessTokenExpiresAt sets the "access_token_expires_at" field to the value that was provided on create.
func (u *Sub2APIProviderUpsertOne) UpdateAccessTokenExpiresAt() *Sub2APIProviderUpsertOne {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.UpdateAccessTokenExpiresAt()
	})
}

// ClearAccessTokenExpiresAt clears the value of the "access_token_expires_at" field.
func (u *Sub2APIProviderUpsertOne) ClearAccessTokenExpiresAt() *Sub2APIProviderUpsertOne {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.ClearAccessTokenExpiresAt()
	})
}

// SetLastTokenRefreshAt sets the "last_token_refresh_at" field.
func (u *Sub2APIProviderUpsertOne) SetLastTokenRefreshAt(v time.Time) *Sub2APIProviderUpsertOne {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.SetLastTokenRefreshAt(v)
	})
}

// UpdateLastTokenRefreshAt sets the "last_token_refresh_at" field to the value that was provided on create.
func (u *Sub2APIProviderUpsertOne) UpdateLastTokenRefreshAt() *Sub2APIProviderUpsertOne {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.UpdateLastTokenRefreshAt()
	})
}

// ClearLastTokenRefreshAt clears the value of the "last_token_refresh_at" field.
func (u *Sub2APIProviderUpsertOne) ClearLastTokenRefreshAt() *Sub2APIProviderUpsertOne {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.ClearLastTokenRefreshAt()
	})
}

// SetLastAuthError sets the "last_auth_error" field.
func (u *Sub2APIProviderUpsertOne) SetLastAuthError(v string) *Sub2APIProviderUpsertOne {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.SetLastAuthError(v)
	})
}

// UpdateLastAuthError sets the "last_auth_error" field to the value that was provided on create.
func (u *Sub2APIProviderUpsertOne) UpdateLastAuthError() *Sub2APIProviderUpsertOne {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.UpdateLastAuthError()
	})
}

// ClearLastAuthError clears the value of the "last_auth_error" field.
func (u *Sub2APIProviderUpsertOne) ClearLastAuthError() *Sub2APIProviderUpsertOne {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.ClearLastAuthError()
	})
}

// SetAPIPathKeys sets the "api_path_keys" field.
func (u *Sub2APIProviderUpsertOne) SetAPIPathKeys(v string) *Sub2APIProviderUpsertOne {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.SetAPIPathKeys(v)
	})
}

// UpdateAPIPathKeys sets the "api_path_keys" field to the value that was provided on create.
func (u *Sub2APIProviderUpsertOne) UpdateAPIPathKeys() *Sub2APIProviderUpsertOne {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.UpdateAPIPathKeys()
	})
}

// ClearAPIPathKeys clears the value of the "api_path_keys" field.
func (u *Sub2APIProviderUpsertOne) ClearAPIPathKeys() *Sub2APIProviderUpsertOne {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.ClearAPIPathKeys()
	})
}

// SetAPIPathGroups sets the "api_path_groups" field.
func (u *Sub2APIProviderUpsertOne) SetAPIPathGroups(v string) *Sub2APIProviderUpsertOne {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.SetAPIPathGroups(v)
	})
}

// UpdateAPIPathGroups sets the "api_path_groups" field to the value that was provided on create.
func (u *Sub2APIProviderUpsertOne) UpdateAPIPathGroups() *Sub2APIProviderUpsertOne {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.UpdateAPIPathGroups()
	})
}

// ClearAPIPathGroups clears the value of the "api_path_groups" field.
func (u *Sub2APIProviderUpsertOne) ClearAPIPathGroups() *Sub2APIProviderUpsertOne {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.ClearAPIPathGroups()
	})
}

// SetLastSyncAt sets the "last_sync_at" field.
func (u *Sub2APIProviderUpsertOne) SetLastSyncAt(v time.Time) *Sub2APIProviderUpsertOne {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.SetLastSyncAt(v)
	})
}

// UpdateLastSyncAt sets the "last_sync_at" field to the value that was provided on create.
func (u *Sub2APIProviderUpsertOne) UpdateLastSyncAt() *Sub2APIProviderUpsertOne {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.UpdateLastSyncAt()
	})
}

// ClearLastSyncAt clears the value of the "last_sync_at" field.
func (u *Sub2APIProviderUpsertOne) ClearLastSyncAt() *Sub2APIProviderUpsertOne {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.ClearLastSyncAt()
	})
}

// SetLastSyncStatus sets the "last_sync_status" field.
func (u *Sub2APIProviderUpsertOne) SetLastSyncStatus(v string) *Sub2APIProviderUpsertOne {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.SetLastSyncStatus(v)
	})
}

// UpdateLastSyncStatus sets the "last_sync_status" field to the value that was provided on create.
func (u *Sub2APIProviderUpsertOne) UpdateLastSyncStatus() *Sub2APIProviderUpsertOne {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.UpdateLastSyncStatus()
	})
}

// ClearLastSyncStatus clears the value of the "last_sync_status" field.
func (u *Sub2APIProviderUpsertOne) ClearLastSyncStatus() *Sub2APIProviderUpsertOne {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.ClearLastSyncStatus()
	})
}

// SetLastSyncError sets the "last_sync_error" field.
func (u *Sub2APIProviderUpsertOne) SetLastSyncError(v string) *Sub2APIProviderUpsertOne {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.SetLastSyncError(v)
	})
}

// UpdateLastSyncError sets the "last_sync_error" field to the value that was provided on create.
func (u *Sub2APIProviderUpsertOne) UpdateLastSyncError() *Sub2APIProviderUpsertOne {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.UpdateLastSyncError()
	})
}

// ClearLastSyncError clears the value of the "last_sync_error" field.
func (u *Sub2APIProviderUpsertOne) ClearLastSyncError() *Sub2APIProviderUpsertOne {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.ClearLastSyncError()
	})
}

// Exec executes the query.
func (u *Sub2APIProviderUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for Sub2APIProviderCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *Sub2APIProviderUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *Sub2APIProviderUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *Sub2APIProviderUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// Sub2APIProviderCreateBulk is the builder for creating many Sub2APIProvider entities in bulk.
type Sub2APIProviderCreateBulk struct {
	config
	err      error
	builders []*Sub2APIProviderCreate
	conflict []sql.ConflictOption
}

// Save creates the Sub2APIProvider entities in the database.
func (_c *Sub2APIProviderCreateBulk) Save(ctx context.Context) ([]*Sub2APIProvider, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Sub2APIProvider, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*Sub2APIProviderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *Sub2APIProviderCreateBulk) SaveX(ctx context.Context) []*Sub2APIProvider {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *Sub2APIProviderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *Sub2APIProviderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Sub2APIProvider.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.Sub2APIProviderUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *Sub2APIProviderCreateBulk) OnConflict(opts ...sql.ConflictOption) *Sub2APIProviderUpsertBulk {
	_c.conflict = opts
	return &Sub2APIProviderUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Sub2APIProvider.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *Sub2APIProviderCreateBulk) OnConflictColumns(columns ...string) *Sub2APIProviderUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &Sub2APIProviderUpsertBulk{
		create: _c,
	}
}

// Sub2APIProviderUpsertBulk is the builder for "upsert"-ing
// a bulk of Sub2APIProvider nodes.
type Sub2APIProviderUpsertBulk struct {
	create *Sub2APIProviderCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Sub2APIProvider.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *Sub2APIProviderUpsertBulk) UpdateNewValues() *Sub2APIProviderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(sub2apiprovider.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Sub2APIProvider.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *Sub2APIProviderUpsertBulk) Ignore() *Sub2APIProviderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *Sub2APIProviderUpsertBulk) DoNothing() *Sub2APIProviderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the Sub2APIProviderCreateBulk.OnConflict
// documentation for more info.
func (u *Sub2APIProviderUpsertBulk) Update(set func(*Sub2APIProviderUpsert)) *Sub2APIProviderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&Sub2APIProviderUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *Sub2APIProviderUpsertBulk) SetUpdatedAt(v time.Time) *Sub2APIProviderUpsertBulk {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *Sub2APIProviderUpsertBulk) UpdateUpdatedAt() *Sub2APIProviderUpsertBulk {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *Sub2APIProviderUpsertBulk) SetDeletedAt(v time.Time) *Sub2APIProviderUpsertBulk {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *Sub2APIProviderUpsertBulk) UpdateDeletedAt() *Sub2APIProviderUpsertBulk {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *Sub2APIProviderUpsertBulk) ClearDeletedAt() *Sub2APIProviderUpsertBulk {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *Sub2APIProviderUpsertBulk) SetName(v string) *Sub2APIProviderUpsertBulk {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *Sub2APIProviderUpsertBulk) UpdateName() *Sub2APIProviderUpsertBulk {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.UpdateName()
	})
}

// SetBaseURL sets the "base_url" field.
func (u *Sub2APIProviderUpsertBulk) SetBaseURL(v string) *Sub2APIProviderUpsertBulk {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.SetBaseURL(v)
	})
}

// UpdateBaseURL sets the "base_url" field to the value that was provided on create.
func (u *Sub2APIProviderUpsertBulk) UpdateBaseURL() *Sub2APIProviderUpsertBulk {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.UpdateBaseURL()
	})
}

// SetProviderType sets the "provider_type" field.
func (u *Sub2APIProviderUpsertBulk) SetProviderType(v string) *Sub2APIProviderUpsertBulk {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.SetProviderType(v)
	})
}

// UpdateProviderType sets the "provider_type" field to the value that was provided on create.
func (u *Sub2APIProviderUpsertBulk) UpdateProviderType() *Sub2APIProviderUpsertBulk {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.UpdateProviderType()
	})
}

// SetStatus sets the "status" field.
func (u *Sub2APIProviderUpsertBulk) SetStatus(v string) *Sub2APIProviderUpsertBulk {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *Sub2APIProviderUpsertBulk) UpdateStatus() *Sub2APIProviderUpsertBulk {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.UpdateStatus()
	})
}

// SetNotes sets the "notes" field.
func (u *Sub2APIProviderUpsertBulk) SetNotes(v string) *Sub2APIProviderUpsertBulk {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *Sub2APIProviderUpsertBulk) UpdateNotes() *Sub2APIProviderUpsertBulk {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *Sub2APIProviderUpsertBulk) ClearNotes() *Sub2APIProviderUpsertBulk {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.ClearNotes()
	})
}

// SetProxyID sets the "proxy_id" field.
func (u *Sub2APIProviderUpsertBulk) SetProxyID(v int64) *Sub2APIProviderUpsertBulk {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.SetProxyID(v)
	})
}

// UpdateProxyID sets the "proxy_id" field to the value that was provided on create.
func (u *Sub2APIProviderUpsertBulk) UpdateProxyID() *Sub2APIProviderUpsertBulk {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.UpdateProxyID()
	})
}

// ClearProxyID clears the value of the "proxy_id" field.
func (u *Sub2APIProviderUpsertBulk) ClearProxyID() *Sub2APIProviderUpsertBulk {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.ClearProxyID()
	})
}

// SetEmail sets the "email" field.
func (u *Sub2APIProviderUpsertBulk) SetEmail(v string) *Sub2APIProviderUpsertBulk {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *Sub2APIProviderUpsertBulk) UpdateEmail() *Sub2APIProviderUpsertBulk {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.UpdateEmail()
	})
}

// SetPasswordEncrypted sets the "password_encrypted" field.
func (u *Sub2APIProviderUpsertBulk) SetPasswordEncrypted(v string) *Sub2APIProviderUpsertBulk {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.SetPasswordEncrypted(v)
	})
}

// UpdatePasswordEncrypted sets the "password_encrypted" field to the value that was provided on create.
func (u *Sub2APIProviderUpsertBulk) UpdatePasswordEncrypted() *Sub2APIProviderUpsertBulk {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.UpdatePasswordEncrypted()
	})
}

// SetAuthMode sets the "auth_mode" field.
func (u *Sub2APIProviderUpsertBulk) SetAuthMode(v string) *Sub2APIProviderUpsertBulk {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.SetAuthMode(v)
	})
}

// UpdateAuthMode sets the "auth_mode" field to the value that was provided on create.
func (u *Sub2APIProviderUpsertBulk) UpdateAuthMode() *Sub2APIProviderUpsertBulk {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.UpdateAuthMode()
	})
}

// SetAccessTokenEncrypted sets the "access_token_encrypted" field.
func (u *Sub2APIProviderUpsertBulk) SetAccessTokenEncrypted(v string) *Sub2APIProviderUpsertBulk {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.SetAccessTokenEncrypted(v)
	})
}

// UpdateAccessTokenEncrypted sets the "access_token_encrypted" field to the value that was provided on create.
func (u *Sub2APIProviderUpsertBulk) UpdateAccessTokenEncrypted() *Sub2APIProviderUpsertBulk {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.UpdateAccessTokenEncrypted()
	})
}

// ClearAccessTokenEncrypted clears the value of the "access_token_encrypted" field.
func (u *Sub2APIProviderUpsertBulk) ClearAccessTokenEncrypted() *Sub2APIProviderUpsertBulk {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.ClearAccessTokenEncrypted()
	})
}

// SetRefreshTokenEncrypted sets the "refresh_token_encrypted" field.
func (u *Sub2APIProviderUpsertBulk) SetRefreshTokenEncrypted(v string) *Sub2APIProviderUpsertBulk {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.SetRefreshTokenEncrypted(v)
	})
}

// UpdateRefreshTokenEncrypted sets the "refresh_token_encrypted" field to the value that was provided on create.
func (u *Sub2APIProviderUpsertBulk) UpdateRefreshTokenEncrypted() *Sub2APIProviderUpsertBulk {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.UpdateRefreshTokenEncrypted()
	})
}

// ClearRefreshTokenEncrypted clears the value of the "refresh_token_encrypted" field.
func (u *Sub2APIProviderUpsertBulk) ClearRefreshTokenEncrypted() *Sub2APIProviderUpsertBulk {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.ClearRefreshTokenEncrypted()
	})
}

// SetAccessTokenExpiresAt sets the "access_token_expires_at" field.
func (u *Sub2APIProviderUpsertBulk) SetAccessTokenExpiresAt(v time.Time) *Sub2APIProviderUpsertBulk {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.SetAccessTokenExpiresAt(v)
	})
}

// UpdateAccessTokenExpiresAt sets the "access_token_expires_at" field to the value that was provided on create.
func (u *Sub2APIProviderUpsertBulk) UpdateAccessTokenExpiresAt() *Sub2APIProviderUpsertBulk {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.UpdateAccessTokenExpiresAt()
	})
}

// ClearAccessTokenExpiresAt clears the value of the "access_token_expires_at" field.
func (u *Sub2APIProviderUpsertBulk) ClearAccessTokenExpiresAt() *Sub2APIProviderUpsertBulk {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.ClearAccessTokenExpiresAt()
	})
}

// SetLastTokenRefreshAt sets the "last_token_refresh_at" field.
func (u *Sub2APIProviderUpsertBulk) SetLastTokenRefreshAt(v time.Time) *Sub2APIProviderUpsertBulk {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.SetLastTokenRefreshAt(v)
	})
}

// UpdateLastTokenRefreshAt sets the "last_token_refresh_at" field to the value that was provided on create.
func (u *Sub2APIProviderUpsertBulk) UpdateLastTokenRefreshAt() *Sub2APIProviderUpsertBulk {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.UpdateLastTokenRefreshAt()
	})
}

// ClearLastTokenRefreshAt clears the value of the "last_token_refresh_at" field.
func (u *Sub2APIProviderUpsertBulk) ClearLastTokenRefreshAt() *Sub2APIProviderUpsertBulk {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.ClearLastTokenRefreshAt()
	})
}

// SetLastAuthError sets the "last_auth_error" field.
func (u *Sub2APIProviderUpsertBulk) SetLastAuthError(v string) *Sub2APIProviderUpsertBulk {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.SetLastAuthError(v)
	})
}

// UpdateLastAuthError sets the "last_auth_error" field to the value that was provided on create.
func (u *Sub2APIProviderUpsertBulk) UpdateLastAuthError() *Sub2APIProviderUpsertBulk {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.UpdateLastAuthError()
	})
}

// ClearLastAuthError clears the value of the "last_auth_error" field.
func (u *Sub2APIProviderUpsertBulk) ClearLastAuthError() *Sub2APIProviderUpsertBulk {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.ClearLastAuthError()
	})
}

// SetAPIPathKeys sets the "api_path_keys" field.
func (u *Sub2APIProviderUpsertBulk) SetAPIPathKeys(v string) *Sub2APIProviderUpsertBulk {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.SetAPIPathKeys(v)
	})
}

// UpdateAPIPathKeys sets the "api_path_keys" field to the value that was provided on create.
func (u *Sub2APIProviderUpsertBulk) UpdateAPIPathKeys() *Sub2APIProviderUpsertBulk {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.UpdateAPIPathKeys()
	})
}

// ClearAPIPathKeys clears the value of the "api_path_keys" field.
func (u *Sub2APIProviderUpsertBulk) ClearAPIPathKeys() *Sub2APIProviderUpsertBulk {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.ClearAPIPathKeys()
	})
}

// SetAPIPathGroups sets the "api_path_groups" field.
func (u *Sub2APIProviderUpsertBulk) SetAPIPathGroups(v string) *Sub2APIProviderUpsertBulk {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.SetAPIPathGroups(v)
	})
}

// UpdateAPIPathGroups sets the "api_path_groups" field to the value that was provided on create.
func (u *Sub2APIProviderUpsertBulk) UpdateAPIPathGroups() *Sub2APIProviderUpsertBulk {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.UpdateAPIPathGroups()
	})
}

// ClearAPIPathGroups clears the value of the "api_path_groups" field.
func (u *Sub2APIProviderUpsertBulk) ClearAPIPathGroups() *Sub2APIProviderUpsertBulk {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.ClearAPIPathGroups()
	})
}

// SetLastSyncAt sets the "last_sync_at" field.
func (u *Sub2APIProviderUpsertBulk) SetLastSyncAt(v time.Time) *Sub2APIProviderUpsertBulk {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.SetLastSyncAt(v)
	})
}

// UpdateLastSyncAt sets the "last_sync_at" field to the value that was provided on create.
func (u *Sub2APIProviderUpsertBulk) UpdateLastSyncAt() *Sub2APIProviderUpsertBulk {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.UpdateLastSyncAt()
	})
}

// ClearLastSyncAt clears the value of the "last_sync_at" field.
func (u *Sub2APIProviderUpsertBulk) ClearLastSyncAt() *Sub2APIProviderUpsertBulk {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.ClearLastSyncAt()
	})
}

// SetLastSyncStatus sets the "last_sync_status" field.
func (u *Sub2APIProviderUpsertBulk) SetLastSyncStatus(v string) *Sub2APIProviderUpsertBulk {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.SetLastSyncStatus(v)
	})
}

// UpdateLastSyncStatus sets the "last_sync_status" field to the value that was provided on create.
func (u *Sub2APIProviderUpsertBulk) UpdateLastSyncStatus() *Sub2APIProviderUpsertBulk {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.UpdateLastSyncStatus()
	})
}

// ClearLastSyncStatus clears the value of the "last_sync_status" field.
func (u *Sub2APIProviderUpsertBulk) ClearLastSyncStatus() *Sub2APIProviderUpsertBulk {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.ClearLastSyncStatus()
	})
}

// SetLastSyncError sets the "last_sync_error" field.
func (u *Sub2APIProviderUpsertBulk) SetLastSyncError(v string) *Sub2APIProviderUpsertBulk {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.SetLastSyncError(v)
	})
}

// UpdateLastSyncError sets the "last_sync_error" field to the value that was provided on create.
func (u *Sub2APIProviderUpsertBulk) UpdateLastSyncError() *Sub2APIProviderUpsertBulk {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.UpdateLastSyncError()
	})
}

// ClearLastSyncError clears the value of the "last_sync_error" field.
func (u *Sub2APIProviderUpsertBulk) ClearLastSyncError() *Sub2APIProviderUpsertBulk {
	return u.Update(func(s *Sub2APIProviderUpsert) {
		s.ClearLastSyncError()
	})
}

// Exec executes the query.
func (u *Sub2APIProviderUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the Sub2APIProviderCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for Sub2APIProviderCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *Sub2APIProviderUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
