// Code generated by ent, DO NOT EDIT.

package sub2apiprovider

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldEQ(FieldDeletedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldEQ(FieldName, v))
}

// BaseURL applies equality check predicate on the "base_url" field. It's identical to BaseURLEQ.
func BaseURL(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldEQ(FieldBaseURL, v))
}

// ProviderType applies equality check predicate on the "provider_type" field. It's identical to ProviderTypeEQ.
func ProviderType(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldEQ(FieldProviderType, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldEQ(FieldStatus, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldEQ(FieldNotes, v))
}

// ProxyID applies equality check predicate on the "proxy_id" field. It's identical to ProxyIDEQ.
func ProxyID(v int64) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldEQ(FieldProxyID, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldEQ(FieldEmail, v))
}

// PasswordEncrypted applies equality check predicate on the "password_encrypted" field. It's identical to PasswordEncryptedEQ.
func PasswordEncrypted(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldEQ(FieldPasswordEncrypted, v))
}

// AuthMode applies equality check predicate on the "auth_mode" field. It's identical to AuthModeEQ.
func AuthMode(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldEQ(FieldAuthMode, v))
}

// AccessTokenEncrypted applies equality check predicate on the "access_token_encrypted" field. It's identical to AccessTokenEncryptedEQ.
func AccessTokenEncrypted(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldEQ(FieldAccessTokenEncrypted, v))
}

// RefreshTokenEncrypted applies equality check predicate on the "refresh_token_encrypted" field. It's identical to RefreshTokenEncryptedEQ.
func RefreshTokenEncrypted(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldEQ(FieldRefreshTokenEncrypted, v))
}

// AccessTokenExpiresAt applies equality check predicate on the "access_token_expires_at" field. It's identical to AccessTokenExpiresAtEQ.
func AccessTokenExpiresAt(v time.Time) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldEQ(FieldAccessTokenExpiresAt, v))
}

// LastTokenRefreshAt applies equality check predicate on the "last_token_refresh_at" field. It's identical to LastTokenRefreshAtEQ.
func LastTokenRefreshAt(v time.Time) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldEQ(FieldLastTokenRefreshAt, v))
}

// LastAuthError applies equality check predicate on the "last_auth_error" field. It's identical to LastAuthErrorEQ.
func LastAuthError(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldEQ(FieldLastAuthError, v))
}

// APIPathKeys applies equality check predicate on the "api_path_keys" field. It's identical to APIPathKeysEQ.
func APIPathKeys(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldEQ(FieldAPIPathKeys, v))
}

// APIPathGroups applies equality check predicate on the "api_path_groups" field. It's identical to APIPathGroupsEQ.
func APIPathGroups(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldEQ(FieldAPIPathGroups, v))
}

// LastSyncAt applies equality check predicate on the "last_sync_at" field. It's identical to LastSyncAtEQ.
func LastSyncAt(v time.Time) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldEQ(FieldLastSyncAt, v))
}

// LastSyncStatus applies equality check predicate on the "last_sync_status" field. It's identical to LastSyncStatusEQ.
func LastSyncStatus(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldEQ(FieldLastSyncStatus, v))
}

// LastSyncError applies equality check predicate on the "last_sync_error" field. It's identical to LastSyncErrorEQ.
func LastSyncError(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldEQ(FieldLastSyncError, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldNotNull(FieldDeletedAt))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldContainsFold(FieldName, v))
}

// BaseURLEQ applies the EQ predicate on the "base_url" field.
func BaseURLEQ(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldEQ(FieldBaseURL, v))
}

// BaseURLNEQ applies the NEQ predicate on the "base_url" field.
func BaseURLNEQ(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldNEQ(FieldBaseURL, v))
}

// BaseURLIn applies the In predicate on the "base_url" field.
func BaseURLIn(vs ...string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldIn(FieldBaseURL, vs...))
}

// BaseURLNotIn applies the NotIn predicate on the "base_url" field.
func BaseURLNotIn(vs ...string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldNotIn(FieldBaseURL, vs...))
}

// BaseURLGT applies the GT predicate on the "base_url" field.
func BaseURLGT(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldGT(FieldBaseURL, v))
}

// BaseURLGTE applies the GTE predicate on the "base_url" field.
func BaseURLGTE(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldGTE(FieldBaseURL, v))
}

// BaseURLLT applies the LT predicate on the "base_url" field.
func BaseURLLT(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldLT(FieldBaseURL, v))
}

// BaseURLLTE applies the LTE predicate on the "base_url" field.
func BaseURLLTE(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldLTE(FieldBaseURL, v))
}

// BaseURLContains applies the Contains predicate on the "base_url" field.
func BaseURLContains(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldContains(FieldBaseURL, v))
}

// BaseURLHasPrefix applies the HasPrefix predicate on the "base_url" field.
func BaseURLHasPrefix(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldHasPrefix(FieldBaseURL, v))
}

// BaseURLHasSuffix applies the HasSuffix predicate on the "base_url" field.
func BaseURLHasSuffix(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldHasSuffix(FieldBaseURL, v))
}

// BaseURLEqualFold applies the EqualFold predicate on the "base_url" field.
func BaseURLEqualFold(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldEqualFold(FieldBaseURL, v))
}

// BaseURLContainsFold applies the ContainsFold predicate on the "base_url" field.
func BaseURLContainsFold(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldContainsFold(FieldBaseURL, v))
}

// ProviderTypeEQ applies the EQ predicate on the "provider_type" field.
func ProviderTypeEQ(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldEQ(FieldProviderType, v))
}

// ProviderTypeNEQ applies the NEQ predicate on the "provider_type" field.
func ProviderTypeNEQ(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldNEQ(FieldProviderType, v))
}

// ProviderTypeIn applies the In predicate on the "provider_type" field.
func ProviderTypeIn(vs ...string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldIn(FieldProviderType, vs...))
}

// ProviderTypeNotIn applies the NotIn predicate on the "provider_type" field.
func ProviderTypeNotIn(vs ...string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldNotIn(FieldProviderType, vs...))
}

// ProviderTypeGT applies the GT predicate on the "provider_type" field.
func ProviderTypeGT(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldGT(FieldProviderType, v))
}

// ProviderTypeGTE applies the GTE predicate on the "provider_type" field.
func ProviderTypeGTE(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldGTE(FieldProviderType, v))
}

// ProviderTypeLT applies the LT predicate on the "provider_type" field.
func ProviderTypeLT(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldLT(FieldProviderType, v))
}

// ProviderTypeLTE applies the LTE predicate on the "provider_type" field.
func ProviderTypeLTE(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldLTE(FieldProviderType, v))
}

// ProviderTypeContains applies the Contains predicate on the "provider_type" field.
func ProviderTypeContains(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldContains(FieldProviderType, v))
}

// ProviderTypeHasPrefix applies the HasPrefix predicate on the "provider_type" field.
func ProviderTypeHasPrefix(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldHasPrefix(FieldProviderType, v))
}

// ProviderTypeHasSuffix applies the HasSuffix predicate on the "provider_type" field.
func ProviderTypeHasSuffix(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldHasSuffix(FieldProviderType, v))
}

// ProviderTypeEqualFold applies the EqualFold predicate on the "provider_type" field.
func ProviderTypeEqualFold(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldEqualFold(FieldProviderType, v))
}

// ProviderTypeContainsFold applies the ContainsFold predicate on the "provider_type" field.
func ProviderTypeContainsFold(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldContainsFold(FieldProviderType, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldContainsFold(FieldStatus, v))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldContainsFold(FieldNotes, v))
}

// ProxyIDEQ applies the EQ predicate on the "proxy_id" field.
func ProxyIDEQ(v int64) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldEQ(FieldProxyID, v))
}

// ProxyIDNEQ applies the NEQ predicate on the "proxy_id" field.
func ProxyIDNEQ(v int64) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldNEQ(FieldProxyID, v))
}

// ProxyIDIn applies the In predicate on the "proxy_id" field.
func ProxyIDIn(vs ...int64) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldIn(FieldProxyID, vs...))
}

// ProxyIDNotIn applies the NotIn predicate on the "proxy_id" field.
func ProxyIDNotIn(vs ...int64) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldNotIn(FieldProxyID, vs...))
}

// ProxyIDIsNil applies the IsNil predicate on the "proxy_id" field.
func ProxyIDIsNil() predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldIsNull(FieldProxyID))
}

// ProxyIDNotNil applies the NotNil predicate on the "proxy_id" field.
func ProxyIDNotNil() predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldNotNull(FieldProxyID))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldContainsFold(FieldEmail, v))
}

// PasswordEncryptedEQ applies the EQ predicate on the "password_encrypted" field.
func PasswordEncryptedEQ(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldEQ(FieldPasswordEncrypted, v))
}

// PasswordEncryptedNEQ applies the NEQ predicate on the "password_encrypted" field.
func PasswordEncryptedNEQ(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldNEQ(FieldPasswordEncrypted, v))
}

// PasswordEncryptedIn applies the In predicate on the "password_encrypted" field.
func PasswordEncryptedIn(vs ...string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldIn(FieldPasswordEncrypted, vs...))
}

// PasswordEncryptedNotIn applies the NotIn predicate on the "password_encrypted" field.
func PasswordEncryptedNotIn(vs ...string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldNotIn(FieldPasswordEncrypted, vs...))
}

// PasswordEncryptedGT applies the GT predicate on the "password_encrypted" field.
func PasswordEncryptedGT(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldGT(FieldPasswordEncrypted, v))
}

// PasswordEncryptedGTE applies the GTE predicate on the "password_encrypted" field.
func PasswordEncryptedGTE(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldGTE(FieldPasswordEncrypted, v))
}

// PasswordEncryptedLT applies the LT predicate on the "password_encrypted" field.
func PasswordEncryptedLT(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldLT(FieldPasswordEncrypted, v))
}

// PasswordEncryptedLTE applies the LTE predicate on the "password_encrypted" field.
func PasswordEncryptedLTE(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldLTE(FieldPasswordEncrypted, v))
}

// PasswordEncryptedContains applies the Contains predicate on the "password_encrypted" field.
func PasswordEncryptedContains(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldContains(FieldPasswordEncrypted, v))
}

// PasswordEncryptedHasPrefix applies the HasPrefix predicate on the "password_encrypted" field.
func PasswordEncryptedHasPrefix(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldHasPrefix(FieldPasswordEncrypted, v))
}

// PasswordEncryptedHasSuffix applies the HasSuffix predicate on the "password_encrypted" field.
func PasswordEncryptedHasSuffix(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldHasSuffix(FieldPasswordEncrypted, v))
}

// PasswordEncryptedEqualFold applies the EqualFold predicate on the "password_encrypted" field.
func PasswordEncryptedEqualFold(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldEqualFold(FieldPasswordEncrypted, v))
}

// PasswordEncryptedContainsFold applies the ContainsFold predicate on the "password_encrypted" field.
func PasswordEncryptedContainsFold(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldContainsFold(FieldPasswordEncrypted, v))
}

// AuthModeEQ applies the EQ predicate on the "auth_mode" field.
func AuthModeEQ(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldEQ(FieldAuthMode, v))
}

// AuthModeNEQ applies the NEQ predicate on the "auth_mode" field.
func AuthModeNEQ(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldNEQ(FieldAuthMode, v))
}

// AuthModeIn applies the In predicate on the "auth_mode" field.
func AuthModeIn(vs ...string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldIn(FieldAuthMode, vs...))
}

// AuthModeNotIn applies the NotIn predicate on the "auth_mode" field.
func AuthModeNotIn(vs ...string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldNotIn(FieldAuthMode, vs...))
}

// AuthModeGT applies the GT predicate on the "auth_mode" field.
func AuthModeGT(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldGT(FieldAuthMode, v))
}

// AuthModeGTE applies the GTE predicate on the "auth_mode" field.
func AuthModeGTE(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldGTE(FieldAuthMode, v))
}

// AuthModeLT applies the LT predicate on the "auth_mode" field.
func AuthModeLT(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldLT(FieldAuthMode, v))
}

// AuthModeLTE applies the LTE predicate on the "auth_mode" field.
func AuthModeLTE(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldLTE(FieldAuthMode, v))
}

// AuthModeContains applies the Contains predicate on the "auth_mode" field.
func AuthModeContains(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldContains(FieldAuthMode, v))
}

// AuthModeHasPrefix applies the HasPrefix predicate on the "auth_mode" field.
func AuthModeHasPrefix(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldHasPrefix(FieldAuthMode, v))
}

// AuthModeHasSuffix applies the HasSuffix predicate on the "auth_mode" field.
func AuthModeHasSuffix(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldHasSuffix(FieldAuthMode, v))
}

// AuthModeEqualFold applies the EqualFold predicate on the "auth_mode" field.
func AuthModeEqualFold(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldEqualFold(FieldAuthMode, v))
}

// AuthModeContainsFold applies the ContainsFold predicate on the "auth_mode" field.
func AuthModeContainsFold(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldContainsFold(FieldAuthMode, v))
}

// AccessTokenEncryptedEQ applies the EQ predicate on the "access_token_encrypted" field.
func AccessTokenEncryptedEQ(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldEQ(FieldAccessTokenEncrypted, v))
}

// AccessTokenEncryptedNEQ applies the NEQ predicate on the "access_token_encrypted" field.
func AccessTokenEncryptedNEQ(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldNEQ(FieldAccessTokenEncrypted, v))
}

// AccessTokenEncryptedIn applies the In predicate on the "access_token_encrypted" field.
func AccessTokenEncryptedIn(vs ...string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldIn(FieldAccessTokenEncrypted, vs...))
}

// AccessTokenEncryptedNotIn applies the NotIn predicate on the "access_token_encrypted" field.
func AccessTokenEncryptedNotIn(vs ...string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldNotIn(FieldAccessTokenEncrypted, vs...))
}

// AccessTokenEncryptedGT applies the GT predicate on the "access_token_encrypted" field.
func AccessTokenEncryptedGT(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldGT(FieldAccessTokenEncrypted, v))
}

// AccessTokenEncryptedGTE applies the GTE predicate on the "access_token_encrypted" field.
func AccessTokenEncryptedGTE(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldGTE(FieldAccessTokenEncrypted, v))
}

// AccessTokenEncryptedLT applies the LT predicate on the "access_token_encrypted" field.
func AccessTokenEncryptedLT(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldLT(FieldAccessTokenEncrypted, v))
}

// AccessTokenEncryptedLTE applies the LTE predicate on the "access_token_encrypted" field.
func AccessTokenEncryptedLTE(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldLTE(FieldAccessTokenEncrypted, v))
}

// AccessTokenEncryptedContains applies the Contains predicate on the "access_token_encrypted" field.
func AccessTokenEncryptedContains(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldContains(FieldAccessTokenEncrypted, v))
}

// AccessTokenEncryptedHasPrefix applies the HasPrefix predicate on the "access_token_encrypted" field.
func AccessTokenEncryptedHasPrefix(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldHasPrefix(FieldAccessTokenEncrypted, v))
}

// AccessTokenEncryptedHasSuffix applies the HasSuffix predicate on the "access_token_encrypted" field.
func AccessTokenEncryptedHasSuffix(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldHasSuffix(FieldAccessTokenEncrypted, v))
}

// AccessTokenEncryptedIsNil applies the IsNil predicate on the "access_token_encrypted" field.
func AccessTokenEncryptedIsNil() predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldIsNull(FieldAccessTokenEncrypted))
}

// AccessTokenEncryptedNotNil applies the NotNil predicate on the "access_token_encrypted" field.
func AccessTokenEncryptedNotNil() predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldNotNull(FieldAccessTokenEncrypted))
}

// AccessTokenEncryptedEqualFold applies the EqualFold predicate on the "access_token_encrypted" field.
func AccessTokenEncryptedEqualFold(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldEqualFold(FieldAccessTokenEncrypted, v))
}

// AccessTokenEncryptedContainsFold applies the ContainsFold predicate on the "access_token_encrypted" field.
func AccessTokenEncryptedContainsFold(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldContainsFold(FieldAccessTokenEncrypted, v))
}

// RefreshTokenEncryptedEQ applies the EQ predicate on the "refresh_token_encrypted" field.
func RefreshTokenEncryptedEQ(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldEQ(FieldRefreshTokenEncrypted, v))
}

// RefreshTokenEncryptedNEQ applies the NEQ predicate on the "refresh_token_encrypted" field.
func RefreshTokenEncryptedNEQ(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldNEQ(FieldRefreshTokenEncrypted, v))
}

// RefreshTokenEncryptedIn applies the In predicate on the "refresh_token_encrypted" field.
func RefreshTokenEncryptedIn(vs ...string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldIn(FieldRefreshTokenEncrypted, vs...))
}

// RefreshTokenEncryptedNotIn applies the NotIn predicate on the "refresh_token_encrypted" field.
func RefreshTokenEncryptedNotIn(vs ...string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldNotIn(FieldRefreshTokenEncrypted, vs...))
}

// RefreshTokenEncryptedGT applies the GT predicate on the "refresh_token_encrypted" field.
func RefreshTokenEncryptedGT(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldGT(FieldRefreshTokenEncrypted, v))
}

// RefreshTokenEncryptedGTE applies the GTE predicate on the "refresh_token_encrypted" field.
func RefreshTokenEncryptedGTE(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldGTE(FieldRefreshTokenEncrypted, v))
}

// RefreshTokenEncryptedLT applies the LT predicate on the "refresh_token_encrypted" field.
func RefreshTokenEncryptedLT(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldLT(FieldRefreshTokenEncrypted, v))
}

// RefreshTokenEncryptedLTE applies the LTE predicate on the "refresh_token_encrypted" field.
func RefreshTokenEncryptedLTE(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldLTE(FieldRefreshTokenEncrypted, v))
}

// RefreshTokenEncryptedContains applies the Contains predicate on the "refresh_token_encrypted" field.
func RefreshTokenEncryptedContains(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldContains(FieldRefreshTokenEncrypted, v))
}

// RefreshTokenEncryptedHasPrefix applies the HasPrefix predicate on the "refresh_token_encrypted" field.
func RefreshTokenEncryptedHasPrefix(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldHasPrefix(FieldRefreshTokenEncrypted, v))
}

// RefreshTokenEncryptedHasSuffix applies the HasSuffix predicate on the "refresh_token_encrypted" field.
func RefreshTokenEncryptedHasSuffix(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldHasSuffix(FieldRefreshTokenEncrypted, v))
}

// RefreshTokenEncryptedIsNil applies the IsNil predicate on the "refresh_token_encrypted" field.
func RefreshTokenEncryptedIsNil() predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldIsNull(FieldRefreshTokenEncrypted))
}

// RefreshTokenEncryptedNotNil applies the NotNil predicate on the "refresh_token_encrypted" field.
func RefreshTokenEncryptedNotNil() predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldNotNull(FieldRefreshTokenEncrypted))
}

// RefreshTokenEncryptedEqualFold applies the EqualFold predicate on the "refresh_token_encrypted" field.
func RefreshTokenEncryptedEqualFold(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldEqualFold(FieldRefreshTokenEncrypted, v))
}

// RefreshTokenEncryptedContainsFold applies the ContainsFold predicate on the "refresh_token_encrypted" field.
func RefreshTokenEncryptedContainsFold(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldContainsFold(FieldRefreshTokenEncrypted, v))
}

// AccessTokenExpiresAtEQ applies the EQ predicate on the "access_token_expires_at" field.
func AccessTokenExpiresAtEQ(v time.Time) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldEQ(FieldAccessTokenExpiresAt, v))
}

// AccessTokenExpiresAtNEQ applies the NEQ predicate on the "access_token_expires_at" field.
func AccessTokenExpiresAtNEQ(v time.Time) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldNEQ(FieldAccessTokenExpiresAt, v))
}

// AccessTokenExpiresAtIn applies the In predicate on the "access_token_expires_at" field.
func AccessTokenExpiresAtIn(vs ...time.Time) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldIn(FieldAccessTokenExpiresAt, vs...))
}

// AccessTokenExpiresAtNotIn applies the NotIn predicate on the "access_token_expires_at" field.
func AccessTokenExpiresAtNotIn(vs ...time.Time) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldNotIn(FieldAccessTokenExpiresAt, vs...))
}

// AccessTokenExpiresAtGT applies the GT predicate on the "access_token_expires_at" field.
func AccessTokenExpiresAtGT(v time.Time) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldGT(FieldAccessTokenExpiresAt, v))
}

// AccessTokenExpiresAtGTE applies the GTE predicate on the "access_token_expires_at" field.
func AccessTokenExpiresAtGTE(v time.Time) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldGTE(FieldAccessTokenExpiresAt, v))
}

// AccessTokenExpiresAtLT applies the LT predicate on the "access_token_expires_at" field.
func AccessTokenExpiresAtLT(v time.Time) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldLT(FieldAccessTokenExpiresAt, v))
}

// AccessTokenExpiresAtLTE applies the LTE predicate on the "access_token_expires_at" field.
func AccessTokenExpiresAtLTE(v time.Time) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldLTE(FieldAccessTokenExpiresAt, v))
}

// AccessTokenExpiresAtIsNil applies the IsNil predicate on the "access_token_expires_at" field.
func AccessTokenExpiresAtIsNil() predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldIsNull(FieldAccessTokenExpiresAt))
}

// AccessTokenExpiresAtNotNil applies the NotNil predicate on the "access_token_expires_at" field.
func AccessTokenExpiresAtNotNil() predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldNotNull(FieldAccessTokenExpiresAt))
}

// LastTokenRefreshAtEQ applies the EQ predicate on the "last_token_refresh_at" field.
func LastTokenRefreshAtEQ(v time.Time) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldEQ(FieldLastTokenRefreshAt, v))
}

// LastTokenRefreshAtNEQ applies the NEQ predicate on the "last_token_refresh_at" field.
func LastTokenRefreshAtNEQ(v time.Time) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldNEQ(FieldLastTokenRefreshAt, v))
}

// LastTokenRefreshAtIn applies the In predicate on the "last_token_refresh_at" field.
func LastTokenRefreshAtIn(vs ...time.Time) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldIn(FieldLastTokenRefreshAt, vs...))
}

// LastTokenRefreshAtNotIn applies the NotIn predicate on the "last_token_refresh_at" field.
func LastTokenRefreshAtNotIn(vs ...time.Time) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldNotIn(FieldLastTokenRefreshAt, vs...))
}

// LastTokenRefreshAtGT applies the GT predicate on the "last_token_refresh_at" field.
func LastTokenRefreshAtGT(v time.Time) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldGT(FieldLastTokenRefreshAt, v))
}

// LastTokenRefreshAtGTE applies the GTE predicate on the "last_token_refresh_at" field.
func LastTokenRefreshAtGTE(v time.Time) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldGTE(FieldLastTokenRefreshAt, v))
}

// LastTokenRefreshAtLT applies the LT predicate on the "last_token_refresh_at" field.
func LastTokenRefreshAtLT(v time.Time) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldLT(FieldLastTokenRefreshAt, v))
}

// LastTokenRefreshAtLTE applies the LTE predicate on the "last_token_refresh_at" field.
func LastTokenRefreshAtLTE(v time.Time) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldLTE(FieldLastTokenRefreshAt, v))
}

// LastTokenRefreshAtIsNil applies the IsNil predicate on the "last_token_refresh_at" field.
func LastTokenRefreshAtIsNil() predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldIsNull(FieldLastTokenRefreshAt))
}

// LastTokenRefreshAtNotNil applies the NotNil predicate on the "last_token_refresh_at" field.
func LastTokenRefreshAtNotNil() predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldNotNull(FieldLastTokenRefreshAt))
}

// LastAuthErrorEQ applies the EQ predicate on the "last_auth_error" field.
func LastAuthErrorEQ(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldEQ(FieldLastAuthError, v))
}

// LastAuthErrorNEQ applies the NEQ predicate on the "last_auth_error" field.
func LastAuthErrorNEQ(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldNEQ(FieldLastAuthError, v))
}

// LastAuthErrorIn applies the In predicate on the "last_auth_error" field.
func LastAuthErrorIn(vs ...string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldIn(FieldLastAuthError, vs...))
}

// LastAuthErrorNotIn applies the NotIn predicate on the "last_auth_error" field.
func LastAuthErrorNotIn(vs ...string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldNotIn(FieldLastAuthError, vs...))
}

// LastAuthErrorGT applies the GT predicate on the "last_auth_error" field.
func LastAuthErrorGT(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldGT(FieldLastAuthError, v))
}

// LastAuthErrorGTE applies the GTE predicate on the "last_auth_error" field.
func LastAuthErrorGTE(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldGTE(FieldLastAuthError, v))
}

// LastAuthErrorLT applies the LT predicate on the "last_auth_error" field.
func LastAuthErrorLT(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldLT(FieldLastAuthError, v))
}

// LastAuthErrorLTE applies the LTE predicate on the "last_auth_error" field.
func LastAuthErrorLTE(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldLTE(FieldLastAuthError, v))
}

// LastAuthErrorContains applies the Contains predicate on the "last_auth_error" field.
func LastAuthErrorContains(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldContains(FieldLastAuthError, v))
}

// LastAuthErrorHasPrefix applies the HasPrefix predicate on the "last_auth_error" field.
func LastAuthErrorHasPrefix(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldHasPrefix(FieldLastAuthError, v))
}

// LastAuthErrorHasSuffix applies the HasSuffix predicate on the "last_auth_error" field.
func LastAuthErrorHasSuffix(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldHasSuffix(FieldLastAuthError, v))
}

// LastAuthErrorIsNil applies the IsNil predicate on the "last_auth_error" field.
func LastAuthErrorIsNil() predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldIsNull(FieldLastAuthError))
}

// LastAuthErrorNotNil applies the NotNil predicate on the "last_auth_error" field.
func LastAuthErrorNotNil() predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldNotNull(FieldLastAuthError))
}

// LastAuthErrorEqualFold applies the EqualFold predicate on the "last_auth_error" field.
func LastAuthErrorEqualFold(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldEqualFold(FieldLastAuthError, v))
}

// LastAuthErrorContainsFold applies the ContainsFold predicate on the "last_auth_error" field.
func LastAuthErrorContainsFold(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldContainsFold(FieldLastAuthError, v))
}

// APIPathKeysEQ applies the EQ predicate on the "api_path_keys" field.
func APIPathKeysEQ(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldEQ(FieldAPIPathKeys, v))
}

// APIPathKeysNEQ applies the NEQ predicate on the "api_path_keys" field.
func APIPathKeysNEQ(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldNEQ(FieldAPIPathKeys, v))
}

// APIPathKeysIn applies the In predicate on the "api_path_keys" field.
func APIPathKeysIn(vs ...string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldIn(FieldAPIPathKeys, vs...))
}

// APIPathKeysNotIn applies the NotIn predicate on the "api_path_keys" field.
func APIPathKeysNotIn(vs ...string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldNotIn(FieldAPIPathKeys, vs...))
}

// APIPathKeysGT applies the GT predicate on the "api_path_keys" field.
func APIPathKeysGT(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldGT(FieldAPIPathKeys, v))
}

// APIPathKeysGTE applies the GTE predicate on the "api_path_keys" field.
func APIPathKeysGTE(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldGTE(FieldAPIPathKeys, v))
}

// APIPathKeysLT applies the LT predicate on the "api_path_keys" field.
func APIPathKeysLT(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldLT(FieldAPIPathKeys, v))
}

// APIPathKeysLTE applies the LTE predicate on the "api_path_keys" field.
func APIPathKeysLTE(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldLTE(FieldAPIPathKeys, v))
}

// APIPathKeysContains applies the Contains predicate on the "api_path_keys" field.
func APIPathKeysContains(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldContains(FieldAPIPathKeys, v))
}

// APIPathKeysHasPrefix applies the HasPrefix predicate on the "api_path_keys" field.
func APIPathKeysHasPrefix(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldHasPrefix(FieldAPIPathKeys, v))
}

// APIPathKeysHasSuffix applies the HasSuffix predicate on the "api_path_keys" field.
func APIPathKeysHasSuffix(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldHasSuffix(FieldAPIPathKeys, v))
}

// APIPathKeysIsNil applies the IsNil predicate on the "api_path_keys" field.
func APIPathKeysIsNil() predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldIsNull(FieldAPIPathKeys))
}

// APIPathKeysNotNil applies the NotNil predicate on the "api_path_keys" field.
func APIPathKeysNotNil() predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldNotNull(FieldAPIPathKeys))
}

// APIPathKeysEqualFold applies the EqualFold predicate on the "api_path_keys" field.
func APIPathKeysEqualFold(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldEqualFold(FieldAPIPathKeys, v))
}

// APIPathKeysContainsFold applies the ContainsFold predicate on the "api_path_keys" field.
func APIPathKeysContainsFold(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldContainsFold(FieldAPIPathKeys, v))
}

// APIPathGroupsEQ applies the EQ predicate on the "api_path_groups" field.
func APIPathGroupsEQ(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldEQ(FieldAPIPathGroups, v))
}

// APIPathGroupsNEQ applies the NEQ predicate on the "api_path_groups" field.
func APIPathGroupsNEQ(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldNEQ(FieldAPIPathGroups, v))
}

// APIPathGroupsIn applies the In predicate on the "api_path_groups" field.
func APIPathGroupsIn(vs ...string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldIn(FieldAPIPathGroups, vs...))
}

// APIPathGroupsNotIn applies the NotIn predicate on the "api_path_groups" field.
func APIPathGroupsNotIn(vs ...string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldNotIn(FieldAPIPathGroups, vs...))
}

// APIPathGroupsGT applies the GT predicate on the "api_path_groups" field.
func APIPathGroupsGT(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldGT(FieldAPIPathGroups, v))
}

// APIPathGroupsGTE applies the GTE predicate on the "api_path_groups" field.
func APIPathGroupsGTE(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldGTE(FieldAPIPathGroups, v))
}

// APIPathGroupsLT applies the LT predicate on the "api_path_groups" field.
func APIPathGroupsLT(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldLT(FieldAPIPathGroups, v))
}

// APIPathGroupsLTE applies the LTE predicate on the "api_path_groups" field.
func APIPathGroupsLTE(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldLTE(FieldAPIPathGroups, v))
}

// APIPathGroupsContains applies the Contains predicate on the "api_path_groups" field.
func APIPathGroupsContains(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldContains(FieldAPIPathGroups, v))
}

// APIPathGroupsHasPrefix applies the HasPrefix predicate on the "api_path_groups" field.
func APIPathGroupsHasPrefix(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldHasPrefix(FieldAPIPathGroups, v))
}

// APIPathGroupsHasSuffix applies the HasSuffix predicate on the "api_path_groups" field.
func APIPathGroupsHasSuffix(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldHasSuffix(FieldAPIPathGroups, v))
}

// APIPathGroupsIsNil applies the IsNil predicate on the "api_path_groups" field.
func APIPathGroupsIsNil() predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldIsNull(FieldAPIPathGroups))
}

// APIPathGroupsNotNil applies the NotNil predicate on the "api_path_groups" field.
func APIPathGroupsNotNil() predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldNotNull(FieldAPIPathGroups))
}

// APIPathGroupsEqualFold applies the EqualFold predicate on the "api_path_groups" field.
func APIPathGroupsEqualFold(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldEqualFold(FieldAPIPathGroups, v))
}

// APIPathGroupsContainsFold applies the ContainsFold predicate on the "api_path_groups" field.
func APIPathGroupsContainsFold(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldContainsFold(FieldAPIPathGroups, v))
}

// LastSyncAtEQ applies the EQ predicate on the "last_sync_at" field.
func LastSyncAtEQ(v time.Time) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldEQ(FieldLastSyncAt, v))
}

// LastSyncAtNEQ applies the NEQ predicate on the "last_sync_at" field.
func LastSyncAtNEQ(v time.Time) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldNEQ(FieldLastSyncAt, v))
}

// LastSyncAtIn applies the In predicate on the "last_sync_at" field.
func LastSyncAtIn(vs ...time.Time) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldIn(FieldLastSyncAt, vs...))
}

// LastSyncAtNotIn applies the NotIn predicate on the "last_sync_at" field.
func LastSyncAtNotIn(vs ...time.Time) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldNotIn(FieldLastSyncAt, vs...))
}

// LastSyncAtGT applies the GT predicate on the "last_sync_at" field.
func LastSyncAtGT(v time.Time) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldGT(FieldLastSyncAt, v))
}

// LastSyncAtGTE applies the GTE predicate on the "last_sync_at" field.
func LastSyncAtGTE(v time.Time) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldGTE(FieldLastSyncAt, v))
}

// LastSyncAtLT applies the LT predicate on the "last_sync_at" field.
func LastSyncAtLT(v time.Time) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldLT(FieldLastSyncAt, v))
}

// LastSyncAtLTE applies the LTE predicate on the "last_sync_at" field.
func LastSyncAtLTE(v time.Time) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldLTE(FieldLastSyncAt, v))
}

// LastSyncAtIsNil applies the IsNil predicate on the "last_sync_at" field.
func LastSyncAtIsNil() predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldIsNull(FieldLastSyncAt))
}

// LastSyncAtNotNil applies the NotNil predicate on the "last_sync_at" field.
func LastSyncAtNotNil() predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldNotNull(FieldLastSyncAt))
}

// LastSyncStatusEQ applies the EQ predicate on the "last_sync_status" field.
func LastSyncStatusEQ(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldEQ(FieldLastSyncStatus, v))
}

// LastSyncStatusNEQ applies the NEQ predicate on the "last_sync_status" field.
func LastSyncStatusNEQ(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldNEQ(FieldLastSyncStatus, v))
}

// LastSyncStatusIn applies the In predicate on the "last_sync_status" field.
func LastSyncStatusIn(vs ...string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldIn(FieldLastSyncStatus, vs...))
}

// LastSyncStatusNotIn applies the NotIn predicate on the "last_sync_status" field.
func LastSyncStatusNotIn(vs ...string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldNotIn(FieldLastSyncStatus, vs...))
}

// LastSyncStatusGT applies the GT predicate on the "last_sync_status" field.
func LastSyncStatusGT(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldGT(FieldLastSyncStatus, v))
}

// LastSyncStatusGTE applies the GTE predicate on the "last_sync_status" field.
func LastSyncStatusGTE(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldGTE(FieldLastSyncStatus, v))
}

// LastSyncStatusLT applies the LT predicate on the "last_sync_status" field.
func LastSyncStatusLT(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldLT(FieldLastSyncStatus, v))
}

// LastSyncStatusLTE applies the LTE predicate on the "last_sync_status" field.
func LastSyncStatusLTE(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldLTE(FieldLastSyncStatus, v))
}

// LastSyncStatusContains applies the Contains predicate on the "last_sync_status" field.
func LastSyncStatusContains(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldContains(FieldLastSyncStatus, v))
}

// LastSyncStatusHasPrefix applies the HasPrefix predicate on the "last_sync_status" field.
func LastSyncStatusHasPrefix(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldHasPrefix(FieldLastSyncStatus, v))
}

// LastSyncStatusHasSuffix applies the HasSuffix predicate on the "last_sync_status" field.
func LastSyncStatusHasSuffix(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldHasSuffix(FieldLastSyncStatus, v))
}

// LastSyncStatusIsNil applies the IsNil predicate on the "last_sync_status" field.
func LastSyncStatusIsNil() predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldIsNull(FieldLastSyncStatus))
}

// LastSyncStatusNotNil applies the NotNil predicate on the "last_sync_status" field.
func LastSyncStatusNotNil() predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldNotNull(FieldLastSyncStatus))
}

// LastSyncStatusEqualFold applies the EqualFold predicate on the "last_sync_status" field.
func LastSyncStatusEqualFold(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldEqualFold(FieldLastSyncStatus, v))
}

// LastSyncStatusContainsFold applies the ContainsFold predicate on the "last_sync_status" field.
func LastSyncStatusContainsFold(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldContainsFold(FieldLastSyncStatus, v))
}

// LastSyncErrorEQ applies the EQ predicate on the "last_sync_error" field.
func LastSyncErrorEQ(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldEQ(FieldLastSyncError, v))
}

// LastSyncErrorNEQ applies the NEQ predicate on the "last_sync_error" field.
func LastSyncErrorNEQ(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldNEQ(FieldLastSyncError, v))
}

// LastSyncErrorIn applies the In predicate on the "last_sync_error" field.
func LastSyncErrorIn(vs ...string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldIn(FieldLastSyncError, vs...))
}

// LastSyncErrorNotIn applies the NotIn predicate on the "last_sync_error" field.
func LastSyncErrorNotIn(vs ...string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldNotIn(FieldLastSyncError, vs...))
}

// LastSyncErrorGT applies the GT predicate on the "last_sync_error" field.
func LastSyncErrorGT(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldGT(FieldLastSyncError, v))
}

// LastSyncErrorGTE applies the GTE predicate on the "last_sync_error" field.
func LastSyncErrorGTE(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldGTE(FieldLastSyncError, v))
}

// LastSyncErrorLT applies the LT predicate on the "last_sync_error" field.
func LastSyncErrorLT(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldLT(FieldLastSyncError, v))
}

// LastSyncErrorLTE applies the LTE predicate on the "last_sync_error" field.
func LastSyncErrorLTE(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldLTE(FieldLastSyncError, v))
}

// LastSyncErrorContains applies the Contains predicate on the "last_sync_error" field.
func LastSyncErrorContains(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldContains(FieldLastSyncError, v))
}

// LastSyncErrorHasPrefix applies the HasPrefix predicate on the "last_sync_error" field.
func LastSyncErrorHasPrefix(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldHasPrefix(FieldLastSyncError, v))
}

// LastSyncErrorHasSuffix applies the HasSuffix predicate on the "last_sync_error" field.
func LastSyncErrorHasSuffix(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldHasSuffix(FieldLastSyncError, v))
}

// LastSyncErrorIsNil applies the IsNil predicate on the "last_sync_error" field.
func LastSyncErrorIsNil() predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldIsNull(FieldLastSyncError))
}

// LastSyncErrorNotNil applies the NotNil predicate on the "last_sync_error" field.
func LastSyncErrorNotNil() predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldNotNull(FieldLastSyncError))
}

// LastSyncErrorEqualFold applies the EqualFold predicate on the "last_sync_error" field.
func LastSyncErrorEqualFold(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldEqualFold(FieldLastSyncError, v))
}

// LastSyncErrorContainsFold applies the ContainsFold predicate on the "last_sync_error" field.
func LastSyncErrorContainsFold(v string) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.FieldContainsFold(FieldLastSyncError, v))
}

// HasProxy applies the HasEdge predicate on the "proxy" edge.
func HasProxy() predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ProxyTable, ProxyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProxyWith applies the HasEdge predicate on the "proxy" edge with a given conditions (other predicates).
func HasProxyWith(preds ...predicate.Proxy) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(func(s *sql.Selector) {
		step := newProxyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAccounts applies the HasEdge predicate on the "accounts" edge.
func HasAccounts() predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AccountsTable, AccountsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountsWith applies the HasEdge predicate on the "accounts" edge with a given conditions (other predicates).
func HasAccountsWith(preds ...predicate.Account) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(func(s *sql.Selector) {
		step := newAccountsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasOptimizeSchedule applies the HasEdge predicate on the "optimize_schedule" edge.
func HasOptimizeSchedule() predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, OptimizeScheduleTable, OptimizeScheduleColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOptimizeScheduleWith applies the HasEdge predicate on the "optimize_schedule" edge with a given conditions (other predicates).
func HasOptimizeScheduleWith(preds ...predicate.Sub2APIOptimizeSchedule) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(func(s *sql.Selector) {
		step := newOptimizeScheduleStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasOptimizeLogs applies the HasEdge predicate on the "optimize_logs" edge.
func HasOptimizeLogs() predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, OptimizeLogsTable, OptimizeLogsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOptimizeLogsWith applies the HasEdge predicate on the "optimize_logs" edge with a given conditions (other predicates).
func HasOptimizeLogsWith(preds ...predicate.Sub2APIOptimizeLog) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(func(s *sql.Selector) {
		step := newOptimizeLogsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProbeConfig applies the HasEdge predicate on the "probe_config" edge.
func HasProbeConfig() predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, ProbeConfigTable, ProbeConfigColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProbeConfigWith applies the HasEdge predicate on the "probe_config" edge with a given conditions (other predicates).
func HasProbeConfigWith(preds ...predicate.Sub2APIProviderProbeConfig) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(func(s *sql.Selector) {
		step := newProbeConfigStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProbeRuns applies the HasEdge predicate on the "probe_runs" edge.
func HasProbeRuns() predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ProbeRunsTable, ProbeRunsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProbeRunsWith applies the HasEdge predicate on the "probe_runs" edge with a given conditions (other predicates).
func HasProbeRunsWith(preds ...predicate.Sub2APIProviderProbeRun) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(func(s *sql.Selector) {
		step := newProbeRunsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProbeTargets applies the HasEdge predicate on the "probe_targets" edge.
func HasProbeTargets() predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ProbeTargetsTable, ProbeTargetsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProbeTargetsWith applies the HasEdge predicate on the "probe_targets" edge with a given conditions (other predicates).
func HasProbeTargetsWith(preds ...predicate.Sub2APIProviderProbeTarget) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(func(s *sql.Selector) {
		step := newProbeTargetsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Sub2APIProvider) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Sub2APIProvider) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Sub2APIProvider) predicate.Sub2APIProvider {
	return predicate.Sub2APIProvider(sql.NotPredicates(p))
}
