// Code generated by ent, DO NOT EDIT.

package sub2apiproviderprobetargetrun

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldLTE(FieldID, id))
}

// TargetID applies equality check predicate on the "target_id" field. It's identical to TargetIDEQ.
func TargetID(v int64) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldEQ(FieldTargetID, v))
}

// ProviderID applies equality check predicate on the "provider_id" field. It's identical to ProviderIDEQ.
func ProviderID(v int64) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldEQ(FieldProviderID, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldEQ(FieldAccountID, v))
}

// ProviderAPIKeyID applies equality check predicate on the "provider_api_key_id" field. It's identical to ProviderAPIKeyIDEQ.
func ProviderAPIKeyID(v int64) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldEQ(FieldProviderAPIKeyID, v))
}

// RemoteGroupID applies equality check predicate on the "remote_group_id" field. It's identical to RemoteGroupIDEQ.
func RemoteGroupID(v int64) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldEQ(FieldRemoteGroupID, v))
}

// RemoteGroupName applies equality check predicate on the "remote_group_name" field. It's identical to RemoteGroupNameEQ.
func RemoteGroupName(v string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldEQ(FieldRemoteGroupName, v))
}

// Platform applies equality check predicate on the "platform" field. It's identical to PlatformEQ.
func Platform(v string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldEQ(FieldPlatform, v))
}

// ModelID applies equality check predicate on the "model_id" field. It's identical to ModelIDEQ.
func ModelID(v string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldEQ(FieldModelID, v))
}

// LatencyMs applies equality check predicate on the "latency_ms" field. It's identical to LatencyMsEQ.
func LatencyMs(v int) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldEQ(FieldLatencyMs, v))
}

// TrafficRequestCount applies equality check predicate on the "traffic_request_count" field. It's identical to TrafficRequestCountEQ.
func TrafficRequestCount(v int) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldEQ(FieldTrafficRequestCount, v))
}

// TrafficSuccessRate applies equality check predicate on the "traffic_success_rate" field. It's identical to TrafficSuccessRateEQ.
func TrafficSuccessRate(v float64) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldEQ(FieldTrafficSuccessRate, v))
}

// TrafficP95LatencyMs applies equality check predicate on the "traffic_p95_latency_ms" field. It's identical to TrafficP95LatencyMsEQ.
func TrafficP95LatencyMs(v int) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldEQ(FieldTrafficP95LatencyMs, v))
}

// ErrorCategory applies equality check predicate on the "error_category" field. It's identical to ErrorCategoryEQ.
func ErrorCategory(v string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldEQ(FieldErrorCategory, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldEQ(FieldErrorMessage, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldEQ(FieldStartedAt, v))
}

// FinishedAt applies equality check predicate on the "finished_at" field. It's identical to FinishedAtEQ.
func FinishedAt(v time.Time) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldEQ(FieldFinishedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldEQ(FieldCreatedAt, v))
}

// TargetIDEQ applies the EQ predicate on the "target_id" field.
func TargetIDEQ(v int64) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldEQ(FieldTargetID, v))
}

// TargetIDNEQ applies the NEQ predicate on the "target_id" field.
func TargetIDNEQ(v int64) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldNEQ(FieldTargetID, v))
}

// TargetIDIn applies the In predicate on the "target_id" field.
func TargetIDIn(vs ...int64) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldIn(FieldTargetID, vs...))
}

// TargetIDNotIn applies the NotIn predicate on the "target_id" field.
func TargetIDNotIn(vs ...int64) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldNotIn(FieldTargetID, vs...))
}

// ProviderIDEQ applies the EQ predicate on the "provider_id" field.
func ProviderIDEQ(v int64) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldEQ(FieldProviderID, v))
}

// ProviderIDNEQ applies the NEQ predicate on the "provider_id" field.
func ProviderIDNEQ(v int64) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldNEQ(FieldProviderID, v))
}

// ProviderIDIn applies the In predicate on the "provider_id" field.
func ProviderIDIn(vs ...int64) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldIn(FieldProviderID, vs...))
}

// ProviderIDNotIn applies the NotIn predicate on the "provider_id" field.
func ProviderIDNotIn(vs ...int64) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldNotIn(FieldProviderID, vs...))
}

// ProviderIDGT applies the GT predicate on the "provider_id" field.
func ProviderIDGT(v int64) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldGT(FieldProviderID, v))
}

// ProviderIDGTE applies the GTE predicate on the "provider_id" field.
func ProviderIDGTE(v int64) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldGTE(FieldProviderID, v))
}

// ProviderIDLT applies the LT predicate on the "provider_id" field.
func ProviderIDLT(v int64) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldLT(FieldProviderID, v))
}

// ProviderIDLTE applies the LTE predicate on the "provider_id" field.
func ProviderIDLTE(v int64) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldLTE(FieldProviderID, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v int64) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v int64) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v int64) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v int64) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldLTE(FieldAccountID, v))
}

// ProviderAPIKeyIDEQ applies the EQ predicate on the "provider_api_key_id" field.
func ProviderAPIKeyIDEQ(v int64) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldEQ(FieldProviderAPIKeyID, v))
}

// ProviderAPIKeyIDNEQ applies the NEQ predicate on the "provider_api_key_id" field.
func ProviderAPIKeyIDNEQ(v int64) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldNEQ(FieldProviderAPIKeyID, v))
}

// ProviderAPIKeyIDIn applies the In predicate on the "provider_api_key_id" field.
func ProviderAPIKeyIDIn(vs ...int64) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldIn(FieldProviderAPIKeyID, vs...))
}

// ProviderAPIKeyIDNotIn applies the NotIn predicate on the "provider_api_key_id" field.
func ProviderAPIKeyIDNotIn(vs ...int64) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldNotIn(FieldProviderAPIKeyID, vs...))
}

// ProviderAPIKeyIDGT applies the GT predicate on the "provider_api_key_id" field.
func ProviderAPIKeyIDGT(v int64) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldGT(FieldProviderAPIKeyID, v))
}

// ProviderAPIKeyIDGTE applies the GTE predicate on the "provider_api_key_id" field.
func ProviderAPIKeyIDGTE(v int64) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldGTE(FieldProviderAPIKeyID, v))
}

// ProviderAPIKeyIDLT applies the LT predicate on the "provider_api_key_id" field.
func ProviderAPIKeyIDLT(v int64) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldLT(FieldProviderAPIKeyID, v))
}

// ProviderAPIKeyIDLTE applies the LTE predicate on the "provider_api_key_id" field.
func ProviderAPIKeyIDLTE(v int64) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldLTE(FieldProviderAPIKeyID, v))
}

// ProviderAPIKeyIDIsNil applies the IsNil predicate on the "provider_api_key_id" field.
func ProviderAPIKeyIDIsNil() predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldIsNull(FieldProviderAPIKeyID))
}

// ProviderAPIKeyIDNotNil applies the NotNil predicate on the "provider_api_key_id" field.
func ProviderAPIKeyIDNotNil() predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldNotNull(FieldProviderAPIKeyID))
}

// RemoteGroupIDEQ applies the EQ predicate on the "remote_group_id" field.
func RemoteGroupIDEQ(v int64) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldEQ(FieldRemoteGroupID, v))
}

// RemoteGroupIDNEQ applies the NEQ predicate on the "remote_group_id" field.
func RemoteGroupIDNEQ(v int64) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldNEQ(FieldRemoteGroupID, v))
}

// RemoteGroupIDIn applies the In predicate on the "remote_group_id" field.
func RemoteGroupIDIn(vs ...int64) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldIn(FieldRemoteGroupID, vs...))
}

// RemoteGroupIDNotIn applies the NotIn predicate on the "remote_group_id" field.
func RemoteGroupIDNotIn(vs ...int64) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldNotIn(FieldRemoteGroupID, vs...))
}

// RemoteGroupIDGT applies the GT predicate on the "remote_group_id" field.
func RemoteGroupIDGT(v int64) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldGT(FieldRemoteGroupID, v))
}

// RemoteGroupIDGTE applies the GTE predicate on the "remote_group_id" field.
func RemoteGroupIDGTE(v int64) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldGTE(FieldRemoteGroupID, v))
}

// RemoteGroupIDLT applies the LT predicate on the "remote_group_id" field.
func RemoteGroupIDLT(v int64) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldLT(FieldRemoteGroupID, v))
}

// RemoteGroupIDLTE applies the LTE predicate on the "remote_group_id" field.
func RemoteGroupIDLTE(v int64) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldLTE(FieldRemoteGroupID, v))
}

// RemoteGroupIDIsNil applies the IsNil predicate on the "remote_group_id" field.
func RemoteGroupIDIsNil() predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldIsNull(FieldRemoteGroupID))
}

// RemoteGroupIDNotNil applies the NotNil predicate on the "remote_group_id" field.
func RemoteGroupIDNotNil() predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldNotNull(FieldRemoteGroupID))
}

// RemoteGroupNameEQ applies the EQ predicate on the "remote_group_name" field.
func RemoteGroupNameEQ(v string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldEQ(FieldRemoteGroupName, v))
}

// RemoteGroupNameNEQ applies the NEQ predicate on the "remote_group_name" field.
func RemoteGroupNameNEQ(v string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldNEQ(FieldRemoteGroupName, v))
}

// RemoteGroupNameIn applies the In predicate on the "remote_group_name" field.
func RemoteGroupNameIn(vs ...string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldIn(FieldRemoteGroupName, vs...))
}

// RemoteGroupNameNotIn applies the NotIn predicate on the "remote_group_name" field.
func RemoteGroupNameNotIn(vs ...string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldNotIn(FieldRemoteGroupName, vs...))
}

// RemoteGroupNameGT applies the GT predicate on the "remote_group_name" field.
func RemoteGroupNameGT(v string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldGT(FieldRemoteGroupName, v))
}

// RemoteGroupNameGTE applies the GTE predicate on the "remote_group_name" field.
func RemoteGroupNameGTE(v string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldGTE(FieldRemoteGroupName, v))
}

// RemoteGroupNameLT applies the LT predicate on the "remote_group_name" field.
func RemoteGroupNameLT(v string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldLT(FieldRemoteGroupName, v))
}

// RemoteGroupNameLTE applies the LTE predicate on the "remote_group_name" field.
func RemoteGroupNameLTE(v string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldLTE(FieldRemoteGroupName, v))
}

// RemoteGroupNameContains applies the Contains predicate on the "remote_group_name" field.
func RemoteGroupNameContains(v string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldContains(FieldRemoteGroupName, v))
}

// RemoteGroupNameHasPrefix applies the HasPrefix predicate on the "remote_group_name" field.
func RemoteGroupNameHasPrefix(v string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldHasPrefix(FieldRemoteGroupName, v))
}

// RemoteGroupNameHasSuffix applies the HasSuffix predicate on the "remote_group_name" field.
func RemoteGroupNameHasSuffix(v string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldHasSuffix(FieldRemoteGroupName, v))
}

// RemoteGroupNameIsNil applies the IsNil predicate on the "remote_group_name" field.
func RemoteGroupNameIsNil() predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldIsNull(FieldRemoteGroupName))
}

// RemoteGroupNameNotNil applies the NotNil predicate on the "remote_group_name" field.
func RemoteGroupNameNotNil() predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldNotNull(FieldRemoteGroupName))
}

// RemoteGroupNameEqualFold applies the EqualFold predicate on the "remote_group_name" field.
func RemoteGroupNameEqualFold(v string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldEqualFold(FieldRemoteGroupName, v))
}

// RemoteGroupNameContainsFold applies the ContainsFold predicate on the "remote_group_name" field.
func RemoteGroupNameContainsFold(v string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldContainsFold(FieldRemoteGroupName, v))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldNotIn(FieldPlatform, vs...))
}

// PlatformGT applies the GT predicate on the "platform" field.
func PlatformGT(v string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldGT(FieldPlatform, v))
}

// PlatformGTE applies the GTE predicate on the "platform" field.
func PlatformGTE(v string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldGTE(FieldPlatform, v))
}

// PlatformLT applies the LT predicate on the "platform" field.
func PlatformLT(v string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldLT(FieldPlatform, v))
}

// PlatformLTE applies the LTE predicate on the "platform" field.
func PlatformLTE(v string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldLTE(FieldPlatform, v))
}

// PlatformContains applies the Contains predicate on the "platform" field.
func PlatformContains(v string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldContains(FieldPlatform, v))
}

// PlatformHasPrefix applies the HasPrefix predicate on the "platform" field.
func PlatformHasPrefix(v string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldHasPrefix(FieldPlatform, v))
}

// PlatformHasSuffix applies the HasSuffix predicate on the "platform" field.
func PlatformHasSuffix(v string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldHasSuffix(FieldPlatform, v))
}

// PlatformEqualFold applies the EqualFold predicate on the "platform" field.
func PlatformEqualFold(v string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldEqualFold(FieldPlatform, v))
}

// PlatformContainsFold applies the ContainsFold predicate on the "platform" field.
func PlatformContainsFold(v string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldContainsFold(FieldPlatform, v))
}

// ModelIDEQ applies the EQ predicate on the "model_id" field.
func ModelIDEQ(v string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldEQ(FieldModelID, v))
}

// ModelIDNEQ applies the NEQ predicate on the "model_id" field.
func ModelIDNEQ(v string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldNEQ(FieldModelID, v))
}

// ModelIDIn applies the In predicate on the "model_id" field.
func ModelIDIn(vs ...string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldIn(FieldModelID, vs...))
}

// ModelIDNotIn applies the NotIn predicate on the "model_id" field.
func ModelIDNotIn(vs ...string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldNotIn(FieldModelID, vs...))
}

// ModelIDGT applies the GT predicate on the "model_id" field.
func ModelIDGT(v string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldGT(FieldModelID, v))
}

// ModelIDGTE applies the GTE predicate on the "model_id" field.
func ModelIDGTE(v string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldGTE(FieldModelID, v))
}

// ModelIDLT applies the LT predicate on the "model_id" field.
func ModelIDLT(v string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldLT(FieldModelID, v))
}

// ModelIDLTE applies the LTE predicate on the "model_id" field.
func ModelIDLTE(v string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldLTE(FieldModelID, v))
}

// ModelIDContains applies the Contains predicate on the "model_id" field.
func ModelIDContains(v string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldContains(FieldModelID, v))
}

// ModelIDHasPrefix applies the HasPrefix predicate on the "model_id" field.
func ModelIDHasPrefix(v string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldHasPrefix(FieldModelID, v))
}

// ModelIDHasSuffix applies the HasSuffix predicate on the "model_id" field.
func ModelIDHasSuffix(v string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldHasSuffix(FieldModelID, v))
}

// ModelIDIsNil applies the IsNil predicate on the "model_id" field.
func ModelIDIsNil() predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldIsNull(FieldModelID))
}

// ModelIDNotNil applies the NotNil predicate on the "model_id" field.
func ModelIDNotNil() predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldNotNull(FieldModelID))
}

// ModelIDEqualFold applies the EqualFold predicate on the "model_id" field.
func ModelIDEqualFold(v string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldEqualFold(FieldModelID, v))
}

// ModelIDContainsFold applies the ContainsFold predicate on the "model_id" field.
func ModelIDContainsFold(v string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldContainsFold(FieldModelID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldNotIn(FieldStatus, vs...))
}

// LatencyMsEQ applies the EQ predicate on the "latency_ms" field.
func LatencyMsEQ(v int) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldEQ(FieldLatencyMs, v))
}

// LatencyMsNEQ applies the NEQ predicate on the "latency_ms" field.
func LatencyMsNEQ(v int) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldNEQ(FieldLatencyMs, v))
}

// LatencyMsIn applies the In predicate on the "latency_ms" field.
func LatencyMsIn(vs ...int) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldIn(FieldLatencyMs, vs...))
}

// LatencyMsNotIn applies the NotIn predicate on the "latency_ms" field.
func LatencyMsNotIn(vs ...int) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldNotIn(FieldLatencyMs, vs...))
}

// LatencyMsGT applies the GT predicate on the "latency_ms" field.
func LatencyMsGT(v int) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldGT(FieldLatencyMs, v))
}

// LatencyMsGTE applies the GTE predicate on the "latency_ms" field.
func LatencyMsGTE(v int) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldGTE(FieldLatencyMs, v))
}

// LatencyMsLT applies the LT predicate on the "latency_ms" field.
func LatencyMsLT(v int) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldLT(FieldLatencyMs, v))
}

// LatencyMsLTE applies the LTE predicate on the "latency_ms" field.
func LatencyMsLTE(v int) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldLTE(FieldLatencyMs, v))
}

// LatencyMsIsNil applies the IsNil predicate on the "latency_ms" field.
func LatencyMsIsNil() predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldIsNull(FieldLatencyMs))
}

// LatencyMsNotNil applies the NotNil predicate on the "latency_ms" field.
func LatencyMsNotNil() predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldNotNull(FieldLatencyMs))
}

// TrafficRequestCountEQ applies the EQ predicate on the "traffic_request_count" field.
func TrafficRequestCountEQ(v int) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldEQ(FieldTrafficRequestCount, v))
}

// TrafficRequestCountNEQ applies the NEQ predicate on the "traffic_request_count" field.
func TrafficRequestCountNEQ(v int) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldNEQ(FieldTrafficRequestCount, v))
}

// TrafficRequestCountIn applies the In predicate on the "traffic_request_count" field.
func TrafficRequestCountIn(vs ...int) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldIn(FieldTrafficRequestCount, vs...))
}

// TrafficRequestCountNotIn applies the NotIn predicate on the "traffic_request_count" field.
func TrafficRequestCountNotIn(vs ...int) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldNotIn(FieldTrafficRequestCount, vs...))
}

// TrafficRequestCountGT applies the GT predicate on the "traffic_request_count" field.
func TrafficRequestCountGT(v int) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldGT(FieldTrafficRequestCount, v))
}

// TrafficRequestCountGTE applies the GTE predicate on the "traffic_request_count" field.
func TrafficRequestCountGTE(v int) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldGTE(FieldTrafficRequestCount, v))
}

// TrafficRequestCountLT applies the LT predicate on the "traffic_request_count" field.
func TrafficRequestCountLT(v int) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldLT(FieldTrafficRequestCount, v))
}

// TrafficRequestCountLTE applies the LTE predicate on the "traffic_request_count" field.
func TrafficRequestCountLTE(v int) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldLTE(FieldTrafficRequestCount, v))
}

// TrafficSuccessRateEQ applies the EQ predicate on the "traffic_success_rate" field.
func TrafficSuccessRateEQ(v float64) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldEQ(FieldTrafficSuccessRate, v))
}

// TrafficSuccessRateNEQ applies the NEQ predicate on the "traffic_success_rate" field.
func TrafficSuccessRateNEQ(v float64) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldNEQ(FieldTrafficSuccessRate, v))
}

// TrafficSuccessRateIn applies the In predicate on the "traffic_success_rate" field.
func TrafficSuccessRateIn(vs ...float64) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldIn(FieldTrafficSuccessRate, vs...))
}

// TrafficSuccessRateNotIn applies the NotIn predicate on the "traffic_success_rate" field.
func TrafficSuccessRateNotIn(vs ...float64) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldNotIn(FieldTrafficSuccessRate, vs...))
}

// TrafficSuccessRateGT applies the GT predicate on the "traffic_success_rate" field.
func TrafficSuccessRateGT(v float64) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldGT(FieldTrafficSuccessRate, v))
}

// TrafficSuccessRateGTE applies the GTE predicate on the "traffic_success_rate" field.
func TrafficSuccessRateGTE(v float64) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldGTE(FieldTrafficSuccessRate, v))
}

// TrafficSuccessRateLT applies the LT predicate on the "traffic_success_rate" field.
func TrafficSuccessRateLT(v float64) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldLT(FieldTrafficSuccessRate, v))
}

// TrafficSuccessRateLTE applies the LTE predicate on the "traffic_success_rate" field.
func TrafficSuccessRateLTE(v float64) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldLTE(FieldTrafficSuccessRate, v))
}

// TrafficSuccessRateIsNil applies the IsNil predicate on the "traffic_success_rate" field.
func TrafficSuccessRateIsNil() predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldIsNull(FieldTrafficSuccessRate))
}

// TrafficSuccessRateNotNil applies the NotNil predicate on the "traffic_success_rate" field.
func TrafficSuccessRateNotNil() predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldNotNull(FieldTrafficSuccessRate))
}

// TrafficP95LatencyMsEQ applies the EQ predicate on the "traffic_p95_latency_ms" field.
func TrafficP95LatencyMsEQ(v int) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldEQ(FieldTrafficP95LatencyMs, v))
}

// TrafficP95LatencyMsNEQ applies the NEQ predicate on the "traffic_p95_latency_ms" field.
func TrafficP95LatencyMsNEQ(v int) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldNEQ(FieldTrafficP95LatencyMs, v))
}

// TrafficP95LatencyMsIn applies the In predicate on the "traffic_p95_latency_ms" field.
func TrafficP95LatencyMsIn(vs ...int) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldIn(FieldTrafficP95LatencyMs, vs...))
}

// TrafficP95LatencyMsNotIn applies the NotIn predicate on the "traffic_p95_latency_ms" field.
func TrafficP95LatencyMsNotIn(vs ...int) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldNotIn(FieldTrafficP95LatencyMs, vs...))
}

// TrafficP95LatencyMsGT applies the GT predicate on the "traffic_p95_latency_ms" field.
func TrafficP95LatencyMsGT(v int) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldGT(FieldTrafficP95LatencyMs, v))
}

// TrafficP95LatencyMsGTE applies the GTE predicate on the "traffic_p95_latency_ms" field.
func TrafficP95LatencyMsGTE(v int) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldGTE(FieldTrafficP95LatencyMs, v))
}

// TrafficP95LatencyMsLT applies the LT predicate on the "traffic_p95_latency_ms" field.
func TrafficP95LatencyMsLT(v int) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldLT(FieldTrafficP95LatencyMs, v))
}

// TrafficP95LatencyMsLTE applies the LTE predicate on the "traffic_p95_latency_ms" field.
func TrafficP95LatencyMsLTE(v int) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldLTE(FieldTrafficP95LatencyMs, v))
}

// TrafficP95LatencyMsIsNil applies the IsNil predicate on the "traffic_p95_latency_ms" field.
func TrafficP95LatencyMsIsNil() predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldIsNull(FieldTrafficP95LatencyMs))
}

// TrafficP95LatencyMsNotNil applies the NotNil predicate on the "traffic_p95_latency_ms" field.
func TrafficP95LatencyMsNotNil() predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldNotNull(FieldTrafficP95LatencyMs))
}

// ErrorCategoryEQ applies the EQ predicate on the "error_category" field.
func ErrorCategoryEQ(v string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldEQ(FieldErrorCategory, v))
}

// ErrorCategoryNEQ applies the NEQ predicate on the "error_category" field.
func ErrorCategoryNEQ(v string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldNEQ(FieldErrorCategory, v))
}

// ErrorCategoryIn applies the In predicate on the "error_category" field.
func ErrorCategoryIn(vs ...string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldIn(FieldErrorCategory, vs...))
}

// ErrorCategoryNotIn applies the NotIn predicate on the "error_category" field.
func ErrorCategoryNotIn(vs ...string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldNotIn(FieldErrorCategory, vs...))
}

// ErrorCategoryGT applies the GT predicate on the "error_category" field.
func ErrorCategoryGT(v string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldGT(FieldErrorCategory, v))
}

// ErrorCategoryGTE applies the GTE predicate on the "error_category" field.
func ErrorCategoryGTE(v string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldGTE(FieldErrorCategory, v))
}

// ErrorCategoryLT applies the LT predicate on the "error_category" field.
func ErrorCategoryLT(v string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldLT(FieldErrorCategory, v))
}

// ErrorCategoryLTE applies the LTE predicate on the "error_category" field.
func ErrorCategoryLTE(v string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldLTE(FieldErrorCategory, v))
}

// ErrorCategoryContains applies the Contains predicate on the "error_category" field.
func ErrorCategoryContains(v string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldContains(FieldErrorCategory, v))
}

// ErrorCategoryHasPrefix applies the HasPrefix predicate on the "error_category" field.
func ErrorCategoryHasPrefix(v string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldHasPrefix(FieldErrorCategory, v))
}

// ErrorCategoryHasSuffix applies the HasSuffix predicate on the "error_category" field.
func ErrorCategoryHasSuffix(v string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldHasSuffix(FieldErrorCategory, v))
}

// ErrorCategoryIsNil applies the IsNil predicate on the "error_category" field.
func ErrorCategoryIsNil() predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldIsNull(FieldErrorCategory))
}

// ErrorCategoryNotNil applies the NotNil predicate on the "error_category" field.
func ErrorCategoryNotNil() predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldNotNull(FieldErrorCategory))
}

// ErrorCategoryEqualFold applies the EqualFold predicate on the "error_category" field.
func ErrorCategoryEqualFold(v string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldEqualFold(FieldErrorCategory, v))
}

// ErrorCategoryContainsFold applies the ContainsFold predicate on the "error_category" field.
func ErrorCategoryContainsFold(v string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldContainsFold(FieldErrorCategory, v))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldContainsFold(FieldErrorMessage, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldLTE(FieldStartedAt, v))
}

// FinishedAtEQ applies the EQ predicate on the "finished_at" field.
func FinishedAtEQ(v time.Time) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldEQ(FieldFinishedAt, v))
}

// FinishedAtNEQ applies the NEQ predicate on the "finished_at" field.
func FinishedAtNEQ(v time.Time) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldNEQ(FieldFinishedAt, v))
}

// FinishedAtIn applies the In predicate on the "finished_at" field.
func FinishedAtIn(vs ...time.Time) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldIn(FieldFinishedAt, vs...))
}

// FinishedAtNotIn applies the NotIn predicate on the "finished_at" field.
func FinishedAtNotIn(vs ...time.Time) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldNotIn(FieldFinishedAt, vs...))
}

// FinishedAtGT applies the GT predicate on the "finished_at" field.
func FinishedAtGT(v time.Time) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldGT(FieldFinishedAt, v))
}

// FinishedAtGTE applies the GTE predicate on the "finished_at" field.
func FinishedAtGTE(v time.Time) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldGTE(FieldFinishedAt, v))
}

// FinishedAtLT applies the LT predicate on the "finished_at" field.
func FinishedAtLT(v time.Time) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldLT(FieldFinishedAt, v))
}

// FinishedAtLTE applies the LTE predicate on the "finished_at" field.
func FinishedAtLTE(v time.Time) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldLTE(FieldFinishedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.FieldLTE(FieldCreatedAt, v))
}

// HasTarget applies the HasEdge predicate on the "target" edge.
func HasTarget() predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TargetTable, TargetColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTargetWith applies the HasEdge predicate on the "target" edge with a given conditions (other predicates).
func HasTargetWith(preds ...predicate.Sub2APIProviderProbeTarget) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(func(s *sql.Selector) {
		step := newTargetStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Sub2APIProviderProbeTargetRun) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Sub2APIProviderProbeTargetRun) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Sub2APIProviderProbeTargetRun) predicate.Sub2APIProviderProbeTargetRun {
	return predicate.Sub2APIProviderProbeTargetRun(sql.NotPredicates(p))
}
